// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/auth.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitslice.io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "gitslice.core.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceStartCliLoginProcedure is the fully-qualified name of the AuthService's StartCliLogin
	// RPC.
	AuthServiceStartCliLoginProcedure = "/gitslice.core.v1.AuthService/StartCliLogin"
	// AuthServicePollCliLoginProcedure is the fully-qualified name of the AuthService's PollCliLogin
	// RPC.
	AuthServicePollCliLoginProcedure = "/gitslice.core.v1.AuthService/PollCliLogin"
	// AuthServiceCompleteCliLoginProcedure is the fully-qualified name of the AuthService's
	// CompleteCliLogin RPC.
	AuthServiceCompleteCliLoginProcedure = "/gitslice.core.v1.AuthService/CompleteCliLogin"
	// AuthServiceGetAuthStatusProcedure is the fully-qualified name of the AuthService's GetAuthStatus
	// RPC.
	AuthServiceGetAuthStatusProcedure = "/gitslice.core.v1.AuthService/GetAuthStatus"
	// AuthServiceCheckUsernameAvailableProcedure is the fully-qualified name of the AuthService's
	// CheckUsernameAvailable RPC.
	AuthServiceCheckUsernameAvailableProcedure = "/gitslice.core.v1.AuthService/CheckUsernameAvailable"
	// AuthServiceChooseUsernameProcedure is the fully-qualified name of the AuthService's
	// ChooseUsername RPC.
	AuthServiceChooseUsernameProcedure = "/gitslice.core.v1.AuthService/ChooseUsername"
	// AuthServiceRegisterAgentProcedure is the fully-qualified name of the AuthService's RegisterAgent
	// RPC.
	AuthServiceRegisterAgentProcedure = "/gitslice.core.v1.AuthService/RegisterAgent"
	// AuthServiceListPendingClaimsProcedure is the fully-qualified name of the AuthService's
	// ListPendingClaims RPC.
	AuthServiceListPendingClaimsProcedure = "/gitslice.core.v1.AuthService/ListPendingClaims"
	// AuthServiceAcceptClaimProcedure is the fully-qualified name of the AuthService's AcceptClaim RPC.
	AuthServiceAcceptClaimProcedure = "/gitslice.core.v1.AuthService/AcceptClaim"
	// AuthServiceListOwnedAgentsProcedure is the fully-qualified name of the AuthService's
	// ListOwnedAgents RPC.
	AuthServiceListOwnedAgentsProcedure = "/gitslice.core.v1.AuthService/ListOwnedAgents"
	// AuthServiceCreateOrganizationProcedure is the fully-qualified name of the AuthService's
	// CreateOrganization RPC.
	AuthServiceCreateOrganizationProcedure = "/gitslice.core.v1.AuthService/CreateOrganization"
	// AuthServiceListAccountMembersProcedure is the fully-qualified name of the AuthService's
	// ListAccountMembers RPC.
	AuthServiceListAccountMembersProcedure = "/gitslice.core.v1.AuthService/ListAccountMembers"
	// AuthServiceSetAccountMemberProcedure is the fully-qualified name of the AuthService's
	// SetAccountMember RPC.
	AuthServiceSetAccountMemberProcedure = "/gitslice.core.v1.AuthService/SetAccountMember"
	// AuthServiceRemoveAccountMemberProcedure is the fully-qualified name of the AuthService's
	// RemoveAccountMember RPC.
	AuthServiceRemoveAccountMemberProcedure = "/gitslice.core.v1.AuthService/RemoveAccountMember"
	// AuthServiceInviteAccountMemberProcedure is the fully-qualified name of the AuthService's
	// InviteAccountMember RPC.
	AuthServiceInviteAccountMemberProcedure = "/gitslice.core.v1.AuthService/InviteAccountMember"
	// AuthServiceListAccountInvitationsProcedure is the fully-qualified name of the AuthService's
	// ListAccountInvitations RPC.
	AuthServiceListAccountInvitationsProcedure = "/gitslice.core.v1.AuthService/ListAccountInvitations"
	// AuthServiceListMyInvitationsProcedure is the fully-qualified name of the AuthService's
	// ListMyInvitations RPC.
	AuthServiceListMyInvitationsProcedure = "/gitslice.core.v1.AuthService/ListMyInvitations"
	// AuthServiceRespondToInvitationProcedure is the fully-qualified name of the AuthService's
	// RespondToInvitation RPC.
	AuthServiceRespondToInvitationProcedure = "/gitslice.core.v1.AuthService/RespondToInvitation"
	// AuthServiceCancelAccountInvitationProcedure is the fully-qualified name of the AuthService's
	// CancelAccountInvitation RPC.
	AuthServiceCancelAccountInvitationProcedure = "/gitslice.core.v1.AuthService/CancelAccountInvitation"
	// AuthServiceGetAccountProfileProcedure is the fully-qualified name of the AuthService's
	// GetAccountProfile RPC.
	AuthServiceGetAccountProfileProcedure = "/gitslice.core.v1.AuthService/GetAccountProfile"
	// AuthServiceUpdateAccountProfileProcedure is the fully-qualified name of the AuthService's
	// UpdateAccountProfile RPC.
	AuthServiceUpdateAccountProfileProcedure = "/gitslice.core.v1.AuthService/UpdateAccountProfile"
)

// AuthServiceClient is a client for the gitslice.core.v1.AuthService service.
type AuthServiceClient interface {
	StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error)
	PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error)
	CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error)
	GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error)
	CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error)
	ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error)
	// RegisterAgent self-registers an agent with its own personal account and
	// returns a long-lived API key. Unauthenticated; disabled unless the server
	// sets GITSLICE_AGENT_SIGNUP_ENABLED. See design/20_agent_signup_and_claim.md.
	RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error)
	// ListPendingClaims lists agent registrations the caller may claim: unclaimed
	// agents whose owner email is one of the caller's verified emails.
	ListPendingClaims(context.Context, *connect.Request[v1.ListPendingClaimsRequest]) (*connect.Response[v1.ListPendingClaimsResponse], error)
	// AcceptClaim makes the caller an owner of the agent's account. The agent
	// keeps its own access, so the account becomes co-owned.
	AcceptClaim(context.Context, *connect.Request[v1.AcceptClaimRequest]) (*connect.Response[v1.AcceptClaimResponse], error)
	// ListOwnedAgents lists the self-registered agents whose accounts the caller
	// owns (typically after AcceptClaim), with basic activity.
	ListOwnedAgents(context.Context, *connect.Request[v1.ListOwnedAgentsRequest]) (*connect.Response[v1.ListOwnedAgentsResponse], error)
	// CreateOrganization creates an organization account (with a private home
	// slice). Any signed-in user with a personal account may create one and
	// becomes its only owner; names reserved for sign-up are refused, and a user
	// owns at most 20 organizations they created. Operators (the server's
	// GITSLICE_OPERATOR_SUBJECTS) may use reserved names and name other owners.
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	// ListAccountMembers lists an account's members. Any member may call it.
	ListAccountMembers(context.Context, *connect.Request[v1.ListAccountMembersRequest]) (*connect.Response[v1.ListAccountMembersResponse], error)
	// SetAccountMember changes a member's role. Owners and admins may call it;
	// only owners grant or revoke owner. Adding someone who is not a member is
	// for operators only; everyone else invites them (InviteAccountMember).
	SetAccountMember(context.Context, *connect.Request[v1.SetAccountMemberRequest]) (*connect.Response[v1.SetAccountMemberResponse], error)
	// RemoveAccountMember removes a user from an organization. The last owner
	// cannot be removed.
	RemoveAccountMember(context.Context, *connect.Request[v1.RemoveAccountMemberRequest]) (*connect.Response[v1.RemoveAccountMemberResponse], error)
	// InviteAccountMember invites a user to an organization with a role. They
	// become a member only when they accept. Owners and admins may invite;
	// only owners invite owners. Inviting someone already invited replaces the
	// invitation's role.
	InviteAccountMember(context.Context, *connect.Request[v1.InviteAccountMemberRequest]) (*connect.Response[v1.InviteAccountMemberResponse], error)
	// ListAccountInvitations lists an organization's pending invitations, for
	// its owners and admins.
	ListAccountInvitations(context.Context, *connect.Request[v1.ListAccountInvitationsRequest]) (*connect.Response[v1.ListAccountInvitationsResponse], error)
	// ListMyInvitations lists the caller's pending invitations.
	ListMyInvitations(context.Context, *connect.Request[v1.ListMyInvitationsRequest]) (*connect.Response[v1.ListMyInvitationsResponse], error)
	// RespondToInvitation accepts or declines the caller's invitation to an
	// organization. Either way the invitation is gone afterwards.
	RespondToInvitation(context.Context, *connect.Request[v1.RespondToInvitationRequest]) (*connect.Response[v1.RespondToInvitationResponse], error)
	// CancelAccountInvitation withdraws a pending invitation. Owners and admins
	// may call it.
	CancelAccountInvitation(context.Context, *connect.Request[v1.CancelAccountInvitationRequest]) (*connect.Response[v1.CancelAccountInvitationResponse], error)
	// GetAccountProfile returns an account's public profile. Anyone may call it,
	// signed in or not.
	GetAccountProfile(context.Context, *connect.Request[v1.GetAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error)
	// UpdateAccountProfile changes an account's profile: an organization's by
	// its owners and admins, a personal account's by its person.
	UpdateAccountProfile(context.Context, *connect.Request[v1.UpdateAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error)
}

// NewAuthServiceClient constructs a client for the gitslice.core.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_proto_core_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		startCliLogin: connect.NewClient[v1.StartCliLoginRequest, v1.StartCliLoginResponse](
			httpClient,
			baseURL+AuthServiceStartCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("StartCliLogin")),
			connect.WithClientOptions(opts...),
		),
		pollCliLogin: connect.NewClient[v1.PollCliLoginRequest, v1.PollCliLoginResponse](
			httpClient,
			baseURL+AuthServicePollCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("PollCliLogin")),
			connect.WithClientOptions(opts...),
		),
		completeCliLogin: connect.NewClient[v1.CompleteCliLoginRequest, v1.CompleteCliLoginResponse](
			httpClient,
			baseURL+AuthServiceCompleteCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("CompleteCliLogin")),
			connect.WithClientOptions(opts...),
		),
		getAuthStatus: connect.NewClient[v1.GetAuthStatusRequest, v1.GetAuthStatusResponse](
			httpClient,
			baseURL+AuthServiceGetAuthStatusProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthStatus")),
			connect.WithClientOptions(opts...),
		),
		checkUsernameAvailable: connect.NewClient[v1.CheckUsernameAvailableRequest, v1.CheckUsernameAvailableResponse](
			httpClient,
			baseURL+AuthServiceCheckUsernameAvailableProcedure,
			connect.WithSchema(authServiceMethods.ByName("CheckUsernameAvailable")),
			connect.WithClientOptions(opts...),
		),
		chooseUsername: connect.NewClient[v1.ChooseUsernameRequest, v1.ChooseUsernameResponse](
			httpClient,
			baseURL+AuthServiceChooseUsernameProcedure,
			connect.WithSchema(authServiceMethods.ByName("ChooseUsername")),
			connect.WithClientOptions(opts...),
		),
		registerAgent: connect.NewClient[v1.RegisterAgentRequest, v1.RegisterAgentResponse](
			httpClient,
			baseURL+AuthServiceRegisterAgentProcedure,
			connect.WithSchema(authServiceMethods.ByName("RegisterAgent")),
			connect.WithClientOptions(opts...),
		),
		listPendingClaims: connect.NewClient[v1.ListPendingClaimsRequest, v1.ListPendingClaimsResponse](
			httpClient,
			baseURL+AuthServiceListPendingClaimsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListPendingClaims")),
			connect.WithClientOptions(opts...),
		),
		acceptClaim: connect.NewClient[v1.AcceptClaimRequest, v1.AcceptClaimResponse](
			httpClient,
			baseURL+AuthServiceAcceptClaimProcedure,
			connect.WithSchema(authServiceMethods.ByName("AcceptClaim")),
			connect.WithClientOptions(opts...),
		),
		listOwnedAgents: connect.NewClient[v1.ListOwnedAgentsRequest, v1.ListOwnedAgentsResponse](
			httpClient,
			baseURL+AuthServiceListOwnedAgentsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListOwnedAgents")),
			connect.WithClientOptions(opts...),
		),
		createOrganization: connect.NewClient[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse](
			httpClient,
			baseURL+AuthServiceCreateOrganizationProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateOrganization")),
			connect.WithClientOptions(opts...),
		),
		listAccountMembers: connect.NewClient[v1.ListAccountMembersRequest, v1.ListAccountMembersResponse](
			httpClient,
			baseURL+AuthServiceListAccountMembersProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAccountMembers")),
			connect.WithClientOptions(opts...),
		),
		setAccountMember: connect.NewClient[v1.SetAccountMemberRequest, v1.SetAccountMemberResponse](
			httpClient,
			baseURL+AuthServiceSetAccountMemberProcedure,
			connect.WithSchema(authServiceMethods.ByName("SetAccountMember")),
			connect.WithClientOptions(opts...),
		),
		removeAccountMember: connect.NewClient[v1.RemoveAccountMemberRequest, v1.RemoveAccountMemberResponse](
			httpClient,
			baseURL+AuthServiceRemoveAccountMemberProcedure,
			connect.WithSchema(authServiceMethods.ByName("RemoveAccountMember")),
			connect.WithClientOptions(opts...),
		),
		inviteAccountMember: connect.NewClient[v1.InviteAccountMemberRequest, v1.InviteAccountMemberResponse](
			httpClient,
			baseURL+AuthServiceInviteAccountMemberProcedure,
			connect.WithSchema(authServiceMethods.ByName("InviteAccountMember")),
			connect.WithClientOptions(opts...),
		),
		listAccountInvitations: connect.NewClient[v1.ListAccountInvitationsRequest, v1.ListAccountInvitationsResponse](
			httpClient,
			baseURL+AuthServiceListAccountInvitationsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListAccountInvitations")),
			connect.WithClientOptions(opts...),
		),
		listMyInvitations: connect.NewClient[v1.ListMyInvitationsRequest, v1.ListMyInvitationsResponse](
			httpClient,
			baseURL+AuthServiceListMyInvitationsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListMyInvitations")),
			connect.WithClientOptions(opts...),
		),
		respondToInvitation: connect.NewClient[v1.RespondToInvitationRequest, v1.RespondToInvitationResponse](
			httpClient,
			baseURL+AuthServiceRespondToInvitationProcedure,
			connect.WithSchema(authServiceMethods.ByName("RespondToInvitation")),
			connect.WithClientOptions(opts...),
		),
		cancelAccountInvitation: connect.NewClient[v1.CancelAccountInvitationRequest, v1.CancelAccountInvitationResponse](
			httpClient,
			baseURL+AuthServiceCancelAccountInvitationProcedure,
			connect.WithSchema(authServiceMethods.ByName("CancelAccountInvitation")),
			connect.WithClientOptions(opts...),
		),
		getAccountProfile: connect.NewClient[v1.GetAccountProfileRequest, v1.AccountProfile](
			httpClient,
			baseURL+AuthServiceGetAccountProfileProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAccountProfile")),
			connect.WithClientOptions(opts...),
		),
		updateAccountProfile: connect.NewClient[v1.UpdateAccountProfileRequest, v1.AccountProfile](
			httpClient,
			baseURL+AuthServiceUpdateAccountProfileProcedure,
			connect.WithSchema(authServiceMethods.ByName("UpdateAccountProfile")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	startCliLogin           *connect.Client[v1.StartCliLoginRequest, v1.StartCliLoginResponse]
	pollCliLogin            *connect.Client[v1.PollCliLoginRequest, v1.PollCliLoginResponse]
	completeCliLogin        *connect.Client[v1.CompleteCliLoginRequest, v1.CompleteCliLoginResponse]
	getAuthStatus           *connect.Client[v1.GetAuthStatusRequest, v1.GetAuthStatusResponse]
	checkUsernameAvailable  *connect.Client[v1.CheckUsernameAvailableRequest, v1.CheckUsernameAvailableResponse]
	chooseUsername          *connect.Client[v1.ChooseUsernameRequest, v1.ChooseUsernameResponse]
	registerAgent           *connect.Client[v1.RegisterAgentRequest, v1.RegisterAgentResponse]
	listPendingClaims       *connect.Client[v1.ListPendingClaimsRequest, v1.ListPendingClaimsResponse]
	acceptClaim             *connect.Client[v1.AcceptClaimRequest, v1.AcceptClaimResponse]
	listOwnedAgents         *connect.Client[v1.ListOwnedAgentsRequest, v1.ListOwnedAgentsResponse]
	createOrganization      *connect.Client[v1.CreateOrganizationRequest, v1.CreateOrganizationResponse]
	listAccountMembers      *connect.Client[v1.ListAccountMembersRequest, v1.ListAccountMembersResponse]
	setAccountMember        *connect.Client[v1.SetAccountMemberRequest, v1.SetAccountMemberResponse]
	removeAccountMember     *connect.Client[v1.RemoveAccountMemberRequest, v1.RemoveAccountMemberResponse]
	inviteAccountMember     *connect.Client[v1.InviteAccountMemberRequest, v1.InviteAccountMemberResponse]
	listAccountInvitations  *connect.Client[v1.ListAccountInvitationsRequest, v1.ListAccountInvitationsResponse]
	listMyInvitations       *connect.Client[v1.ListMyInvitationsRequest, v1.ListMyInvitationsResponse]
	respondToInvitation     *connect.Client[v1.RespondToInvitationRequest, v1.RespondToInvitationResponse]
	cancelAccountInvitation *connect.Client[v1.CancelAccountInvitationRequest, v1.CancelAccountInvitationResponse]
	getAccountProfile       *connect.Client[v1.GetAccountProfileRequest, v1.AccountProfile]
	updateAccountProfile    *connect.Client[v1.UpdateAccountProfileRequest, v1.AccountProfile]
}

// StartCliLogin calls gitslice.core.v1.AuthService.StartCliLogin.
func (c *authServiceClient) StartCliLogin(ctx context.Context, req *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error) {
	return c.startCliLogin.CallUnary(ctx, req)
}

// PollCliLogin calls gitslice.core.v1.AuthService.PollCliLogin.
func (c *authServiceClient) PollCliLogin(ctx context.Context, req *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error) {
	return c.pollCliLogin.CallUnary(ctx, req)
}

// CompleteCliLogin calls gitslice.core.v1.AuthService.CompleteCliLogin.
func (c *authServiceClient) CompleteCliLogin(ctx context.Context, req *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error) {
	return c.completeCliLogin.CallUnary(ctx, req)
}

// GetAuthStatus calls gitslice.core.v1.AuthService.GetAuthStatus.
func (c *authServiceClient) GetAuthStatus(ctx context.Context, req *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error) {
	return c.getAuthStatus.CallUnary(ctx, req)
}

// CheckUsernameAvailable calls gitslice.core.v1.AuthService.CheckUsernameAvailable.
func (c *authServiceClient) CheckUsernameAvailable(ctx context.Context, req *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error) {
	return c.checkUsernameAvailable.CallUnary(ctx, req)
}

// ChooseUsername calls gitslice.core.v1.AuthService.ChooseUsername.
func (c *authServiceClient) ChooseUsername(ctx context.Context, req *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error) {
	return c.chooseUsername.CallUnary(ctx, req)
}

// RegisterAgent calls gitslice.core.v1.AuthService.RegisterAgent.
func (c *authServiceClient) RegisterAgent(ctx context.Context, req *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error) {
	return c.registerAgent.CallUnary(ctx, req)
}

// ListPendingClaims calls gitslice.core.v1.AuthService.ListPendingClaims.
func (c *authServiceClient) ListPendingClaims(ctx context.Context, req *connect.Request[v1.ListPendingClaimsRequest]) (*connect.Response[v1.ListPendingClaimsResponse], error) {
	return c.listPendingClaims.CallUnary(ctx, req)
}

// AcceptClaim calls gitslice.core.v1.AuthService.AcceptClaim.
func (c *authServiceClient) AcceptClaim(ctx context.Context, req *connect.Request[v1.AcceptClaimRequest]) (*connect.Response[v1.AcceptClaimResponse], error) {
	return c.acceptClaim.CallUnary(ctx, req)
}

// ListOwnedAgents calls gitslice.core.v1.AuthService.ListOwnedAgents.
func (c *authServiceClient) ListOwnedAgents(ctx context.Context, req *connect.Request[v1.ListOwnedAgentsRequest]) (*connect.Response[v1.ListOwnedAgentsResponse], error) {
	return c.listOwnedAgents.CallUnary(ctx, req)
}

// CreateOrganization calls gitslice.core.v1.AuthService.CreateOrganization.
func (c *authServiceClient) CreateOrganization(ctx context.Context, req *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return c.createOrganization.CallUnary(ctx, req)
}

// ListAccountMembers calls gitslice.core.v1.AuthService.ListAccountMembers.
func (c *authServiceClient) ListAccountMembers(ctx context.Context, req *connect.Request[v1.ListAccountMembersRequest]) (*connect.Response[v1.ListAccountMembersResponse], error) {
	return c.listAccountMembers.CallUnary(ctx, req)
}

// SetAccountMember calls gitslice.core.v1.AuthService.SetAccountMember.
func (c *authServiceClient) SetAccountMember(ctx context.Context, req *connect.Request[v1.SetAccountMemberRequest]) (*connect.Response[v1.SetAccountMemberResponse], error) {
	return c.setAccountMember.CallUnary(ctx, req)
}

// RemoveAccountMember calls gitslice.core.v1.AuthService.RemoveAccountMember.
func (c *authServiceClient) RemoveAccountMember(ctx context.Context, req *connect.Request[v1.RemoveAccountMemberRequest]) (*connect.Response[v1.RemoveAccountMemberResponse], error) {
	return c.removeAccountMember.CallUnary(ctx, req)
}

// InviteAccountMember calls gitslice.core.v1.AuthService.InviteAccountMember.
func (c *authServiceClient) InviteAccountMember(ctx context.Context, req *connect.Request[v1.InviteAccountMemberRequest]) (*connect.Response[v1.InviteAccountMemberResponse], error) {
	return c.inviteAccountMember.CallUnary(ctx, req)
}

// ListAccountInvitations calls gitslice.core.v1.AuthService.ListAccountInvitations.
func (c *authServiceClient) ListAccountInvitations(ctx context.Context, req *connect.Request[v1.ListAccountInvitationsRequest]) (*connect.Response[v1.ListAccountInvitationsResponse], error) {
	return c.listAccountInvitations.CallUnary(ctx, req)
}

// ListMyInvitations calls gitslice.core.v1.AuthService.ListMyInvitations.
func (c *authServiceClient) ListMyInvitations(ctx context.Context, req *connect.Request[v1.ListMyInvitationsRequest]) (*connect.Response[v1.ListMyInvitationsResponse], error) {
	return c.listMyInvitations.CallUnary(ctx, req)
}

// RespondToInvitation calls gitslice.core.v1.AuthService.RespondToInvitation.
func (c *authServiceClient) RespondToInvitation(ctx context.Context, req *connect.Request[v1.RespondToInvitationRequest]) (*connect.Response[v1.RespondToInvitationResponse], error) {
	return c.respondToInvitation.CallUnary(ctx, req)
}

// CancelAccountInvitation calls gitslice.core.v1.AuthService.CancelAccountInvitation.
func (c *authServiceClient) CancelAccountInvitation(ctx context.Context, req *connect.Request[v1.CancelAccountInvitationRequest]) (*connect.Response[v1.CancelAccountInvitationResponse], error) {
	return c.cancelAccountInvitation.CallUnary(ctx, req)
}

// GetAccountProfile calls gitslice.core.v1.AuthService.GetAccountProfile.
func (c *authServiceClient) GetAccountProfile(ctx context.Context, req *connect.Request[v1.GetAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error) {
	return c.getAccountProfile.CallUnary(ctx, req)
}

// UpdateAccountProfile calls gitslice.core.v1.AuthService.UpdateAccountProfile.
func (c *authServiceClient) UpdateAccountProfile(ctx context.Context, req *connect.Request[v1.UpdateAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error) {
	return c.updateAccountProfile.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the gitslice.core.v1.AuthService service.
type AuthServiceHandler interface {
	StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error)
	PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error)
	CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error)
	GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error)
	CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error)
	ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error)
	// RegisterAgent self-registers an agent with its own personal account and
	// returns a long-lived API key. Unauthenticated; disabled unless the server
	// sets GITSLICE_AGENT_SIGNUP_ENABLED. See design/20_agent_signup_and_claim.md.
	RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error)
	// ListPendingClaims lists agent registrations the caller may claim: unclaimed
	// agents whose owner email is one of the caller's verified emails.
	ListPendingClaims(context.Context, *connect.Request[v1.ListPendingClaimsRequest]) (*connect.Response[v1.ListPendingClaimsResponse], error)
	// AcceptClaim makes the caller an owner of the agent's account. The agent
	// keeps its own access, so the account becomes co-owned.
	AcceptClaim(context.Context, *connect.Request[v1.AcceptClaimRequest]) (*connect.Response[v1.AcceptClaimResponse], error)
	// ListOwnedAgents lists the self-registered agents whose accounts the caller
	// owns (typically after AcceptClaim), with basic activity.
	ListOwnedAgents(context.Context, *connect.Request[v1.ListOwnedAgentsRequest]) (*connect.Response[v1.ListOwnedAgentsResponse], error)
	// CreateOrganization creates an organization account (with a private home
	// slice). Any signed-in user with a personal account may create one and
	// becomes its only owner; names reserved for sign-up are refused, and a user
	// owns at most 20 organizations they created. Operators (the server's
	// GITSLICE_OPERATOR_SUBJECTS) may use reserved names and name other owners.
	CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error)
	// ListAccountMembers lists an account's members. Any member may call it.
	ListAccountMembers(context.Context, *connect.Request[v1.ListAccountMembersRequest]) (*connect.Response[v1.ListAccountMembersResponse], error)
	// SetAccountMember changes a member's role. Owners and admins may call it;
	// only owners grant or revoke owner. Adding someone who is not a member is
	// for operators only; everyone else invites them (InviteAccountMember).
	SetAccountMember(context.Context, *connect.Request[v1.SetAccountMemberRequest]) (*connect.Response[v1.SetAccountMemberResponse], error)
	// RemoveAccountMember removes a user from an organization. The last owner
	// cannot be removed.
	RemoveAccountMember(context.Context, *connect.Request[v1.RemoveAccountMemberRequest]) (*connect.Response[v1.RemoveAccountMemberResponse], error)
	// InviteAccountMember invites a user to an organization with a role. They
	// become a member only when they accept. Owners and admins may invite;
	// only owners invite owners. Inviting someone already invited replaces the
	// invitation's role.
	InviteAccountMember(context.Context, *connect.Request[v1.InviteAccountMemberRequest]) (*connect.Response[v1.InviteAccountMemberResponse], error)
	// ListAccountInvitations lists an organization's pending invitations, for
	// its owners and admins.
	ListAccountInvitations(context.Context, *connect.Request[v1.ListAccountInvitationsRequest]) (*connect.Response[v1.ListAccountInvitationsResponse], error)
	// ListMyInvitations lists the caller's pending invitations.
	ListMyInvitations(context.Context, *connect.Request[v1.ListMyInvitationsRequest]) (*connect.Response[v1.ListMyInvitationsResponse], error)
	// RespondToInvitation accepts or declines the caller's invitation to an
	// organization. Either way the invitation is gone afterwards.
	RespondToInvitation(context.Context, *connect.Request[v1.RespondToInvitationRequest]) (*connect.Response[v1.RespondToInvitationResponse], error)
	// CancelAccountInvitation withdraws a pending invitation. Owners and admins
	// may call it.
	CancelAccountInvitation(context.Context, *connect.Request[v1.CancelAccountInvitationRequest]) (*connect.Response[v1.CancelAccountInvitationResponse], error)
	// GetAccountProfile returns an account's public profile. Anyone may call it,
	// signed in or not.
	GetAccountProfile(context.Context, *connect.Request[v1.GetAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error)
	// UpdateAccountProfile changes an account's profile: an organization's by
	// its owners and admins, a personal account's by its person.
	UpdateAccountProfile(context.Context, *connect.Request[v1.UpdateAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_proto_core_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceStartCliLoginHandler := connect.NewUnaryHandler(
		AuthServiceStartCliLoginProcedure,
		svc.StartCliLogin,
		connect.WithSchema(authServiceMethods.ByName("StartCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServicePollCliLoginHandler := connect.NewUnaryHandler(
		AuthServicePollCliLoginProcedure,
		svc.PollCliLogin,
		connect.WithSchema(authServiceMethods.ByName("PollCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCompleteCliLoginHandler := connect.NewUnaryHandler(
		AuthServiceCompleteCliLoginProcedure,
		svc.CompleteCliLogin,
		connect.WithSchema(authServiceMethods.ByName("CompleteCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthStatusHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthStatusProcedure,
		svc.GetAuthStatus,
		connect.WithSchema(authServiceMethods.ByName("GetAuthStatus")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCheckUsernameAvailableHandler := connect.NewUnaryHandler(
		AuthServiceCheckUsernameAvailableProcedure,
		svc.CheckUsernameAvailable,
		connect.WithSchema(authServiceMethods.ByName("CheckUsernameAvailable")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceChooseUsernameHandler := connect.NewUnaryHandler(
		AuthServiceChooseUsernameProcedure,
		svc.ChooseUsername,
		connect.WithSchema(authServiceMethods.ByName("ChooseUsername")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRegisterAgentHandler := connect.NewUnaryHandler(
		AuthServiceRegisterAgentProcedure,
		svc.RegisterAgent,
		connect.WithSchema(authServiceMethods.ByName("RegisterAgent")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListPendingClaimsHandler := connect.NewUnaryHandler(
		AuthServiceListPendingClaimsProcedure,
		svc.ListPendingClaims,
		connect.WithSchema(authServiceMethods.ByName("ListPendingClaims")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAcceptClaimHandler := connect.NewUnaryHandler(
		AuthServiceAcceptClaimProcedure,
		svc.AcceptClaim,
		connect.WithSchema(authServiceMethods.ByName("AcceptClaim")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListOwnedAgentsHandler := connect.NewUnaryHandler(
		AuthServiceListOwnedAgentsProcedure,
		svc.ListOwnedAgents,
		connect.WithSchema(authServiceMethods.ByName("ListOwnedAgents")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCreateOrganizationHandler := connect.NewUnaryHandler(
		AuthServiceCreateOrganizationProcedure,
		svc.CreateOrganization,
		connect.WithSchema(authServiceMethods.ByName("CreateOrganization")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListAccountMembersHandler := connect.NewUnaryHandler(
		AuthServiceListAccountMembersProcedure,
		svc.ListAccountMembers,
		connect.WithSchema(authServiceMethods.ByName("ListAccountMembers")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceSetAccountMemberHandler := connect.NewUnaryHandler(
		AuthServiceSetAccountMemberProcedure,
		svc.SetAccountMember,
		connect.WithSchema(authServiceMethods.ByName("SetAccountMember")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRemoveAccountMemberHandler := connect.NewUnaryHandler(
		AuthServiceRemoveAccountMemberProcedure,
		svc.RemoveAccountMember,
		connect.WithSchema(authServiceMethods.ByName("RemoveAccountMember")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceInviteAccountMemberHandler := connect.NewUnaryHandler(
		AuthServiceInviteAccountMemberProcedure,
		svc.InviteAccountMember,
		connect.WithSchema(authServiceMethods.ByName("InviteAccountMember")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListAccountInvitationsHandler := connect.NewUnaryHandler(
		AuthServiceListAccountInvitationsProcedure,
		svc.ListAccountInvitations,
		connect.WithSchema(authServiceMethods.ByName("ListAccountInvitations")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListMyInvitationsHandler := connect.NewUnaryHandler(
		AuthServiceListMyInvitationsProcedure,
		svc.ListMyInvitations,
		connect.WithSchema(authServiceMethods.ByName("ListMyInvitations")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRespondToInvitationHandler := connect.NewUnaryHandler(
		AuthServiceRespondToInvitationProcedure,
		svc.RespondToInvitation,
		connect.WithSchema(authServiceMethods.ByName("RespondToInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCancelAccountInvitationHandler := connect.NewUnaryHandler(
		AuthServiceCancelAccountInvitationProcedure,
		svc.CancelAccountInvitation,
		connect.WithSchema(authServiceMethods.ByName("CancelAccountInvitation")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAccountProfileHandler := connect.NewUnaryHandler(
		AuthServiceGetAccountProfileProcedure,
		svc.GetAccountProfile,
		connect.WithSchema(authServiceMethods.ByName("GetAccountProfile")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceUpdateAccountProfileHandler := connect.NewUnaryHandler(
		AuthServiceUpdateAccountProfileProcedure,
		svc.UpdateAccountProfile,
		connect.WithSchema(authServiceMethods.ByName("UpdateAccountProfile")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceStartCliLoginProcedure:
			authServiceStartCliLoginHandler.ServeHTTP(w, r)
		case AuthServicePollCliLoginProcedure:
			authServicePollCliLoginHandler.ServeHTTP(w, r)
		case AuthServiceCompleteCliLoginProcedure:
			authServiceCompleteCliLoginHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthStatusProcedure:
			authServiceGetAuthStatusHandler.ServeHTTP(w, r)
		case AuthServiceCheckUsernameAvailableProcedure:
			authServiceCheckUsernameAvailableHandler.ServeHTTP(w, r)
		case AuthServiceChooseUsernameProcedure:
			authServiceChooseUsernameHandler.ServeHTTP(w, r)
		case AuthServiceRegisterAgentProcedure:
			authServiceRegisterAgentHandler.ServeHTTP(w, r)
		case AuthServiceListPendingClaimsProcedure:
			authServiceListPendingClaimsHandler.ServeHTTP(w, r)
		case AuthServiceAcceptClaimProcedure:
			authServiceAcceptClaimHandler.ServeHTTP(w, r)
		case AuthServiceListOwnedAgentsProcedure:
			authServiceListOwnedAgentsHandler.ServeHTTP(w, r)
		case AuthServiceCreateOrganizationProcedure:
			authServiceCreateOrganizationHandler.ServeHTTP(w, r)
		case AuthServiceListAccountMembersProcedure:
			authServiceListAccountMembersHandler.ServeHTTP(w, r)
		case AuthServiceSetAccountMemberProcedure:
			authServiceSetAccountMemberHandler.ServeHTTP(w, r)
		case AuthServiceRemoveAccountMemberProcedure:
			authServiceRemoveAccountMemberHandler.ServeHTTP(w, r)
		case AuthServiceInviteAccountMemberProcedure:
			authServiceInviteAccountMemberHandler.ServeHTTP(w, r)
		case AuthServiceListAccountInvitationsProcedure:
			authServiceListAccountInvitationsHandler.ServeHTTP(w, r)
		case AuthServiceListMyInvitationsProcedure:
			authServiceListMyInvitationsHandler.ServeHTTP(w, r)
		case AuthServiceRespondToInvitationProcedure:
			authServiceRespondToInvitationHandler.ServeHTTP(w, r)
		case AuthServiceCancelAccountInvitationProcedure:
			authServiceCancelAccountInvitationHandler.ServeHTTP(w, r)
		case AuthServiceGetAccountProfileProcedure:
			authServiceGetAccountProfileHandler.ServeHTTP(w, r)
		case AuthServiceUpdateAccountProfileProcedure:
			authServiceUpdateAccountProfileHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.StartCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.PollCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CompleteCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.GetAuthStatus is not implemented"))
}

func (UnimplementedAuthServiceHandler) CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CheckUsernameAvailable is not implemented"))
}

func (UnimplementedAuthServiceHandler) ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ChooseUsername is not implemented"))
}

func (UnimplementedAuthServiceHandler) RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.RegisterAgent is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListPendingClaims(context.Context, *connect.Request[v1.ListPendingClaimsRequest]) (*connect.Response[v1.ListPendingClaimsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ListPendingClaims is not implemented"))
}

func (UnimplementedAuthServiceHandler) AcceptClaim(context.Context, *connect.Request[v1.AcceptClaimRequest]) (*connect.Response[v1.AcceptClaimResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.AcceptClaim is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListOwnedAgents(context.Context, *connect.Request[v1.ListOwnedAgentsRequest]) (*connect.Response[v1.ListOwnedAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ListOwnedAgents is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateOrganization(context.Context, *connect.Request[v1.CreateOrganizationRequest]) (*connect.Response[v1.CreateOrganizationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CreateOrganization is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListAccountMembers(context.Context, *connect.Request[v1.ListAccountMembersRequest]) (*connect.Response[v1.ListAccountMembersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ListAccountMembers is not implemented"))
}

func (UnimplementedAuthServiceHandler) SetAccountMember(context.Context, *connect.Request[v1.SetAccountMemberRequest]) (*connect.Response[v1.SetAccountMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.SetAccountMember is not implemented"))
}

func (UnimplementedAuthServiceHandler) RemoveAccountMember(context.Context, *connect.Request[v1.RemoveAccountMemberRequest]) (*connect.Response[v1.RemoveAccountMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.RemoveAccountMember is not implemented"))
}

func (UnimplementedAuthServiceHandler) InviteAccountMember(context.Context, *connect.Request[v1.InviteAccountMemberRequest]) (*connect.Response[v1.InviteAccountMemberResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.InviteAccountMember is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListAccountInvitations(context.Context, *connect.Request[v1.ListAccountInvitationsRequest]) (*connect.Response[v1.ListAccountInvitationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ListAccountInvitations is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListMyInvitations(context.Context, *connect.Request[v1.ListMyInvitationsRequest]) (*connect.Response[v1.ListMyInvitationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ListMyInvitations is not implemented"))
}

func (UnimplementedAuthServiceHandler) RespondToInvitation(context.Context, *connect.Request[v1.RespondToInvitationRequest]) (*connect.Response[v1.RespondToInvitationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.RespondToInvitation is not implemented"))
}

func (UnimplementedAuthServiceHandler) CancelAccountInvitation(context.Context, *connect.Request[v1.CancelAccountInvitationRequest]) (*connect.Response[v1.CancelAccountInvitationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CancelAccountInvitation is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAccountProfile(context.Context, *connect.Request[v1.GetAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.GetAccountProfile is not implemented"))
}

func (UnimplementedAuthServiceHandler) UpdateAccountProfile(context.Context, *connect.Request[v1.UpdateAccountProfileRequest]) (*connect.Response[v1.AccountProfile], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.UpdateAccountProfile is not implemented"))
}
