// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/auth.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitslice-io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "gitslice.core.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceStartCliLoginProcedure is the fully-qualified name of the AuthService's StartCliLogin
	// RPC.
	AuthServiceStartCliLoginProcedure = "/gitslice.core.v1.AuthService/StartCliLogin"
	// AuthServicePollCliLoginProcedure is the fully-qualified name of the AuthService's PollCliLogin
	// RPC.
	AuthServicePollCliLoginProcedure = "/gitslice.core.v1.AuthService/PollCliLogin"
	// AuthServiceCompleteCliLoginProcedure is the fully-qualified name of the AuthService's
	// CompleteCliLogin RPC.
	AuthServiceCompleteCliLoginProcedure = "/gitslice.core.v1.AuthService/CompleteCliLogin"
	// AuthServiceGetAuthStatusProcedure is the fully-qualified name of the AuthService's GetAuthStatus
	// RPC.
	AuthServiceGetAuthStatusProcedure = "/gitslice.core.v1.AuthService/GetAuthStatus"
	// AuthServiceCheckUsernameAvailableProcedure is the fully-qualified name of the AuthService's
	// CheckUsernameAvailable RPC.
	AuthServiceCheckUsernameAvailableProcedure = "/gitslice.core.v1.AuthService/CheckUsernameAvailable"
	// AuthServiceChooseUsernameProcedure is the fully-qualified name of the AuthService's
	// ChooseUsername RPC.
	AuthServiceChooseUsernameProcedure = "/gitslice.core.v1.AuthService/ChooseUsername"
)

// AuthServiceClient is a client for the gitslice.core.v1.AuthService service.
type AuthServiceClient interface {
	StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error)
	PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error)
	CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error)
	GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error)
	CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error)
	ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error)
}

// NewAuthServiceClient constructs a client for the gitslice.core.v1.AuthService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_proto_core_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		startCliLogin: connect.NewClient[v1.StartCliLoginRequest, v1.StartCliLoginResponse](
			httpClient,
			baseURL+AuthServiceStartCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("StartCliLogin")),
			connect.WithClientOptions(opts...),
		),
		pollCliLogin: connect.NewClient[v1.PollCliLoginRequest, v1.PollCliLoginResponse](
			httpClient,
			baseURL+AuthServicePollCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("PollCliLogin")),
			connect.WithClientOptions(opts...),
		),
		completeCliLogin: connect.NewClient[v1.CompleteCliLoginRequest, v1.CompleteCliLoginResponse](
			httpClient,
			baseURL+AuthServiceCompleteCliLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("CompleteCliLogin")),
			connect.WithClientOptions(opts...),
		),
		getAuthStatus: connect.NewClient[v1.GetAuthStatusRequest, v1.GetAuthStatusResponse](
			httpClient,
			baseURL+AuthServiceGetAuthStatusProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetAuthStatus")),
			connect.WithClientOptions(opts...),
		),
		checkUsernameAvailable: connect.NewClient[v1.CheckUsernameAvailableRequest, v1.CheckUsernameAvailableResponse](
			httpClient,
			baseURL+AuthServiceCheckUsernameAvailableProcedure,
			connect.WithSchema(authServiceMethods.ByName("CheckUsernameAvailable")),
			connect.WithClientOptions(opts...),
		),
		chooseUsername: connect.NewClient[v1.ChooseUsernameRequest, v1.ChooseUsernameResponse](
			httpClient,
			baseURL+AuthServiceChooseUsernameProcedure,
			connect.WithSchema(authServiceMethods.ByName("ChooseUsername")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	startCliLogin          *connect.Client[v1.StartCliLoginRequest, v1.StartCliLoginResponse]
	pollCliLogin           *connect.Client[v1.PollCliLoginRequest, v1.PollCliLoginResponse]
	completeCliLogin       *connect.Client[v1.CompleteCliLoginRequest, v1.CompleteCliLoginResponse]
	getAuthStatus          *connect.Client[v1.GetAuthStatusRequest, v1.GetAuthStatusResponse]
	checkUsernameAvailable *connect.Client[v1.CheckUsernameAvailableRequest, v1.CheckUsernameAvailableResponse]
	chooseUsername         *connect.Client[v1.ChooseUsernameRequest, v1.ChooseUsernameResponse]
}

// StartCliLogin calls gitslice.core.v1.AuthService.StartCliLogin.
func (c *authServiceClient) StartCliLogin(ctx context.Context, req *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error) {
	return c.startCliLogin.CallUnary(ctx, req)
}

// PollCliLogin calls gitslice.core.v1.AuthService.PollCliLogin.
func (c *authServiceClient) PollCliLogin(ctx context.Context, req *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error) {
	return c.pollCliLogin.CallUnary(ctx, req)
}

// CompleteCliLogin calls gitslice.core.v1.AuthService.CompleteCliLogin.
func (c *authServiceClient) CompleteCliLogin(ctx context.Context, req *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error) {
	return c.completeCliLogin.CallUnary(ctx, req)
}

// GetAuthStatus calls gitslice.core.v1.AuthService.GetAuthStatus.
func (c *authServiceClient) GetAuthStatus(ctx context.Context, req *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error) {
	return c.getAuthStatus.CallUnary(ctx, req)
}

// CheckUsernameAvailable calls gitslice.core.v1.AuthService.CheckUsernameAvailable.
func (c *authServiceClient) CheckUsernameAvailable(ctx context.Context, req *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error) {
	return c.checkUsernameAvailable.CallUnary(ctx, req)
}

// ChooseUsername calls gitslice.core.v1.AuthService.ChooseUsername.
func (c *authServiceClient) ChooseUsername(ctx context.Context, req *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error) {
	return c.chooseUsername.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the gitslice.core.v1.AuthService service.
type AuthServiceHandler interface {
	StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error)
	PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error)
	CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error)
	GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error)
	CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error)
	ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_proto_core_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceStartCliLoginHandler := connect.NewUnaryHandler(
		AuthServiceStartCliLoginProcedure,
		svc.StartCliLogin,
		connect.WithSchema(authServiceMethods.ByName("StartCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServicePollCliLoginHandler := connect.NewUnaryHandler(
		AuthServicePollCliLoginProcedure,
		svc.PollCliLogin,
		connect.WithSchema(authServiceMethods.ByName("PollCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCompleteCliLoginHandler := connect.NewUnaryHandler(
		AuthServiceCompleteCliLoginProcedure,
		svc.CompleteCliLogin,
		connect.WithSchema(authServiceMethods.ByName("CompleteCliLogin")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceGetAuthStatusHandler := connect.NewUnaryHandler(
		AuthServiceGetAuthStatusProcedure,
		svc.GetAuthStatus,
		connect.WithSchema(authServiceMethods.ByName("GetAuthStatus")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCheckUsernameAvailableHandler := connect.NewUnaryHandler(
		AuthServiceCheckUsernameAvailableProcedure,
		svc.CheckUsernameAvailable,
		connect.WithSchema(authServiceMethods.ByName("CheckUsernameAvailable")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceChooseUsernameHandler := connect.NewUnaryHandler(
		AuthServiceChooseUsernameProcedure,
		svc.ChooseUsername,
		connect.WithSchema(authServiceMethods.ByName("ChooseUsername")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceStartCliLoginProcedure:
			authServiceStartCliLoginHandler.ServeHTTP(w, r)
		case AuthServicePollCliLoginProcedure:
			authServicePollCliLoginHandler.ServeHTTP(w, r)
		case AuthServiceCompleteCliLoginProcedure:
			authServiceCompleteCliLoginHandler.ServeHTTP(w, r)
		case AuthServiceGetAuthStatusProcedure:
			authServiceGetAuthStatusHandler.ServeHTTP(w, r)
		case AuthServiceCheckUsernameAvailableProcedure:
			authServiceCheckUsernameAvailableHandler.ServeHTTP(w, r)
		case AuthServiceChooseUsernameProcedure:
			authServiceChooseUsernameHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) StartCliLogin(context.Context, *connect.Request[v1.StartCliLoginRequest]) (*connect.Response[v1.StartCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.StartCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) PollCliLogin(context.Context, *connect.Request[v1.PollCliLoginRequest]) (*connect.Response[v1.PollCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.PollCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) CompleteCliLogin(context.Context, *connect.Request[v1.CompleteCliLoginRequest]) (*connect.Response[v1.CompleteCliLoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CompleteCliLogin is not implemented"))
}

func (UnimplementedAuthServiceHandler) GetAuthStatus(context.Context, *connect.Request[v1.GetAuthStatusRequest]) (*connect.Response[v1.GetAuthStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.GetAuthStatus is not implemented"))
}

func (UnimplementedAuthServiceHandler) CheckUsernameAvailable(context.Context, *connect.Request[v1.CheckUsernameAvailableRequest]) (*connect.Response[v1.CheckUsernameAvailableResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.CheckUsernameAvailable is not implemented"))
}

func (UnimplementedAuthServiceHandler) ChooseUsername(context.Context, *connect.Request[v1.ChooseUsernameRequest]) (*connect.Response[v1.ChooseUsernameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.AuthService.ChooseUsername is not implemented"))
}
