// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/changeset.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitslice-io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ChangesetServiceName is the fully-qualified name of the ChangesetService service.
	ChangesetServiceName = "gitslice.core.v1.ChangesetService"
	// ChangesetStackServiceName is the fully-qualified name of the ChangesetStackService service.
	ChangesetStackServiceName = "gitslice.core.v1.ChangesetStackService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ChangesetServiceCreateChangesetProcedure is the fully-qualified name of the ChangesetService's
	// CreateChangeset RPC.
	ChangesetServiceCreateChangesetProcedure = "/gitslice.core.v1.ChangesetService/CreateChangeset"
	// ChangesetServiceGetChangesetProcedure is the fully-qualified name of the ChangesetService's
	// GetChangeset RPC.
	ChangesetServiceGetChangesetProcedure = "/gitslice.core.v1.ChangesetService/GetChangeset"
	// ChangesetServiceListChangesetsProcedure is the fully-qualified name of the ChangesetService's
	// ListChangesets RPC.
	ChangesetServiceListChangesetsProcedure = "/gitslice.core.v1.ChangesetService/ListChangesets"
	// ChangesetServiceDiffChangesetProcedure is the fully-qualified name of the ChangesetService's
	// DiffChangeset RPC.
	ChangesetServiceDiffChangesetProcedure = "/gitslice.core.v1.ChangesetService/DiffChangeset"
	// ChangesetServiceUpdateChangesetProcedure is the fully-qualified name of the ChangesetService's
	// UpdateChangeset RPC.
	ChangesetServiceUpdateChangesetProcedure = "/gitslice.core.v1.ChangesetService/UpdateChangeset"
	// ChangesetServiceApproveChangesetProcedure is the fully-qualified name of the ChangesetService's
	// ApproveChangeset RPC.
	ChangesetServiceApproveChangesetProcedure = "/gitslice.core.v1.ChangesetService/ApproveChangeset"
	// ChangesetServiceReportCheckResultProcedure is the fully-qualified name of the ChangesetService's
	// ReportCheckResult RPC.
	ChangesetServiceReportCheckResultProcedure = "/gitslice.core.v1.ChangesetService/ReportCheckResult"
	// ChangesetServiceSubmitChangesetProcedure is the fully-qualified name of the ChangesetService's
	// SubmitChangeset RPC.
	ChangesetServiceSubmitChangesetProcedure = "/gitslice.core.v1.ChangesetService/SubmitChangeset"
	// ChangesetServiceAbandonChangesetProcedure is the fully-qualified name of the ChangesetService's
	// AbandonChangeset RPC.
	ChangesetServiceAbandonChangesetProcedure = "/gitslice.core.v1.ChangesetService/AbandonChangeset"
	// ChangesetStackServiceCreateStackProcedure is the fully-qualified name of the
	// ChangesetStackService's CreateStack RPC.
	ChangesetStackServiceCreateStackProcedure = "/gitslice.core.v1.ChangesetStackService/CreateStack"
	// ChangesetStackServiceGetStackProcedure is the fully-qualified name of the ChangesetStackService's
	// GetStack RPC.
	ChangesetStackServiceGetStackProcedure = "/gitslice.core.v1.ChangesetStackService/GetStack"
	// ChangesetStackServiceListStacksProcedure is the fully-qualified name of the
	// ChangesetStackService's ListStacks RPC.
	ChangesetStackServiceListStacksProcedure = "/gitslice.core.v1.ChangesetStackService/ListStacks"
	// ChangesetStackServiceAddStackEntryProcedure is the fully-qualified name of the
	// ChangesetStackService's AddStackEntry RPC.
	ChangesetStackServiceAddStackEntryProcedure = "/gitslice.core.v1.ChangesetStackService/AddStackEntry"
	// ChangesetStackServiceMoveStackEntryProcedure is the fully-qualified name of the
	// ChangesetStackService's MoveStackEntry RPC.
	ChangesetStackServiceMoveStackEntryProcedure = "/gitslice.core.v1.ChangesetStackService/MoveStackEntry"
	// ChangesetStackServiceReparentStackEntryProcedure is the fully-qualified name of the
	// ChangesetStackService's ReparentStackEntry RPC.
	ChangesetStackServiceReparentStackEntryProcedure = "/gitslice.core.v1.ChangesetStackService/ReparentStackEntry"
	// ChangesetStackServiceDetachStackEntryProcedure is the fully-qualified name of the
	// ChangesetStackService's DetachStackEntry RPC.
	ChangesetStackServiceDetachStackEntryProcedure = "/gitslice.core.v1.ChangesetStackService/DetachStackEntry"
	// ChangesetStackServiceRestackProcedure is the fully-qualified name of the ChangesetStackService's
	// Restack RPC.
	ChangesetStackServiceRestackProcedure = "/gitslice.core.v1.ChangesetStackService/Restack"
	// ChangesetStackServiceSubmitStackProcedure is the fully-qualified name of the
	// ChangesetStackService's SubmitStack RPC.
	ChangesetStackServiceSubmitStackProcedure = "/gitslice.core.v1.ChangesetStackService/SubmitStack"
)

// ChangesetServiceClient is a client for the gitslice.core.v1.ChangesetService service.
type ChangesetServiceClient interface {
	CreateChangeset(context.Context, *connect.Request[v1.CreateChangesetRequest]) (*connect.Response[v1.Changeset], error)
	GetChangeset(context.Context, *connect.Request[v1.GetChangesetRequest]) (*connect.Response[v1.Changeset], error)
	ListChangesets(context.Context, *connect.Request[v1.ListChangesetsRequest]) (*connect.Response[v1.ListChangesetsResponse], error)
	DiffChangeset(context.Context, *connect.Request[v1.DiffChangesetRequest]) (*connect.Response[v1.DiffChangesetResponse], error)
	UpdateChangeset(context.Context, *connect.Request[v1.UpdateChangesetRequest]) (*connect.Response[v1.Patchset], error)
	ApproveChangeset(context.Context, *connect.Request[v1.ApproveChangesetRequest]) (*connect.Response[v1.ApproveChangesetResponse], error)
	ReportCheckResult(context.Context, *connect.Request[v1.ReportCheckResultRequest]) (*connect.Response[v1.ReportCheckResultResponse], error)
	SubmitChangeset(context.Context, *connect.Request[v1.SubmitChangesetRequest]) (*connect.Response[v1.SubmitChangesetResponse], error)
	AbandonChangeset(context.Context, *connect.Request[v1.AbandonChangesetRequest]) (*connect.Response[v1.Empty], error)
}

// NewChangesetServiceClient constructs a client for the gitslice.core.v1.ChangesetService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChangesetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChangesetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	changesetServiceMethods := v1.File_proto_core_v1_changeset_proto.Services().ByName("ChangesetService").Methods()
	return &changesetServiceClient{
		createChangeset: connect.NewClient[v1.CreateChangesetRequest, v1.Changeset](
			httpClient,
			baseURL+ChangesetServiceCreateChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("CreateChangeset")),
			connect.WithClientOptions(opts...),
		),
		getChangeset: connect.NewClient[v1.GetChangesetRequest, v1.Changeset](
			httpClient,
			baseURL+ChangesetServiceGetChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("GetChangeset")),
			connect.WithClientOptions(opts...),
		),
		listChangesets: connect.NewClient[v1.ListChangesetsRequest, v1.ListChangesetsResponse](
			httpClient,
			baseURL+ChangesetServiceListChangesetsProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("ListChangesets")),
			connect.WithClientOptions(opts...),
		),
		diffChangeset: connect.NewClient[v1.DiffChangesetRequest, v1.DiffChangesetResponse](
			httpClient,
			baseURL+ChangesetServiceDiffChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("DiffChangeset")),
			connect.WithClientOptions(opts...),
		),
		updateChangeset: connect.NewClient[v1.UpdateChangesetRequest, v1.Patchset](
			httpClient,
			baseURL+ChangesetServiceUpdateChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("UpdateChangeset")),
			connect.WithClientOptions(opts...),
		),
		approveChangeset: connect.NewClient[v1.ApproveChangesetRequest, v1.ApproveChangesetResponse](
			httpClient,
			baseURL+ChangesetServiceApproveChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("ApproveChangeset")),
			connect.WithClientOptions(opts...),
		),
		reportCheckResult: connect.NewClient[v1.ReportCheckResultRequest, v1.ReportCheckResultResponse](
			httpClient,
			baseURL+ChangesetServiceReportCheckResultProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("ReportCheckResult")),
			connect.WithClientOptions(opts...),
		),
		submitChangeset: connect.NewClient[v1.SubmitChangesetRequest, v1.SubmitChangesetResponse](
			httpClient,
			baseURL+ChangesetServiceSubmitChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("SubmitChangeset")),
			connect.WithClientOptions(opts...),
		),
		abandonChangeset: connect.NewClient[v1.AbandonChangesetRequest, v1.Empty](
			httpClient,
			baseURL+ChangesetServiceAbandonChangesetProcedure,
			connect.WithSchema(changesetServiceMethods.ByName("AbandonChangeset")),
			connect.WithClientOptions(opts...),
		),
	}
}

// changesetServiceClient implements ChangesetServiceClient.
type changesetServiceClient struct {
	createChangeset   *connect.Client[v1.CreateChangesetRequest, v1.Changeset]
	getChangeset      *connect.Client[v1.GetChangesetRequest, v1.Changeset]
	listChangesets    *connect.Client[v1.ListChangesetsRequest, v1.ListChangesetsResponse]
	diffChangeset     *connect.Client[v1.DiffChangesetRequest, v1.DiffChangesetResponse]
	updateChangeset   *connect.Client[v1.UpdateChangesetRequest, v1.Patchset]
	approveChangeset  *connect.Client[v1.ApproveChangesetRequest, v1.ApproveChangesetResponse]
	reportCheckResult *connect.Client[v1.ReportCheckResultRequest, v1.ReportCheckResultResponse]
	submitChangeset   *connect.Client[v1.SubmitChangesetRequest, v1.SubmitChangesetResponse]
	abandonChangeset  *connect.Client[v1.AbandonChangesetRequest, v1.Empty]
}

// CreateChangeset calls gitslice.core.v1.ChangesetService.CreateChangeset.
func (c *changesetServiceClient) CreateChangeset(ctx context.Context, req *connect.Request[v1.CreateChangesetRequest]) (*connect.Response[v1.Changeset], error) {
	return c.createChangeset.CallUnary(ctx, req)
}

// GetChangeset calls gitslice.core.v1.ChangesetService.GetChangeset.
func (c *changesetServiceClient) GetChangeset(ctx context.Context, req *connect.Request[v1.GetChangesetRequest]) (*connect.Response[v1.Changeset], error) {
	return c.getChangeset.CallUnary(ctx, req)
}

// ListChangesets calls gitslice.core.v1.ChangesetService.ListChangesets.
func (c *changesetServiceClient) ListChangesets(ctx context.Context, req *connect.Request[v1.ListChangesetsRequest]) (*connect.Response[v1.ListChangesetsResponse], error) {
	return c.listChangesets.CallUnary(ctx, req)
}

// DiffChangeset calls gitslice.core.v1.ChangesetService.DiffChangeset.
func (c *changesetServiceClient) DiffChangeset(ctx context.Context, req *connect.Request[v1.DiffChangesetRequest]) (*connect.Response[v1.DiffChangesetResponse], error) {
	return c.diffChangeset.CallUnary(ctx, req)
}

// UpdateChangeset calls gitslice.core.v1.ChangesetService.UpdateChangeset.
func (c *changesetServiceClient) UpdateChangeset(ctx context.Context, req *connect.Request[v1.UpdateChangesetRequest]) (*connect.Response[v1.Patchset], error) {
	return c.updateChangeset.CallUnary(ctx, req)
}

// ApproveChangeset calls gitslice.core.v1.ChangesetService.ApproveChangeset.
func (c *changesetServiceClient) ApproveChangeset(ctx context.Context, req *connect.Request[v1.ApproveChangesetRequest]) (*connect.Response[v1.ApproveChangesetResponse], error) {
	return c.approveChangeset.CallUnary(ctx, req)
}

// ReportCheckResult calls gitslice.core.v1.ChangesetService.ReportCheckResult.
func (c *changesetServiceClient) ReportCheckResult(ctx context.Context, req *connect.Request[v1.ReportCheckResultRequest]) (*connect.Response[v1.ReportCheckResultResponse], error) {
	return c.reportCheckResult.CallUnary(ctx, req)
}

// SubmitChangeset calls gitslice.core.v1.ChangesetService.SubmitChangeset.
func (c *changesetServiceClient) SubmitChangeset(ctx context.Context, req *connect.Request[v1.SubmitChangesetRequest]) (*connect.Response[v1.SubmitChangesetResponse], error) {
	return c.submitChangeset.CallUnary(ctx, req)
}

// AbandonChangeset calls gitslice.core.v1.ChangesetService.AbandonChangeset.
func (c *changesetServiceClient) AbandonChangeset(ctx context.Context, req *connect.Request[v1.AbandonChangesetRequest]) (*connect.Response[v1.Empty], error) {
	return c.abandonChangeset.CallUnary(ctx, req)
}

// ChangesetServiceHandler is an implementation of the gitslice.core.v1.ChangesetService service.
type ChangesetServiceHandler interface {
	CreateChangeset(context.Context, *connect.Request[v1.CreateChangesetRequest]) (*connect.Response[v1.Changeset], error)
	GetChangeset(context.Context, *connect.Request[v1.GetChangesetRequest]) (*connect.Response[v1.Changeset], error)
	ListChangesets(context.Context, *connect.Request[v1.ListChangesetsRequest]) (*connect.Response[v1.ListChangesetsResponse], error)
	DiffChangeset(context.Context, *connect.Request[v1.DiffChangesetRequest]) (*connect.Response[v1.DiffChangesetResponse], error)
	UpdateChangeset(context.Context, *connect.Request[v1.UpdateChangesetRequest]) (*connect.Response[v1.Patchset], error)
	ApproveChangeset(context.Context, *connect.Request[v1.ApproveChangesetRequest]) (*connect.Response[v1.ApproveChangesetResponse], error)
	ReportCheckResult(context.Context, *connect.Request[v1.ReportCheckResultRequest]) (*connect.Response[v1.ReportCheckResultResponse], error)
	SubmitChangeset(context.Context, *connect.Request[v1.SubmitChangesetRequest]) (*connect.Response[v1.SubmitChangesetResponse], error)
	AbandonChangeset(context.Context, *connect.Request[v1.AbandonChangesetRequest]) (*connect.Response[v1.Empty], error)
}

// NewChangesetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChangesetServiceHandler(svc ChangesetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	changesetServiceMethods := v1.File_proto_core_v1_changeset_proto.Services().ByName("ChangesetService").Methods()
	changesetServiceCreateChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceCreateChangesetProcedure,
		svc.CreateChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("CreateChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceGetChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceGetChangesetProcedure,
		svc.GetChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("GetChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceListChangesetsHandler := connect.NewUnaryHandler(
		ChangesetServiceListChangesetsProcedure,
		svc.ListChangesets,
		connect.WithSchema(changesetServiceMethods.ByName("ListChangesets")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceDiffChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceDiffChangesetProcedure,
		svc.DiffChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("DiffChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceUpdateChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceUpdateChangesetProcedure,
		svc.UpdateChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("UpdateChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceApproveChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceApproveChangesetProcedure,
		svc.ApproveChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("ApproveChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceReportCheckResultHandler := connect.NewUnaryHandler(
		ChangesetServiceReportCheckResultProcedure,
		svc.ReportCheckResult,
		connect.WithSchema(changesetServiceMethods.ByName("ReportCheckResult")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceSubmitChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceSubmitChangesetProcedure,
		svc.SubmitChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("SubmitChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	changesetServiceAbandonChangesetHandler := connect.NewUnaryHandler(
		ChangesetServiceAbandonChangesetProcedure,
		svc.AbandonChangeset,
		connect.WithSchema(changesetServiceMethods.ByName("AbandonChangeset")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.ChangesetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChangesetServiceCreateChangesetProcedure:
			changesetServiceCreateChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceGetChangesetProcedure:
			changesetServiceGetChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceListChangesetsProcedure:
			changesetServiceListChangesetsHandler.ServeHTTP(w, r)
		case ChangesetServiceDiffChangesetProcedure:
			changesetServiceDiffChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceUpdateChangesetProcedure:
			changesetServiceUpdateChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceApproveChangesetProcedure:
			changesetServiceApproveChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceReportCheckResultProcedure:
			changesetServiceReportCheckResultHandler.ServeHTTP(w, r)
		case ChangesetServiceSubmitChangesetProcedure:
			changesetServiceSubmitChangesetHandler.ServeHTTP(w, r)
		case ChangesetServiceAbandonChangesetProcedure:
			changesetServiceAbandonChangesetHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChangesetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChangesetServiceHandler struct{}

func (UnimplementedChangesetServiceHandler) CreateChangeset(context.Context, *connect.Request[v1.CreateChangesetRequest]) (*connect.Response[v1.Changeset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.CreateChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) GetChangeset(context.Context, *connect.Request[v1.GetChangesetRequest]) (*connect.Response[v1.Changeset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.GetChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) ListChangesets(context.Context, *connect.Request[v1.ListChangesetsRequest]) (*connect.Response[v1.ListChangesetsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.ListChangesets is not implemented"))
}

func (UnimplementedChangesetServiceHandler) DiffChangeset(context.Context, *connect.Request[v1.DiffChangesetRequest]) (*connect.Response[v1.DiffChangesetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.DiffChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) UpdateChangeset(context.Context, *connect.Request[v1.UpdateChangesetRequest]) (*connect.Response[v1.Patchset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.UpdateChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) ApproveChangeset(context.Context, *connect.Request[v1.ApproveChangesetRequest]) (*connect.Response[v1.ApproveChangesetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.ApproveChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) ReportCheckResult(context.Context, *connect.Request[v1.ReportCheckResultRequest]) (*connect.Response[v1.ReportCheckResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.ReportCheckResult is not implemented"))
}

func (UnimplementedChangesetServiceHandler) SubmitChangeset(context.Context, *connect.Request[v1.SubmitChangesetRequest]) (*connect.Response[v1.SubmitChangesetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.SubmitChangeset is not implemented"))
}

func (UnimplementedChangesetServiceHandler) AbandonChangeset(context.Context, *connect.Request[v1.AbandonChangesetRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetService.AbandonChangeset is not implemented"))
}

// ChangesetStackServiceClient is a client for the gitslice.core.v1.ChangesetStackService service.
type ChangesetStackServiceClient interface {
	CreateStack(context.Context, *connect.Request[v1.CreateStackRequest]) (*connect.Response[v1.ChangesetStack], error)
	GetStack(context.Context, *connect.Request[v1.GetStackRequest]) (*connect.Response[v1.ChangesetStack], error)
	ListStacks(context.Context, *connect.Request[v1.ListStacksRequest]) (*connect.Response[v1.ListStacksResponse], error)
	AddStackEntry(context.Context, *connect.Request[v1.AddStackEntryRequest]) (*connect.Response[v1.Changeset], error)
	MoveStackEntry(context.Context, *connect.Request[v1.MoveStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error)
	ReparentStackEntry(context.Context, *connect.Request[v1.ReparentStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error)
	DetachStackEntry(context.Context, *connect.Request[v1.DetachStackEntryRequest]) (*connect.Response[v1.DetachStackEntryResponse], error)
	Restack(context.Context, *connect.Request[v1.RestackRequest]) (*connect.Response[v1.RestackResponse], error)
	SubmitStack(context.Context, *connect.Request[v1.SubmitStackRequest]) (*connect.Response[v1.SubmitStackResponse], error)
}

// NewChangesetStackServiceClient constructs a client for the gitslice.core.v1.ChangesetStackService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewChangesetStackServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ChangesetStackServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	changesetStackServiceMethods := v1.File_proto_core_v1_changeset_proto.Services().ByName("ChangesetStackService").Methods()
	return &changesetStackServiceClient{
		createStack: connect.NewClient[v1.CreateStackRequest, v1.ChangesetStack](
			httpClient,
			baseURL+ChangesetStackServiceCreateStackProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("CreateStack")),
			connect.WithClientOptions(opts...),
		),
		getStack: connect.NewClient[v1.GetStackRequest, v1.ChangesetStack](
			httpClient,
			baseURL+ChangesetStackServiceGetStackProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("GetStack")),
			connect.WithClientOptions(opts...),
		),
		listStacks: connect.NewClient[v1.ListStacksRequest, v1.ListStacksResponse](
			httpClient,
			baseURL+ChangesetStackServiceListStacksProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("ListStacks")),
			connect.WithClientOptions(opts...),
		),
		addStackEntry: connect.NewClient[v1.AddStackEntryRequest, v1.Changeset](
			httpClient,
			baseURL+ChangesetStackServiceAddStackEntryProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("AddStackEntry")),
			connect.WithClientOptions(opts...),
		),
		moveStackEntry: connect.NewClient[v1.MoveStackEntryRequest, v1.ChangesetStack](
			httpClient,
			baseURL+ChangesetStackServiceMoveStackEntryProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("MoveStackEntry")),
			connect.WithClientOptions(opts...),
		),
		reparentStackEntry: connect.NewClient[v1.ReparentStackEntryRequest, v1.ChangesetStack](
			httpClient,
			baseURL+ChangesetStackServiceReparentStackEntryProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("ReparentStackEntry")),
			connect.WithClientOptions(opts...),
		),
		detachStackEntry: connect.NewClient[v1.DetachStackEntryRequest, v1.DetachStackEntryResponse](
			httpClient,
			baseURL+ChangesetStackServiceDetachStackEntryProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("DetachStackEntry")),
			connect.WithClientOptions(opts...),
		),
		restack: connect.NewClient[v1.RestackRequest, v1.RestackResponse](
			httpClient,
			baseURL+ChangesetStackServiceRestackProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("Restack")),
			connect.WithClientOptions(opts...),
		),
		submitStack: connect.NewClient[v1.SubmitStackRequest, v1.SubmitStackResponse](
			httpClient,
			baseURL+ChangesetStackServiceSubmitStackProcedure,
			connect.WithSchema(changesetStackServiceMethods.ByName("SubmitStack")),
			connect.WithClientOptions(opts...),
		),
	}
}

// changesetStackServiceClient implements ChangesetStackServiceClient.
type changesetStackServiceClient struct {
	createStack        *connect.Client[v1.CreateStackRequest, v1.ChangesetStack]
	getStack           *connect.Client[v1.GetStackRequest, v1.ChangesetStack]
	listStacks         *connect.Client[v1.ListStacksRequest, v1.ListStacksResponse]
	addStackEntry      *connect.Client[v1.AddStackEntryRequest, v1.Changeset]
	moveStackEntry     *connect.Client[v1.MoveStackEntryRequest, v1.ChangesetStack]
	reparentStackEntry *connect.Client[v1.ReparentStackEntryRequest, v1.ChangesetStack]
	detachStackEntry   *connect.Client[v1.DetachStackEntryRequest, v1.DetachStackEntryResponse]
	restack            *connect.Client[v1.RestackRequest, v1.RestackResponse]
	submitStack        *connect.Client[v1.SubmitStackRequest, v1.SubmitStackResponse]
}

// CreateStack calls gitslice.core.v1.ChangesetStackService.CreateStack.
func (c *changesetStackServiceClient) CreateStack(ctx context.Context, req *connect.Request[v1.CreateStackRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return c.createStack.CallUnary(ctx, req)
}

// GetStack calls gitslice.core.v1.ChangesetStackService.GetStack.
func (c *changesetStackServiceClient) GetStack(ctx context.Context, req *connect.Request[v1.GetStackRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return c.getStack.CallUnary(ctx, req)
}

// ListStacks calls gitslice.core.v1.ChangesetStackService.ListStacks.
func (c *changesetStackServiceClient) ListStacks(ctx context.Context, req *connect.Request[v1.ListStacksRequest]) (*connect.Response[v1.ListStacksResponse], error) {
	return c.listStacks.CallUnary(ctx, req)
}

// AddStackEntry calls gitslice.core.v1.ChangesetStackService.AddStackEntry.
func (c *changesetStackServiceClient) AddStackEntry(ctx context.Context, req *connect.Request[v1.AddStackEntryRequest]) (*connect.Response[v1.Changeset], error) {
	return c.addStackEntry.CallUnary(ctx, req)
}

// MoveStackEntry calls gitslice.core.v1.ChangesetStackService.MoveStackEntry.
func (c *changesetStackServiceClient) MoveStackEntry(ctx context.Context, req *connect.Request[v1.MoveStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return c.moveStackEntry.CallUnary(ctx, req)
}

// ReparentStackEntry calls gitslice.core.v1.ChangesetStackService.ReparentStackEntry.
func (c *changesetStackServiceClient) ReparentStackEntry(ctx context.Context, req *connect.Request[v1.ReparentStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return c.reparentStackEntry.CallUnary(ctx, req)
}

// DetachStackEntry calls gitslice.core.v1.ChangesetStackService.DetachStackEntry.
func (c *changesetStackServiceClient) DetachStackEntry(ctx context.Context, req *connect.Request[v1.DetachStackEntryRequest]) (*connect.Response[v1.DetachStackEntryResponse], error) {
	return c.detachStackEntry.CallUnary(ctx, req)
}

// Restack calls gitslice.core.v1.ChangesetStackService.Restack.
func (c *changesetStackServiceClient) Restack(ctx context.Context, req *connect.Request[v1.RestackRequest]) (*connect.Response[v1.RestackResponse], error) {
	return c.restack.CallUnary(ctx, req)
}

// SubmitStack calls gitslice.core.v1.ChangesetStackService.SubmitStack.
func (c *changesetStackServiceClient) SubmitStack(ctx context.Context, req *connect.Request[v1.SubmitStackRequest]) (*connect.Response[v1.SubmitStackResponse], error) {
	return c.submitStack.CallUnary(ctx, req)
}

// ChangesetStackServiceHandler is an implementation of the gitslice.core.v1.ChangesetStackService
// service.
type ChangesetStackServiceHandler interface {
	CreateStack(context.Context, *connect.Request[v1.CreateStackRequest]) (*connect.Response[v1.ChangesetStack], error)
	GetStack(context.Context, *connect.Request[v1.GetStackRequest]) (*connect.Response[v1.ChangesetStack], error)
	ListStacks(context.Context, *connect.Request[v1.ListStacksRequest]) (*connect.Response[v1.ListStacksResponse], error)
	AddStackEntry(context.Context, *connect.Request[v1.AddStackEntryRequest]) (*connect.Response[v1.Changeset], error)
	MoveStackEntry(context.Context, *connect.Request[v1.MoveStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error)
	ReparentStackEntry(context.Context, *connect.Request[v1.ReparentStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error)
	DetachStackEntry(context.Context, *connect.Request[v1.DetachStackEntryRequest]) (*connect.Response[v1.DetachStackEntryResponse], error)
	Restack(context.Context, *connect.Request[v1.RestackRequest]) (*connect.Response[v1.RestackResponse], error)
	SubmitStack(context.Context, *connect.Request[v1.SubmitStackRequest]) (*connect.Response[v1.SubmitStackResponse], error)
}

// NewChangesetStackServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewChangesetStackServiceHandler(svc ChangesetStackServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	changesetStackServiceMethods := v1.File_proto_core_v1_changeset_proto.Services().ByName("ChangesetStackService").Methods()
	changesetStackServiceCreateStackHandler := connect.NewUnaryHandler(
		ChangesetStackServiceCreateStackProcedure,
		svc.CreateStack,
		connect.WithSchema(changesetStackServiceMethods.ByName("CreateStack")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceGetStackHandler := connect.NewUnaryHandler(
		ChangesetStackServiceGetStackProcedure,
		svc.GetStack,
		connect.WithSchema(changesetStackServiceMethods.ByName("GetStack")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceListStacksHandler := connect.NewUnaryHandler(
		ChangesetStackServiceListStacksProcedure,
		svc.ListStacks,
		connect.WithSchema(changesetStackServiceMethods.ByName("ListStacks")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceAddStackEntryHandler := connect.NewUnaryHandler(
		ChangesetStackServiceAddStackEntryProcedure,
		svc.AddStackEntry,
		connect.WithSchema(changesetStackServiceMethods.ByName("AddStackEntry")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceMoveStackEntryHandler := connect.NewUnaryHandler(
		ChangesetStackServiceMoveStackEntryProcedure,
		svc.MoveStackEntry,
		connect.WithSchema(changesetStackServiceMethods.ByName("MoveStackEntry")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceReparentStackEntryHandler := connect.NewUnaryHandler(
		ChangesetStackServiceReparentStackEntryProcedure,
		svc.ReparentStackEntry,
		connect.WithSchema(changesetStackServiceMethods.ByName("ReparentStackEntry")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceDetachStackEntryHandler := connect.NewUnaryHandler(
		ChangesetStackServiceDetachStackEntryProcedure,
		svc.DetachStackEntry,
		connect.WithSchema(changesetStackServiceMethods.ByName("DetachStackEntry")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceRestackHandler := connect.NewUnaryHandler(
		ChangesetStackServiceRestackProcedure,
		svc.Restack,
		connect.WithSchema(changesetStackServiceMethods.ByName("Restack")),
		connect.WithHandlerOptions(opts...),
	)
	changesetStackServiceSubmitStackHandler := connect.NewUnaryHandler(
		ChangesetStackServiceSubmitStackProcedure,
		svc.SubmitStack,
		connect.WithSchema(changesetStackServiceMethods.ByName("SubmitStack")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.ChangesetStackService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ChangesetStackServiceCreateStackProcedure:
			changesetStackServiceCreateStackHandler.ServeHTTP(w, r)
		case ChangesetStackServiceGetStackProcedure:
			changesetStackServiceGetStackHandler.ServeHTTP(w, r)
		case ChangesetStackServiceListStacksProcedure:
			changesetStackServiceListStacksHandler.ServeHTTP(w, r)
		case ChangesetStackServiceAddStackEntryProcedure:
			changesetStackServiceAddStackEntryHandler.ServeHTTP(w, r)
		case ChangesetStackServiceMoveStackEntryProcedure:
			changesetStackServiceMoveStackEntryHandler.ServeHTTP(w, r)
		case ChangesetStackServiceReparentStackEntryProcedure:
			changesetStackServiceReparentStackEntryHandler.ServeHTTP(w, r)
		case ChangesetStackServiceDetachStackEntryProcedure:
			changesetStackServiceDetachStackEntryHandler.ServeHTTP(w, r)
		case ChangesetStackServiceRestackProcedure:
			changesetStackServiceRestackHandler.ServeHTTP(w, r)
		case ChangesetStackServiceSubmitStackProcedure:
			changesetStackServiceSubmitStackHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedChangesetStackServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedChangesetStackServiceHandler struct{}

func (UnimplementedChangesetStackServiceHandler) CreateStack(context.Context, *connect.Request[v1.CreateStackRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.CreateStack is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) GetStack(context.Context, *connect.Request[v1.GetStackRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.GetStack is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) ListStacks(context.Context, *connect.Request[v1.ListStacksRequest]) (*connect.Response[v1.ListStacksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.ListStacks is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) AddStackEntry(context.Context, *connect.Request[v1.AddStackEntryRequest]) (*connect.Response[v1.Changeset], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.AddStackEntry is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) MoveStackEntry(context.Context, *connect.Request[v1.MoveStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.MoveStackEntry is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) ReparentStackEntry(context.Context, *connect.Request[v1.ReparentStackEntryRequest]) (*connect.Response[v1.ChangesetStack], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.ReparentStackEntry is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) DetachStackEntry(context.Context, *connect.Request[v1.DetachStackEntryRequest]) (*connect.Response[v1.DetachStackEntryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.DetachStackEntry is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) Restack(context.Context, *connect.Request[v1.RestackRequest]) (*connect.Response[v1.RestackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.Restack is not implemented"))
}

func (UnimplementedChangesetStackServiceHandler) SubmitStack(context.Context, *connect.Request[v1.SubmitStackRequest]) (*connect.Response[v1.SubmitStackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.ChangesetStackService.SubmitStack is not implemented"))
}
