// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/repository.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitslice-io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RepositoryServiceName is the fully-qualified name of the RepositoryService service.
	RepositoryServiceName = "gitslice.core.v1.RepositoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RepositoryServiceResolvePathProcedure is the fully-qualified name of the RepositoryService's
	// ResolvePath RPC.
	RepositoryServiceResolvePathProcedure = "/gitslice.core.v1.RepositoryService/ResolvePath"
	// RepositoryServiceListDirectoryProcedure is the fully-qualified name of the RepositoryService's
	// ListDirectory RPC.
	RepositoryServiceListDirectoryProcedure = "/gitslice.core.v1.RepositoryService/ListDirectory"
	// RepositoryServiceReadFileProcedure is the fully-qualified name of the RepositoryService's
	// ReadFile RPC.
	RepositoryServiceReadFileProcedure = "/gitslice.core.v1.RepositoryService/ReadFile"
	// RepositoryServiceGetCommitProcedure is the fully-qualified name of the RepositoryService's
	// GetCommit RPC.
	RepositoryServiceGetCommitProcedure = "/gitslice.core.v1.RepositoryService/GetCommit"
	// RepositoryServiceResolveCommitProcedure is the fully-qualified name of the RepositoryService's
	// ResolveCommit RPC.
	RepositoryServiceResolveCommitProcedure = "/gitslice.core.v1.RepositoryService/ResolveCommit"
	// RepositoryServiceListCommitsProcedure is the fully-qualified name of the RepositoryService's
	// ListCommits RPC.
	RepositoryServiceListCommitsProcedure = "/gitslice.core.v1.RepositoryService/ListCommits"
	// RepositoryServiceGetRefProcedure is the fully-qualified name of the RepositoryService's GetRef
	// RPC.
	RepositoryServiceGetRefProcedure = "/gitslice.core.v1.RepositoryService/GetRef"
	// RepositoryServiceImportGitRepositoryProcedure is the fully-qualified name of the
	// RepositoryService's ImportGitRepository RPC.
	RepositoryServiceImportGitRepositoryProcedure = "/gitslice.core.v1.RepositoryService/ImportGitRepository"
	// RepositoryServiceImportGitRepositoryStreamProcedure is the fully-qualified name of the
	// RepositoryService's ImportGitRepositoryStream RPC.
	RepositoryServiceImportGitRepositoryStreamProcedure = "/gitslice.core.v1.RepositoryService/ImportGitRepositoryStream"
)

// RepositoryServiceClient is a client for the gitslice.core.v1.RepositoryService service.
type RepositoryServiceClient interface {
	ResolvePath(context.Context, *connect.Request[v1.ResolvePathRequest]) (*connect.Response[v1.ResolvePathResponse], error)
	ListDirectory(context.Context, *connect.Request[v1.ListDirectoryRequest]) (*connect.Response[v1.ListDirectoryResponse], error)
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error)
	GetCommit(context.Context, *connect.Request[v1.GetCommitRequest]) (*connect.Response[v1.Commit], error)
	ResolveCommit(context.Context, *connect.Request[v1.ResolveCommitRequest]) (*connect.Response[v1.ResolveCommitResponse], error)
	ListCommits(context.Context, *connect.Request[v1.ListCommitsRequest]) (*connect.Response[v1.ListCommitsResponse], error)
	GetRef(context.Context, *connect.Request[v1.GetRefRequest]) (*connect.Response[v1.Ref], error)
	ImportGitRepository(context.Context, *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.Response[v1.ImportGitRepositoryResponse], error)
	ImportGitRepositoryStream(context.Context, *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.ServerStreamForClient[v1.ImportGitRepositoryProgress], error)
}

// NewRepositoryServiceClient constructs a client for the gitslice.core.v1.RepositoryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRepositoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RepositoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	repositoryServiceMethods := v1.File_proto_core_v1_repository_proto.Services().ByName("RepositoryService").Methods()
	return &repositoryServiceClient{
		resolvePath: connect.NewClient[v1.ResolvePathRequest, v1.ResolvePathResponse](
			httpClient,
			baseURL+RepositoryServiceResolvePathProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ResolvePath")),
			connect.WithClientOptions(opts...),
		),
		listDirectory: connect.NewClient[v1.ListDirectoryRequest, v1.ListDirectoryResponse](
			httpClient,
			baseURL+RepositoryServiceListDirectoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ListDirectory")),
			connect.WithClientOptions(opts...),
		),
		readFile: connect.NewClient[v1.ReadFileRequest, v1.ReadFileResponse](
			httpClient,
			baseURL+RepositoryServiceReadFileProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ReadFile")),
			connect.WithClientOptions(opts...),
		),
		getCommit: connect.NewClient[v1.GetCommitRequest, v1.Commit](
			httpClient,
			baseURL+RepositoryServiceGetCommitProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("GetCommit")),
			connect.WithClientOptions(opts...),
		),
		resolveCommit: connect.NewClient[v1.ResolveCommitRequest, v1.ResolveCommitResponse](
			httpClient,
			baseURL+RepositoryServiceResolveCommitProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ResolveCommit")),
			connect.WithClientOptions(opts...),
		),
		listCommits: connect.NewClient[v1.ListCommitsRequest, v1.ListCommitsResponse](
			httpClient,
			baseURL+RepositoryServiceListCommitsProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ListCommits")),
			connect.WithClientOptions(opts...),
		),
		getRef: connect.NewClient[v1.GetRefRequest, v1.Ref](
			httpClient,
			baseURL+RepositoryServiceGetRefProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("GetRef")),
			connect.WithClientOptions(opts...),
		),
		importGitRepository: connect.NewClient[v1.ImportGitRepositoryRequest, v1.ImportGitRepositoryResponse](
			httpClient,
			baseURL+RepositoryServiceImportGitRepositoryProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ImportGitRepository")),
			connect.WithClientOptions(opts...),
		),
		importGitRepositoryStream: connect.NewClient[v1.ImportGitRepositoryRequest, v1.ImportGitRepositoryProgress](
			httpClient,
			baseURL+RepositoryServiceImportGitRepositoryStreamProcedure,
			connect.WithSchema(repositoryServiceMethods.ByName("ImportGitRepositoryStream")),
			connect.WithClientOptions(opts...),
		),
	}
}

// repositoryServiceClient implements RepositoryServiceClient.
type repositoryServiceClient struct {
	resolvePath               *connect.Client[v1.ResolvePathRequest, v1.ResolvePathResponse]
	listDirectory             *connect.Client[v1.ListDirectoryRequest, v1.ListDirectoryResponse]
	readFile                  *connect.Client[v1.ReadFileRequest, v1.ReadFileResponse]
	getCommit                 *connect.Client[v1.GetCommitRequest, v1.Commit]
	resolveCommit             *connect.Client[v1.ResolveCommitRequest, v1.ResolveCommitResponse]
	listCommits               *connect.Client[v1.ListCommitsRequest, v1.ListCommitsResponse]
	getRef                    *connect.Client[v1.GetRefRequest, v1.Ref]
	importGitRepository       *connect.Client[v1.ImportGitRepositoryRequest, v1.ImportGitRepositoryResponse]
	importGitRepositoryStream *connect.Client[v1.ImportGitRepositoryRequest, v1.ImportGitRepositoryProgress]
}

// ResolvePath calls gitslice.core.v1.RepositoryService.ResolvePath.
func (c *repositoryServiceClient) ResolvePath(ctx context.Context, req *connect.Request[v1.ResolvePathRequest]) (*connect.Response[v1.ResolvePathResponse], error) {
	return c.resolvePath.CallUnary(ctx, req)
}

// ListDirectory calls gitslice.core.v1.RepositoryService.ListDirectory.
func (c *repositoryServiceClient) ListDirectory(ctx context.Context, req *connect.Request[v1.ListDirectoryRequest]) (*connect.Response[v1.ListDirectoryResponse], error) {
	return c.listDirectory.CallUnary(ctx, req)
}

// ReadFile calls gitslice.core.v1.RepositoryService.ReadFile.
func (c *repositoryServiceClient) ReadFile(ctx context.Context, req *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error) {
	return c.readFile.CallUnary(ctx, req)
}

// GetCommit calls gitslice.core.v1.RepositoryService.GetCommit.
func (c *repositoryServiceClient) GetCommit(ctx context.Context, req *connect.Request[v1.GetCommitRequest]) (*connect.Response[v1.Commit], error) {
	return c.getCommit.CallUnary(ctx, req)
}

// ResolveCommit calls gitslice.core.v1.RepositoryService.ResolveCommit.
func (c *repositoryServiceClient) ResolveCommit(ctx context.Context, req *connect.Request[v1.ResolveCommitRequest]) (*connect.Response[v1.ResolveCommitResponse], error) {
	return c.resolveCommit.CallUnary(ctx, req)
}

// ListCommits calls gitslice.core.v1.RepositoryService.ListCommits.
func (c *repositoryServiceClient) ListCommits(ctx context.Context, req *connect.Request[v1.ListCommitsRequest]) (*connect.Response[v1.ListCommitsResponse], error) {
	return c.listCommits.CallUnary(ctx, req)
}

// GetRef calls gitslice.core.v1.RepositoryService.GetRef.
func (c *repositoryServiceClient) GetRef(ctx context.Context, req *connect.Request[v1.GetRefRequest]) (*connect.Response[v1.Ref], error) {
	return c.getRef.CallUnary(ctx, req)
}

// ImportGitRepository calls gitslice.core.v1.RepositoryService.ImportGitRepository.
func (c *repositoryServiceClient) ImportGitRepository(ctx context.Context, req *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.Response[v1.ImportGitRepositoryResponse], error) {
	return c.importGitRepository.CallUnary(ctx, req)
}

// ImportGitRepositoryStream calls gitslice.core.v1.RepositoryService.ImportGitRepositoryStream.
func (c *repositoryServiceClient) ImportGitRepositoryStream(ctx context.Context, req *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.ServerStreamForClient[v1.ImportGitRepositoryProgress], error) {
	return c.importGitRepositoryStream.CallServerStream(ctx, req)
}

// RepositoryServiceHandler is an implementation of the gitslice.core.v1.RepositoryService service.
type RepositoryServiceHandler interface {
	ResolvePath(context.Context, *connect.Request[v1.ResolvePathRequest]) (*connect.Response[v1.ResolvePathResponse], error)
	ListDirectory(context.Context, *connect.Request[v1.ListDirectoryRequest]) (*connect.Response[v1.ListDirectoryResponse], error)
	ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error)
	GetCommit(context.Context, *connect.Request[v1.GetCommitRequest]) (*connect.Response[v1.Commit], error)
	ResolveCommit(context.Context, *connect.Request[v1.ResolveCommitRequest]) (*connect.Response[v1.ResolveCommitResponse], error)
	ListCommits(context.Context, *connect.Request[v1.ListCommitsRequest]) (*connect.Response[v1.ListCommitsResponse], error)
	GetRef(context.Context, *connect.Request[v1.GetRefRequest]) (*connect.Response[v1.Ref], error)
	ImportGitRepository(context.Context, *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.Response[v1.ImportGitRepositoryResponse], error)
	ImportGitRepositoryStream(context.Context, *connect.Request[v1.ImportGitRepositoryRequest], *connect.ServerStream[v1.ImportGitRepositoryProgress]) error
}

// NewRepositoryServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRepositoryServiceHandler(svc RepositoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	repositoryServiceMethods := v1.File_proto_core_v1_repository_proto.Services().ByName("RepositoryService").Methods()
	repositoryServiceResolvePathHandler := connect.NewUnaryHandler(
		RepositoryServiceResolvePathProcedure,
		svc.ResolvePath,
		connect.WithSchema(repositoryServiceMethods.ByName("ResolvePath")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceListDirectoryHandler := connect.NewUnaryHandler(
		RepositoryServiceListDirectoryProcedure,
		svc.ListDirectory,
		connect.WithSchema(repositoryServiceMethods.ByName("ListDirectory")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceReadFileHandler := connect.NewUnaryHandler(
		RepositoryServiceReadFileProcedure,
		svc.ReadFile,
		connect.WithSchema(repositoryServiceMethods.ByName("ReadFile")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceGetCommitHandler := connect.NewUnaryHandler(
		RepositoryServiceGetCommitProcedure,
		svc.GetCommit,
		connect.WithSchema(repositoryServiceMethods.ByName("GetCommit")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceResolveCommitHandler := connect.NewUnaryHandler(
		RepositoryServiceResolveCommitProcedure,
		svc.ResolveCommit,
		connect.WithSchema(repositoryServiceMethods.ByName("ResolveCommit")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceListCommitsHandler := connect.NewUnaryHandler(
		RepositoryServiceListCommitsProcedure,
		svc.ListCommits,
		connect.WithSchema(repositoryServiceMethods.ByName("ListCommits")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceGetRefHandler := connect.NewUnaryHandler(
		RepositoryServiceGetRefProcedure,
		svc.GetRef,
		connect.WithSchema(repositoryServiceMethods.ByName("GetRef")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceImportGitRepositoryHandler := connect.NewUnaryHandler(
		RepositoryServiceImportGitRepositoryProcedure,
		svc.ImportGitRepository,
		connect.WithSchema(repositoryServiceMethods.ByName("ImportGitRepository")),
		connect.WithHandlerOptions(opts...),
	)
	repositoryServiceImportGitRepositoryStreamHandler := connect.NewServerStreamHandler(
		RepositoryServiceImportGitRepositoryStreamProcedure,
		svc.ImportGitRepositoryStream,
		connect.WithSchema(repositoryServiceMethods.ByName("ImportGitRepositoryStream")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.RepositoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RepositoryServiceResolvePathProcedure:
			repositoryServiceResolvePathHandler.ServeHTTP(w, r)
		case RepositoryServiceListDirectoryProcedure:
			repositoryServiceListDirectoryHandler.ServeHTTP(w, r)
		case RepositoryServiceReadFileProcedure:
			repositoryServiceReadFileHandler.ServeHTTP(w, r)
		case RepositoryServiceGetCommitProcedure:
			repositoryServiceGetCommitHandler.ServeHTTP(w, r)
		case RepositoryServiceResolveCommitProcedure:
			repositoryServiceResolveCommitHandler.ServeHTTP(w, r)
		case RepositoryServiceListCommitsProcedure:
			repositoryServiceListCommitsHandler.ServeHTTP(w, r)
		case RepositoryServiceGetRefProcedure:
			repositoryServiceGetRefHandler.ServeHTTP(w, r)
		case RepositoryServiceImportGitRepositoryProcedure:
			repositoryServiceImportGitRepositoryHandler.ServeHTTP(w, r)
		case RepositoryServiceImportGitRepositoryStreamProcedure:
			repositoryServiceImportGitRepositoryStreamHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRepositoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRepositoryServiceHandler struct{}

func (UnimplementedRepositoryServiceHandler) ResolvePath(context.Context, *connect.Request[v1.ResolvePathRequest]) (*connect.Response[v1.ResolvePathResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ResolvePath is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ListDirectory(context.Context, *connect.Request[v1.ListDirectoryRequest]) (*connect.Response[v1.ListDirectoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ListDirectory is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ReadFile(context.Context, *connect.Request[v1.ReadFileRequest]) (*connect.Response[v1.ReadFileResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ReadFile is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) GetCommit(context.Context, *connect.Request[v1.GetCommitRequest]) (*connect.Response[v1.Commit], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.GetCommit is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ResolveCommit(context.Context, *connect.Request[v1.ResolveCommitRequest]) (*connect.Response[v1.ResolveCommitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ResolveCommit is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ListCommits(context.Context, *connect.Request[v1.ListCommitsRequest]) (*connect.Response[v1.ListCommitsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ListCommits is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) GetRef(context.Context, *connect.Request[v1.GetRefRequest]) (*connect.Response[v1.Ref], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.GetRef is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ImportGitRepository(context.Context, *connect.Request[v1.ImportGitRepositoryRequest]) (*connect.Response[v1.ImportGitRepositoryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ImportGitRepository is not implemented"))
}

func (UnimplementedRepositoryServiceHandler) ImportGitRepositoryStream(context.Context, *connect.Request[v1.ImportGitRepositoryRequest], *connect.ServerStream[v1.ImportGitRepositoryProgress]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.RepositoryService.ImportGitRepositoryStream is not implemented"))
}
