// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/slice.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/gitslice-io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SliceServiceName is the fully-qualified name of the SliceService service.
	SliceServiceName = "gitslice.core.v1.SliceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SliceServiceCreateSliceProcedure is the fully-qualified name of the SliceService's CreateSlice
	// RPC.
	SliceServiceCreateSliceProcedure = "/gitslice.core.v1.SliceService/CreateSlice"
	// SliceServiceResolveSliceProcedure is the fully-qualified name of the SliceService's ResolveSlice
	// RPC.
	SliceServiceResolveSliceProcedure = "/gitslice.core.v1.SliceService/ResolveSlice"
	// SliceServiceGetSliceProcedure is the fully-qualified name of the SliceService's GetSlice RPC.
	SliceServiceGetSliceProcedure = "/gitslice.core.v1.SliceService/GetSlice"
	// SliceServiceListSlicesProcedure is the fully-qualified name of the SliceService's ListSlices RPC.
	SliceServiceListSlicesProcedure = "/gitslice.core.v1.SliceService/ListSlices"
	// SliceServiceListSliceDefinitionVersionsProcedure is the fully-qualified name of the
	// SliceService's ListSliceDefinitionVersions RPC.
	SliceServiceListSliceDefinitionVersionsProcedure = "/gitslice.core.v1.SliceService/ListSliceDefinitionVersions"
	// SliceServiceUpdateSliceDefinitionProcedure is the fully-qualified name of the SliceService's
	// UpdateSliceDefinition RPC.
	SliceServiceUpdateSliceDefinitionProcedure = "/gitslice.core.v1.SliceService/UpdateSliceDefinition"
	// SliceServiceSetSliceCIDaemonProcedure is the fully-qualified name of the SliceService's
	// SetSliceCIDaemon RPC.
	SliceServiceSetSliceCIDaemonProcedure = "/gitslice.core.v1.SliceService/SetSliceCIDaemon"
	// SliceServiceSetSliceSecretProcedure is the fully-qualified name of the SliceService's
	// SetSliceSecret RPC.
	SliceServiceSetSliceSecretProcedure = "/gitslice.core.v1.SliceService/SetSliceSecret"
	// SliceServiceDeleteSliceSecretProcedure is the fully-qualified name of the SliceService's
	// DeleteSliceSecret RPC.
	SliceServiceDeleteSliceSecretProcedure = "/gitslice.core.v1.SliceService/DeleteSliceSecret"
	// SliceServiceListSliceSecretsProcedure is the fully-qualified name of the SliceService's
	// ListSliceSecrets RPC.
	SliceServiceListSliceSecretsProcedure = "/gitslice.core.v1.SliceService/ListSliceSecrets"
	// SliceServiceDeleteSliceProcedure is the fully-qualified name of the SliceService's DeleteSlice
	// RPC.
	SliceServiceDeleteSliceProcedure = "/gitslice.core.v1.SliceService/DeleteSlice"
)

// SliceServiceClient is a client for the gitslice.core.v1.SliceService service.
type SliceServiceClient interface {
	CreateSlice(context.Context, *connect.Request[v1.CreateSliceRequest]) (*connect.Response[v1.Slice], error)
	ResolveSlice(context.Context, *connect.Request[v1.ResolveSliceRequest]) (*connect.Response[v1.Slice], error)
	GetSlice(context.Context, *connect.Request[v1.GetSliceRequest]) (*connect.Response[v1.Slice], error)
	ListSlices(context.Context, *connect.Request[v1.ListSlicesRequest]) (*connect.Response[v1.ListSlicesResponse], error)
	ListSliceDefinitionVersions(context.Context, *connect.Request[v1.ListSliceDefinitionVersionsRequest]) (*connect.Response[v1.ListSliceDefinitionVersionsResponse], error)
	UpdateSliceDefinition(context.Context, *connect.Request[v1.UpdateSliceDefinitionRequest]) (*connect.Response[v1.SliceDefinition], error)
	SetSliceCIDaemon(context.Context, *connect.Request[v1.SetSliceCIDaemonRequest]) (*connect.Response[v1.Slice], error)
	SetSliceSecret(context.Context, *connect.Request[v1.SetSliceSecretRequest]) (*connect.Response[v1.Empty], error)
	DeleteSliceSecret(context.Context, *connect.Request[v1.DeleteSliceSecretRequest]) (*connect.Response[v1.Empty], error)
	ListSliceSecrets(context.Context, *connect.Request[v1.ListSliceSecretsRequest]) (*connect.Response[v1.ListSliceSecretsResponse], error)
	DeleteSlice(context.Context, *connect.Request[v1.DeleteSliceRequest]) (*connect.Response[v1.DeleteSliceResponse], error)
}

// NewSliceServiceClient constructs a client for the gitslice.core.v1.SliceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSliceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SliceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	sliceServiceMethods := v1.File_proto_core_v1_slice_proto.Services().ByName("SliceService").Methods()
	return &sliceServiceClient{
		createSlice: connect.NewClient[v1.CreateSliceRequest, v1.Slice](
			httpClient,
			baseURL+SliceServiceCreateSliceProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("CreateSlice")),
			connect.WithClientOptions(opts...),
		),
		resolveSlice: connect.NewClient[v1.ResolveSliceRequest, v1.Slice](
			httpClient,
			baseURL+SliceServiceResolveSliceProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("ResolveSlice")),
			connect.WithClientOptions(opts...),
		),
		getSlice: connect.NewClient[v1.GetSliceRequest, v1.Slice](
			httpClient,
			baseURL+SliceServiceGetSliceProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("GetSlice")),
			connect.WithClientOptions(opts...),
		),
		listSlices: connect.NewClient[v1.ListSlicesRequest, v1.ListSlicesResponse](
			httpClient,
			baseURL+SliceServiceListSlicesProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("ListSlices")),
			connect.WithClientOptions(opts...),
		),
		listSliceDefinitionVersions: connect.NewClient[v1.ListSliceDefinitionVersionsRequest, v1.ListSliceDefinitionVersionsResponse](
			httpClient,
			baseURL+SliceServiceListSliceDefinitionVersionsProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("ListSliceDefinitionVersions")),
			connect.WithClientOptions(opts...),
		),
		updateSliceDefinition: connect.NewClient[v1.UpdateSliceDefinitionRequest, v1.SliceDefinition](
			httpClient,
			baseURL+SliceServiceUpdateSliceDefinitionProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("UpdateSliceDefinition")),
			connect.WithClientOptions(opts...),
		),
		setSliceCIDaemon: connect.NewClient[v1.SetSliceCIDaemonRequest, v1.Slice](
			httpClient,
			baseURL+SliceServiceSetSliceCIDaemonProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("SetSliceCIDaemon")),
			connect.WithClientOptions(opts...),
		),
		setSliceSecret: connect.NewClient[v1.SetSliceSecretRequest, v1.Empty](
			httpClient,
			baseURL+SliceServiceSetSliceSecretProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("SetSliceSecret")),
			connect.WithClientOptions(opts...),
		),
		deleteSliceSecret: connect.NewClient[v1.DeleteSliceSecretRequest, v1.Empty](
			httpClient,
			baseURL+SliceServiceDeleteSliceSecretProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("DeleteSliceSecret")),
			connect.WithClientOptions(opts...),
		),
		listSliceSecrets: connect.NewClient[v1.ListSliceSecretsRequest, v1.ListSliceSecretsResponse](
			httpClient,
			baseURL+SliceServiceListSliceSecretsProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("ListSliceSecrets")),
			connect.WithClientOptions(opts...),
		),
		deleteSlice: connect.NewClient[v1.DeleteSliceRequest, v1.DeleteSliceResponse](
			httpClient,
			baseURL+SliceServiceDeleteSliceProcedure,
			connect.WithSchema(sliceServiceMethods.ByName("DeleteSlice")),
			connect.WithClientOptions(opts...),
		),
	}
}

// sliceServiceClient implements SliceServiceClient.
type sliceServiceClient struct {
	createSlice                 *connect.Client[v1.CreateSliceRequest, v1.Slice]
	resolveSlice                *connect.Client[v1.ResolveSliceRequest, v1.Slice]
	getSlice                    *connect.Client[v1.GetSliceRequest, v1.Slice]
	listSlices                  *connect.Client[v1.ListSlicesRequest, v1.ListSlicesResponse]
	listSliceDefinitionVersions *connect.Client[v1.ListSliceDefinitionVersionsRequest, v1.ListSliceDefinitionVersionsResponse]
	updateSliceDefinition       *connect.Client[v1.UpdateSliceDefinitionRequest, v1.SliceDefinition]
	setSliceCIDaemon            *connect.Client[v1.SetSliceCIDaemonRequest, v1.Slice]
	setSliceSecret              *connect.Client[v1.SetSliceSecretRequest, v1.Empty]
	deleteSliceSecret           *connect.Client[v1.DeleteSliceSecretRequest, v1.Empty]
	listSliceSecrets            *connect.Client[v1.ListSliceSecretsRequest, v1.ListSliceSecretsResponse]
	deleteSlice                 *connect.Client[v1.DeleteSliceRequest, v1.DeleteSliceResponse]
}

// CreateSlice calls gitslice.core.v1.SliceService.CreateSlice.
func (c *sliceServiceClient) CreateSlice(ctx context.Context, req *connect.Request[v1.CreateSliceRequest]) (*connect.Response[v1.Slice], error) {
	return c.createSlice.CallUnary(ctx, req)
}

// ResolveSlice calls gitslice.core.v1.SliceService.ResolveSlice.
func (c *sliceServiceClient) ResolveSlice(ctx context.Context, req *connect.Request[v1.ResolveSliceRequest]) (*connect.Response[v1.Slice], error) {
	return c.resolveSlice.CallUnary(ctx, req)
}

// GetSlice calls gitslice.core.v1.SliceService.GetSlice.
func (c *sliceServiceClient) GetSlice(ctx context.Context, req *connect.Request[v1.GetSliceRequest]) (*connect.Response[v1.Slice], error) {
	return c.getSlice.CallUnary(ctx, req)
}

// ListSlices calls gitslice.core.v1.SliceService.ListSlices.
func (c *sliceServiceClient) ListSlices(ctx context.Context, req *connect.Request[v1.ListSlicesRequest]) (*connect.Response[v1.ListSlicesResponse], error) {
	return c.listSlices.CallUnary(ctx, req)
}

// ListSliceDefinitionVersions calls gitslice.core.v1.SliceService.ListSliceDefinitionVersions.
func (c *sliceServiceClient) ListSliceDefinitionVersions(ctx context.Context, req *connect.Request[v1.ListSliceDefinitionVersionsRequest]) (*connect.Response[v1.ListSliceDefinitionVersionsResponse], error) {
	return c.listSliceDefinitionVersions.CallUnary(ctx, req)
}

// UpdateSliceDefinition calls gitslice.core.v1.SliceService.UpdateSliceDefinition.
func (c *sliceServiceClient) UpdateSliceDefinition(ctx context.Context, req *connect.Request[v1.UpdateSliceDefinitionRequest]) (*connect.Response[v1.SliceDefinition], error) {
	return c.updateSliceDefinition.CallUnary(ctx, req)
}

// SetSliceCIDaemon calls gitslice.core.v1.SliceService.SetSliceCIDaemon.
func (c *sliceServiceClient) SetSliceCIDaemon(ctx context.Context, req *connect.Request[v1.SetSliceCIDaemonRequest]) (*connect.Response[v1.Slice], error) {
	return c.setSliceCIDaemon.CallUnary(ctx, req)
}

// SetSliceSecret calls gitslice.core.v1.SliceService.SetSliceSecret.
func (c *sliceServiceClient) SetSliceSecret(ctx context.Context, req *connect.Request[v1.SetSliceSecretRequest]) (*connect.Response[v1.Empty], error) {
	return c.setSliceSecret.CallUnary(ctx, req)
}

// DeleteSliceSecret calls gitslice.core.v1.SliceService.DeleteSliceSecret.
func (c *sliceServiceClient) DeleteSliceSecret(ctx context.Context, req *connect.Request[v1.DeleteSliceSecretRequest]) (*connect.Response[v1.Empty], error) {
	return c.deleteSliceSecret.CallUnary(ctx, req)
}

// ListSliceSecrets calls gitslice.core.v1.SliceService.ListSliceSecrets.
func (c *sliceServiceClient) ListSliceSecrets(ctx context.Context, req *connect.Request[v1.ListSliceSecretsRequest]) (*connect.Response[v1.ListSliceSecretsResponse], error) {
	return c.listSliceSecrets.CallUnary(ctx, req)
}

// DeleteSlice calls gitslice.core.v1.SliceService.DeleteSlice.
func (c *sliceServiceClient) DeleteSlice(ctx context.Context, req *connect.Request[v1.DeleteSliceRequest]) (*connect.Response[v1.DeleteSliceResponse], error) {
	return c.deleteSlice.CallUnary(ctx, req)
}

// SliceServiceHandler is an implementation of the gitslice.core.v1.SliceService service.
type SliceServiceHandler interface {
	CreateSlice(context.Context, *connect.Request[v1.CreateSliceRequest]) (*connect.Response[v1.Slice], error)
	ResolveSlice(context.Context, *connect.Request[v1.ResolveSliceRequest]) (*connect.Response[v1.Slice], error)
	GetSlice(context.Context, *connect.Request[v1.GetSliceRequest]) (*connect.Response[v1.Slice], error)
	ListSlices(context.Context, *connect.Request[v1.ListSlicesRequest]) (*connect.Response[v1.ListSlicesResponse], error)
	ListSliceDefinitionVersions(context.Context, *connect.Request[v1.ListSliceDefinitionVersionsRequest]) (*connect.Response[v1.ListSliceDefinitionVersionsResponse], error)
	UpdateSliceDefinition(context.Context, *connect.Request[v1.UpdateSliceDefinitionRequest]) (*connect.Response[v1.SliceDefinition], error)
	SetSliceCIDaemon(context.Context, *connect.Request[v1.SetSliceCIDaemonRequest]) (*connect.Response[v1.Slice], error)
	SetSliceSecret(context.Context, *connect.Request[v1.SetSliceSecretRequest]) (*connect.Response[v1.Empty], error)
	DeleteSliceSecret(context.Context, *connect.Request[v1.DeleteSliceSecretRequest]) (*connect.Response[v1.Empty], error)
	ListSliceSecrets(context.Context, *connect.Request[v1.ListSliceSecretsRequest]) (*connect.Response[v1.ListSliceSecretsResponse], error)
	DeleteSlice(context.Context, *connect.Request[v1.DeleteSliceRequest]) (*connect.Response[v1.DeleteSliceResponse], error)
}

// NewSliceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSliceServiceHandler(svc SliceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	sliceServiceMethods := v1.File_proto_core_v1_slice_proto.Services().ByName("SliceService").Methods()
	sliceServiceCreateSliceHandler := connect.NewUnaryHandler(
		SliceServiceCreateSliceProcedure,
		svc.CreateSlice,
		connect.WithSchema(sliceServiceMethods.ByName("CreateSlice")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceResolveSliceHandler := connect.NewUnaryHandler(
		SliceServiceResolveSliceProcedure,
		svc.ResolveSlice,
		connect.WithSchema(sliceServiceMethods.ByName("ResolveSlice")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceGetSliceHandler := connect.NewUnaryHandler(
		SliceServiceGetSliceProcedure,
		svc.GetSlice,
		connect.WithSchema(sliceServiceMethods.ByName("GetSlice")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceListSlicesHandler := connect.NewUnaryHandler(
		SliceServiceListSlicesProcedure,
		svc.ListSlices,
		connect.WithSchema(sliceServiceMethods.ByName("ListSlices")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceListSliceDefinitionVersionsHandler := connect.NewUnaryHandler(
		SliceServiceListSliceDefinitionVersionsProcedure,
		svc.ListSliceDefinitionVersions,
		connect.WithSchema(sliceServiceMethods.ByName("ListSliceDefinitionVersions")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceUpdateSliceDefinitionHandler := connect.NewUnaryHandler(
		SliceServiceUpdateSliceDefinitionProcedure,
		svc.UpdateSliceDefinition,
		connect.WithSchema(sliceServiceMethods.ByName("UpdateSliceDefinition")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceSetSliceCIDaemonHandler := connect.NewUnaryHandler(
		SliceServiceSetSliceCIDaemonProcedure,
		svc.SetSliceCIDaemon,
		connect.WithSchema(sliceServiceMethods.ByName("SetSliceCIDaemon")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceSetSliceSecretHandler := connect.NewUnaryHandler(
		SliceServiceSetSliceSecretProcedure,
		svc.SetSliceSecret,
		connect.WithSchema(sliceServiceMethods.ByName("SetSliceSecret")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceDeleteSliceSecretHandler := connect.NewUnaryHandler(
		SliceServiceDeleteSliceSecretProcedure,
		svc.DeleteSliceSecret,
		connect.WithSchema(sliceServiceMethods.ByName("DeleteSliceSecret")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceListSliceSecretsHandler := connect.NewUnaryHandler(
		SliceServiceListSliceSecretsProcedure,
		svc.ListSliceSecrets,
		connect.WithSchema(sliceServiceMethods.ByName("ListSliceSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	sliceServiceDeleteSliceHandler := connect.NewUnaryHandler(
		SliceServiceDeleteSliceProcedure,
		svc.DeleteSlice,
		connect.WithSchema(sliceServiceMethods.ByName("DeleteSlice")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.SliceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SliceServiceCreateSliceProcedure:
			sliceServiceCreateSliceHandler.ServeHTTP(w, r)
		case SliceServiceResolveSliceProcedure:
			sliceServiceResolveSliceHandler.ServeHTTP(w, r)
		case SliceServiceGetSliceProcedure:
			sliceServiceGetSliceHandler.ServeHTTP(w, r)
		case SliceServiceListSlicesProcedure:
			sliceServiceListSlicesHandler.ServeHTTP(w, r)
		case SliceServiceListSliceDefinitionVersionsProcedure:
			sliceServiceListSliceDefinitionVersionsHandler.ServeHTTP(w, r)
		case SliceServiceUpdateSliceDefinitionProcedure:
			sliceServiceUpdateSliceDefinitionHandler.ServeHTTP(w, r)
		case SliceServiceSetSliceCIDaemonProcedure:
			sliceServiceSetSliceCIDaemonHandler.ServeHTTP(w, r)
		case SliceServiceSetSliceSecretProcedure:
			sliceServiceSetSliceSecretHandler.ServeHTTP(w, r)
		case SliceServiceDeleteSliceSecretProcedure:
			sliceServiceDeleteSliceSecretHandler.ServeHTTP(w, r)
		case SliceServiceListSliceSecretsProcedure:
			sliceServiceListSliceSecretsHandler.ServeHTTP(w, r)
		case SliceServiceDeleteSliceProcedure:
			sliceServiceDeleteSliceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSliceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSliceServiceHandler struct{}

func (UnimplementedSliceServiceHandler) CreateSlice(context.Context, *connect.Request[v1.CreateSliceRequest]) (*connect.Response[v1.Slice], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.CreateSlice is not implemented"))
}

func (UnimplementedSliceServiceHandler) ResolveSlice(context.Context, *connect.Request[v1.ResolveSliceRequest]) (*connect.Response[v1.Slice], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.ResolveSlice is not implemented"))
}

func (UnimplementedSliceServiceHandler) GetSlice(context.Context, *connect.Request[v1.GetSliceRequest]) (*connect.Response[v1.Slice], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.GetSlice is not implemented"))
}

func (UnimplementedSliceServiceHandler) ListSlices(context.Context, *connect.Request[v1.ListSlicesRequest]) (*connect.Response[v1.ListSlicesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.ListSlices is not implemented"))
}

func (UnimplementedSliceServiceHandler) ListSliceDefinitionVersions(context.Context, *connect.Request[v1.ListSliceDefinitionVersionsRequest]) (*connect.Response[v1.ListSliceDefinitionVersionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.ListSliceDefinitionVersions is not implemented"))
}

func (UnimplementedSliceServiceHandler) UpdateSliceDefinition(context.Context, *connect.Request[v1.UpdateSliceDefinitionRequest]) (*connect.Response[v1.SliceDefinition], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.UpdateSliceDefinition is not implemented"))
}

func (UnimplementedSliceServiceHandler) SetSliceCIDaemon(context.Context, *connect.Request[v1.SetSliceCIDaemonRequest]) (*connect.Response[v1.Slice], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.SetSliceCIDaemon is not implemented"))
}

func (UnimplementedSliceServiceHandler) SetSliceSecret(context.Context, *connect.Request[v1.SetSliceSecretRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.SetSliceSecret is not implemented"))
}

func (UnimplementedSliceServiceHandler) DeleteSliceSecret(context.Context, *connect.Request[v1.DeleteSliceSecretRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.DeleteSliceSecret is not implemented"))
}

func (UnimplementedSliceServiceHandler) ListSliceSecrets(context.Context, *connect.Request[v1.ListSliceSecretsRequest]) (*connect.Response[v1.ListSliceSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.ListSliceSecrets is not implemented"))
}

func (UnimplementedSliceServiceHandler) DeleteSlice(context.Context, *connect.Request[v1.DeleteSliceRequest]) (*connect.Response[v1.DeleteSliceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.SliceService.DeleteSlice is not implemented"))
}
