// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/core/v1/webhook.proto

package corev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "gitslice.io/gitslice/proto/core/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WebhookServiceName is the fully-qualified name of the WebhookService service.
	WebhookServiceName = "gitslice.core.v1.WebhookService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WebhookServiceCreateWebhookProcedure is the fully-qualified name of the WebhookService's
	// CreateWebhook RPC.
	WebhookServiceCreateWebhookProcedure = "/gitslice.core.v1.WebhookService/CreateWebhook"
	// WebhookServiceListWebhooksProcedure is the fully-qualified name of the WebhookService's
	// ListWebhooks RPC.
	WebhookServiceListWebhooksProcedure = "/gitslice.core.v1.WebhookService/ListWebhooks"
	// WebhookServiceUpdateWebhookProcedure is the fully-qualified name of the WebhookService's
	// UpdateWebhook RPC.
	WebhookServiceUpdateWebhookProcedure = "/gitslice.core.v1.WebhookService/UpdateWebhook"
	// WebhookServiceDeleteWebhookProcedure is the fully-qualified name of the WebhookService's
	// DeleteWebhook RPC.
	WebhookServiceDeleteWebhookProcedure = "/gitslice.core.v1.WebhookService/DeleteWebhook"
	// WebhookServicePingWebhookProcedure is the fully-qualified name of the WebhookService's
	// PingWebhook RPC.
	WebhookServicePingWebhookProcedure = "/gitslice.core.v1.WebhookService/PingWebhook"
	// WebhookServiceListWebhookDeliveriesProcedure is the fully-qualified name of the WebhookService's
	// ListWebhookDeliveries RPC.
	WebhookServiceListWebhookDeliveriesProcedure = "/gitslice.core.v1.WebhookService/ListWebhookDeliveries"
	// WebhookServiceRedeliverWebhookDeliveryProcedure is the fully-qualified name of the
	// WebhookService's RedeliverWebhookDelivery RPC.
	WebhookServiceRedeliverWebhookDeliveryProcedure = "/gitslice.core.v1.WebhookService/RedeliverWebhookDelivery"
)

// WebhookServiceClient is a client for the gitslice.core.v1.WebhookService service.
type WebhookServiceClient interface {
	CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.Webhook], error)
	ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error)
	UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.Webhook], error)
	DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.Empty], error)
	// PingWebhook sends a ping event now and returns its delivery.
	PingWebhook(context.Context, *connect.Request[v1.PingWebhookRequest]) (*connect.Response[v1.WebhookDelivery], error)
	// ListWebhookDeliveries lists a webhook's recent deliveries, newest first.
	ListWebhookDeliveries(context.Context, *connect.Request[v1.ListWebhookDeliveriesRequest]) (*connect.Response[v1.ListWebhookDeliveriesResponse], error)
	// RedeliverWebhookDelivery sends a delivery's event again, now, as a new
	// delivery with the same event id.
	RedeliverWebhookDelivery(context.Context, *connect.Request[v1.RedeliverWebhookDeliveryRequest]) (*connect.Response[v1.WebhookDelivery], error)
}

// NewWebhookServiceClient constructs a client for the gitslice.core.v1.WebhookService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWebhookServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WebhookServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	webhookServiceMethods := v1.File_proto_core_v1_webhook_proto.Services().ByName("WebhookService").Methods()
	return &webhookServiceClient{
		createWebhook: connect.NewClient[v1.CreateWebhookRequest, v1.Webhook](
			httpClient,
			baseURL+WebhookServiceCreateWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("CreateWebhook")),
			connect.WithClientOptions(opts...),
		),
		listWebhooks: connect.NewClient[v1.ListWebhooksRequest, v1.ListWebhooksResponse](
			httpClient,
			baseURL+WebhookServiceListWebhooksProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("ListWebhooks")),
			connect.WithClientOptions(opts...),
		),
		updateWebhook: connect.NewClient[v1.UpdateWebhookRequest, v1.Webhook](
			httpClient,
			baseURL+WebhookServiceUpdateWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("UpdateWebhook")),
			connect.WithClientOptions(opts...),
		),
		deleteWebhook: connect.NewClient[v1.DeleteWebhookRequest, v1.Empty](
			httpClient,
			baseURL+WebhookServiceDeleteWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("DeleteWebhook")),
			connect.WithClientOptions(opts...),
		),
		pingWebhook: connect.NewClient[v1.PingWebhookRequest, v1.WebhookDelivery](
			httpClient,
			baseURL+WebhookServicePingWebhookProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("PingWebhook")),
			connect.WithClientOptions(opts...),
		),
		listWebhookDeliveries: connect.NewClient[v1.ListWebhookDeliveriesRequest, v1.ListWebhookDeliveriesResponse](
			httpClient,
			baseURL+WebhookServiceListWebhookDeliveriesProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("ListWebhookDeliveries")),
			connect.WithClientOptions(opts...),
		),
		redeliverWebhookDelivery: connect.NewClient[v1.RedeliverWebhookDeliveryRequest, v1.WebhookDelivery](
			httpClient,
			baseURL+WebhookServiceRedeliverWebhookDeliveryProcedure,
			connect.WithSchema(webhookServiceMethods.ByName("RedeliverWebhookDelivery")),
			connect.WithClientOptions(opts...),
		),
	}
}

// webhookServiceClient implements WebhookServiceClient.
type webhookServiceClient struct {
	createWebhook            *connect.Client[v1.CreateWebhookRequest, v1.Webhook]
	listWebhooks             *connect.Client[v1.ListWebhooksRequest, v1.ListWebhooksResponse]
	updateWebhook            *connect.Client[v1.UpdateWebhookRequest, v1.Webhook]
	deleteWebhook            *connect.Client[v1.DeleteWebhookRequest, v1.Empty]
	pingWebhook              *connect.Client[v1.PingWebhookRequest, v1.WebhookDelivery]
	listWebhookDeliveries    *connect.Client[v1.ListWebhookDeliveriesRequest, v1.ListWebhookDeliveriesResponse]
	redeliverWebhookDelivery *connect.Client[v1.RedeliverWebhookDeliveryRequest, v1.WebhookDelivery]
}

// CreateWebhook calls gitslice.core.v1.WebhookService.CreateWebhook.
func (c *webhookServiceClient) CreateWebhook(ctx context.Context, req *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.Webhook], error) {
	return c.createWebhook.CallUnary(ctx, req)
}

// ListWebhooks calls gitslice.core.v1.WebhookService.ListWebhooks.
func (c *webhookServiceClient) ListWebhooks(ctx context.Context, req *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	return c.listWebhooks.CallUnary(ctx, req)
}

// UpdateWebhook calls gitslice.core.v1.WebhookService.UpdateWebhook.
func (c *webhookServiceClient) UpdateWebhook(ctx context.Context, req *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.Webhook], error) {
	return c.updateWebhook.CallUnary(ctx, req)
}

// DeleteWebhook calls gitslice.core.v1.WebhookService.DeleteWebhook.
func (c *webhookServiceClient) DeleteWebhook(ctx context.Context, req *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.Empty], error) {
	return c.deleteWebhook.CallUnary(ctx, req)
}

// PingWebhook calls gitslice.core.v1.WebhookService.PingWebhook.
func (c *webhookServiceClient) PingWebhook(ctx context.Context, req *connect.Request[v1.PingWebhookRequest]) (*connect.Response[v1.WebhookDelivery], error) {
	return c.pingWebhook.CallUnary(ctx, req)
}

// ListWebhookDeliveries calls gitslice.core.v1.WebhookService.ListWebhookDeliveries.
func (c *webhookServiceClient) ListWebhookDeliveries(ctx context.Context, req *connect.Request[v1.ListWebhookDeliveriesRequest]) (*connect.Response[v1.ListWebhookDeliveriesResponse], error) {
	return c.listWebhookDeliveries.CallUnary(ctx, req)
}

// RedeliverWebhookDelivery calls gitslice.core.v1.WebhookService.RedeliverWebhookDelivery.
func (c *webhookServiceClient) RedeliverWebhookDelivery(ctx context.Context, req *connect.Request[v1.RedeliverWebhookDeliveryRequest]) (*connect.Response[v1.WebhookDelivery], error) {
	return c.redeliverWebhookDelivery.CallUnary(ctx, req)
}

// WebhookServiceHandler is an implementation of the gitslice.core.v1.WebhookService service.
type WebhookServiceHandler interface {
	CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.Webhook], error)
	ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error)
	UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.Webhook], error)
	DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.Empty], error)
	// PingWebhook sends a ping event now and returns its delivery.
	PingWebhook(context.Context, *connect.Request[v1.PingWebhookRequest]) (*connect.Response[v1.WebhookDelivery], error)
	// ListWebhookDeliveries lists a webhook's recent deliveries, newest first.
	ListWebhookDeliveries(context.Context, *connect.Request[v1.ListWebhookDeliveriesRequest]) (*connect.Response[v1.ListWebhookDeliveriesResponse], error)
	// RedeliverWebhookDelivery sends a delivery's event again, now, as a new
	// delivery with the same event id.
	RedeliverWebhookDelivery(context.Context, *connect.Request[v1.RedeliverWebhookDeliveryRequest]) (*connect.Response[v1.WebhookDelivery], error)
}

// NewWebhookServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWebhookServiceHandler(svc WebhookServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	webhookServiceMethods := v1.File_proto_core_v1_webhook_proto.Services().ByName("WebhookService").Methods()
	webhookServiceCreateWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceCreateWebhookProcedure,
		svc.CreateWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("CreateWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceListWebhooksHandler := connect.NewUnaryHandler(
		WebhookServiceListWebhooksProcedure,
		svc.ListWebhooks,
		connect.WithSchema(webhookServiceMethods.ByName("ListWebhooks")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceUpdateWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceUpdateWebhookProcedure,
		svc.UpdateWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("UpdateWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceDeleteWebhookHandler := connect.NewUnaryHandler(
		WebhookServiceDeleteWebhookProcedure,
		svc.DeleteWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("DeleteWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServicePingWebhookHandler := connect.NewUnaryHandler(
		WebhookServicePingWebhookProcedure,
		svc.PingWebhook,
		connect.WithSchema(webhookServiceMethods.ByName("PingWebhook")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceListWebhookDeliveriesHandler := connect.NewUnaryHandler(
		WebhookServiceListWebhookDeliveriesProcedure,
		svc.ListWebhookDeliveries,
		connect.WithSchema(webhookServiceMethods.ByName("ListWebhookDeliveries")),
		connect.WithHandlerOptions(opts...),
	)
	webhookServiceRedeliverWebhookDeliveryHandler := connect.NewUnaryHandler(
		WebhookServiceRedeliverWebhookDeliveryProcedure,
		svc.RedeliverWebhookDelivery,
		connect.WithSchema(webhookServiceMethods.ByName("RedeliverWebhookDelivery")),
		connect.WithHandlerOptions(opts...),
	)
	return "/gitslice.core.v1.WebhookService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WebhookServiceCreateWebhookProcedure:
			webhookServiceCreateWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceListWebhooksProcedure:
			webhookServiceListWebhooksHandler.ServeHTTP(w, r)
		case WebhookServiceUpdateWebhookProcedure:
			webhookServiceUpdateWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceDeleteWebhookProcedure:
			webhookServiceDeleteWebhookHandler.ServeHTTP(w, r)
		case WebhookServicePingWebhookProcedure:
			webhookServicePingWebhookHandler.ServeHTTP(w, r)
		case WebhookServiceListWebhookDeliveriesProcedure:
			webhookServiceListWebhookDeliveriesHandler.ServeHTTP(w, r)
		case WebhookServiceRedeliverWebhookDeliveryProcedure:
			webhookServiceRedeliverWebhookDeliveryHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWebhookServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWebhookServiceHandler struct{}

func (UnimplementedWebhookServiceHandler) CreateWebhook(context.Context, *connect.Request[v1.CreateWebhookRequest]) (*connect.Response[v1.Webhook], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.CreateWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) ListWebhooks(context.Context, *connect.Request[v1.ListWebhooksRequest]) (*connect.Response[v1.ListWebhooksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.ListWebhooks is not implemented"))
}

func (UnimplementedWebhookServiceHandler) UpdateWebhook(context.Context, *connect.Request[v1.UpdateWebhookRequest]) (*connect.Response[v1.Webhook], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.UpdateWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) DeleteWebhook(context.Context, *connect.Request[v1.DeleteWebhookRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.DeleteWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) PingWebhook(context.Context, *connect.Request[v1.PingWebhookRequest]) (*connect.Response[v1.WebhookDelivery], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.PingWebhook is not implemented"))
}

func (UnimplementedWebhookServiceHandler) ListWebhookDeliveries(context.Context, *connect.Request[v1.ListWebhookDeliveriesRequest]) (*connect.Response[v1.ListWebhookDeliveriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.ListWebhookDeliveries is not implemented"))
}

func (UnimplementedWebhookServiceHandler) RedeliverWebhookDelivery(context.Context, *connect.Request[v1.RedeliverWebhookDeliveryRequest]) (*connect.Response[v1.WebhookDelivery], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("gitslice.core.v1.WebhookService.RedeliverWebhookDelivery is not implemented"))
}
