// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.5
// source: proto/core/v1/auth.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartCliLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartCliLoginRequest) Reset() {
	*x = StartCliLoginRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCliLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCliLoginRequest) ProtoMessage() {}

func (x *StartCliLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCliLoginRequest.ProtoReflect.Descriptor instead.
func (*StartCliLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{0}
}

type StartCliLoginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Code                string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ExpiresAt           string                 `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	PollIntervalSeconds int32                  `protobuf:"varint,3,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StartCliLoginResponse) Reset() {
	*x = StartCliLoginResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartCliLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartCliLoginResponse) ProtoMessage() {}

func (x *StartCliLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartCliLoginResponse.ProtoReflect.Descriptor instead.
func (*StartCliLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *StartCliLoginResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StartCliLoginResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *StartCliLoginResponse) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

type PollCliLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCliLoginRequest) Reset() {
	*x = PollCliLoginRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCliLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCliLoginRequest) ProtoMessage() {}

func (x *PollCliLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCliLoginRequest.ProtoReflect.Descriptor instead.
func (*PollCliLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *PollCliLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PollCliLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	SubjectId     string                 `protobuf:"bytes,3,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCliLoginResponse) Reset() {
	*x = PollCliLoginResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCliLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCliLoginResponse) ProtoMessage() {}

func (x *PollCliLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCliLoginResponse.ProtoReflect.Descriptor instead.
func (*PollCliLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *PollCliLoginResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PollCliLoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PollCliLoginResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type CompleteCliLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCliLoginRequest) Reset() {
	*x = CompleteCliLoginRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCliLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCliLoginRequest) ProtoMessage() {}

func (x *CompleteCliLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCliLoginRequest.ProtoReflect.Descriptor instead.
func (*CompleteCliLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteCliLoginRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type CompleteCliLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubjectId     string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteCliLoginResponse) Reset() {
	*x = CompleteCliLoginResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteCliLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteCliLoginResponse) ProtoMessage() {}

func (x *CompleteCliLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteCliLoginResponse.ProtoReflect.Descriptor instead.
func (*CompleteCliLoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteCliLoginResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

type GetAuthStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStatusRequest) Reset() {
	*x = GetAuthStatusRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStatusRequest) ProtoMessage() {}

func (x *GetAuthStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAuthStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{6}
}

type GetAuthStatusResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SubjectId string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// Account slugs the authenticated subject belongs to. The first is the
	// subject's personal account, whose "home" slice covers "/<account>".
	Accounts []string `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	// True when the subject has no personal account yet and must choose a
	// username before using account-scoped features.
	NeedsUsername bool `protobuf:"varint,3,opt,name=needs_username,json=needsUsername,proto3" json:"needs_username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthStatusResponse) Reset() {
	*x = GetAuthStatusResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthStatusResponse) ProtoMessage() {}

func (x *GetAuthStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAuthStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *GetAuthStatusResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetAuthStatusResponse) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GetAuthStatusResponse) GetNeedsUsername() bool {
	if x != nil {
		return x.NeedsUsername
	}
	return false
}

type CheckUsernameAvailableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailableRequest) Reset() {
	*x = CheckUsernameAvailableRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailableRequest) ProtoMessage() {}

func (x *CheckUsernameAvailableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailableRequest.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailableRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *CheckUsernameAvailableRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CheckUsernameAvailableResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Available bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	// The normalized username that would be used (lowercased, '_' -> '-').
	Normalized string `protobuf:"bytes,2,opt,name=normalized,proto3" json:"normalized,omitempty"`
	// When not available or invalid, a short human-readable reason (e.g.
	// "username is taken", or a validation message). Empty when available.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUsernameAvailableResponse) Reset() {
	*x = CheckUsernameAvailableResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUsernameAvailableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUsernameAvailableResponse) ProtoMessage() {}

func (x *CheckUsernameAvailableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUsernameAvailableResponse.ProtoReflect.Descriptor instead.
func (*CheckUsernameAvailableResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *CheckUsernameAvailableResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckUsernameAvailableResponse) GetNormalized() string {
	if x != nil {
		return x.Normalized
	}
	return ""
}

func (x *CheckUsernameAvailableResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ChooseUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseUsernameRequest) Reset() {
	*x = ChooseUsernameRequest{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseUsernameRequest) ProtoMessage() {}

func (x *ChooseUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseUsernameRequest.ProtoReflect.Descriptor instead.
func (*ChooseUsernameRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ChooseUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ChooseUsernameResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SubjectId string                 `protobuf:"bytes,1,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// The chosen personal account slug.
	Account       string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseUsernameResponse) Reset() {
	*x = ChooseUsernameResponse{}
	mi := &file_proto_core_v1_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseUsernameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseUsernameResponse) ProtoMessage() {}

func (x *ChooseUsernameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseUsernameResponse.ProtoReflect.Descriptor instead.
func (*ChooseUsernameResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_auth_proto_rawDescGZIP(), []int{11}
}

func (x *ChooseUsernameResponse) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ChooseUsernameResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

var File_proto_core_v1_auth_proto protoreflect.FileDescriptor

const file_proto_core_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x18proto/core/v1/auth.proto\x12\x10gitslice.core.v1\"\x16\n" +
	"\x14StartCliLoginRequest\"~\n" +
	"\x15StartCliLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\tR\texpiresAt\x122\n" +
	"\x15poll_interval_seconds\x18\x03 \x01(\x05R\x13pollIntervalSeconds\")\n" +
	"\x13PollCliLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"c\n" +
	"\x14PollCliLoginResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x03 \x01(\tR\tsubjectId\"-\n" +
	"\x17CompleteCliLoginRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"9\n" +
	"\x18CompleteCliLoginResponse\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\"\x16\n" +
	"\x14GetAuthStatusRequest\"y\n" +
	"\x15GetAuthStatusResponse\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x1a\n" +
	"\baccounts\x18\x02 \x03(\tR\baccounts\x12%\n" +
	"\x0eneeds_username\x18\x03 \x01(\bR\rneedsUsername\";\n" +
	"\x1dCheckUsernameAvailableRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"v\n" +
	"\x1eCheckUsernameAvailableResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1e\n" +
	"\n" +
	"normalized\x18\x02 \x01(\tR\n" +
	"normalized\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"3\n" +
	"\x15ChooseUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"Q\n" +
	"\x16ChooseUsernameResponse\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x01 \x01(\tR\tsubjectId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount2\xfd\x04\n" +
	"\vAuthService\x12`\n" +
	"\rStartCliLogin\x12&.gitslice.core.v1.StartCliLoginRequest\x1a'.gitslice.core.v1.StartCliLoginResponse\x12]\n" +
	"\fPollCliLogin\x12%.gitslice.core.v1.PollCliLoginRequest\x1a&.gitslice.core.v1.PollCliLoginResponse\x12i\n" +
	"\x10CompleteCliLogin\x12).gitslice.core.v1.CompleteCliLoginRequest\x1a*.gitslice.core.v1.CompleteCliLoginResponse\x12`\n" +
	"\rGetAuthStatus\x12&.gitslice.core.v1.GetAuthStatusRequest\x1a'.gitslice.core.v1.GetAuthStatusResponse\x12{\n" +
	"\x16CheckUsernameAvailable\x12/.gitslice.core.v1.CheckUsernameAvailableRequest\x1a0.gitslice.core.v1.CheckUsernameAvailableResponse\x12c\n" +
	"\x0eChooseUsername\x12'.gitslice.core.v1.ChooseUsernameRequest\x1a(.gitslice.core.v1.ChooseUsernameResponseB6Z4github.com/gitslice-io/gitslice/proto/core/v1;corev1b\x06proto3"

var (
	file_proto_core_v1_auth_proto_rawDescOnce sync.Once
	file_proto_core_v1_auth_proto_rawDescData []byte
)

func file_proto_core_v1_auth_proto_rawDescGZIP() []byte {
	file_proto_core_v1_auth_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_auth_proto_rawDesc), len(file_proto_core_v1_auth_proto_rawDesc)))
	})
	return file_proto_core_v1_auth_proto_rawDescData
}

var file_proto_core_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_core_v1_auth_proto_goTypes = []any{
	(*StartCliLoginRequest)(nil),           // 0: gitslice.core.v1.StartCliLoginRequest
	(*StartCliLoginResponse)(nil),          // 1: gitslice.core.v1.StartCliLoginResponse
	(*PollCliLoginRequest)(nil),            // 2: gitslice.core.v1.PollCliLoginRequest
	(*PollCliLoginResponse)(nil),           // 3: gitslice.core.v1.PollCliLoginResponse
	(*CompleteCliLoginRequest)(nil),        // 4: gitslice.core.v1.CompleteCliLoginRequest
	(*CompleteCliLoginResponse)(nil),       // 5: gitslice.core.v1.CompleteCliLoginResponse
	(*GetAuthStatusRequest)(nil),           // 6: gitslice.core.v1.GetAuthStatusRequest
	(*GetAuthStatusResponse)(nil),          // 7: gitslice.core.v1.GetAuthStatusResponse
	(*CheckUsernameAvailableRequest)(nil),  // 8: gitslice.core.v1.CheckUsernameAvailableRequest
	(*CheckUsernameAvailableResponse)(nil), // 9: gitslice.core.v1.CheckUsernameAvailableResponse
	(*ChooseUsernameRequest)(nil),          // 10: gitslice.core.v1.ChooseUsernameRequest
	(*ChooseUsernameResponse)(nil),         // 11: gitslice.core.v1.ChooseUsernameResponse
}
var file_proto_core_v1_auth_proto_depIdxs = []int32{
	0,  // 0: gitslice.core.v1.AuthService.StartCliLogin:input_type -> gitslice.core.v1.StartCliLoginRequest
	2,  // 1: gitslice.core.v1.AuthService.PollCliLogin:input_type -> gitslice.core.v1.PollCliLoginRequest
	4,  // 2: gitslice.core.v1.AuthService.CompleteCliLogin:input_type -> gitslice.core.v1.CompleteCliLoginRequest
	6,  // 3: gitslice.core.v1.AuthService.GetAuthStatus:input_type -> gitslice.core.v1.GetAuthStatusRequest
	8,  // 4: gitslice.core.v1.AuthService.CheckUsernameAvailable:input_type -> gitslice.core.v1.CheckUsernameAvailableRequest
	10, // 5: gitslice.core.v1.AuthService.ChooseUsername:input_type -> gitslice.core.v1.ChooseUsernameRequest
	1,  // 6: gitslice.core.v1.AuthService.StartCliLogin:output_type -> gitslice.core.v1.StartCliLoginResponse
	3,  // 7: gitslice.core.v1.AuthService.PollCliLogin:output_type -> gitslice.core.v1.PollCliLoginResponse
	5,  // 8: gitslice.core.v1.AuthService.CompleteCliLogin:output_type -> gitslice.core.v1.CompleteCliLoginResponse
	7,  // 9: gitslice.core.v1.AuthService.GetAuthStatus:output_type -> gitslice.core.v1.GetAuthStatusResponse
	9,  // 10: gitslice.core.v1.AuthService.CheckUsernameAvailable:output_type -> gitslice.core.v1.CheckUsernameAvailableResponse
	11, // 11: gitslice.core.v1.AuthService.ChooseUsername:output_type -> gitslice.core.v1.ChooseUsernameResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_core_v1_auth_proto_init() }
func file_proto_core_v1_auth_proto_init() {
	if File_proto_core_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_auth_proto_rawDesc), len(file_proto_core_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_auth_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_auth_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_auth_proto_msgTypes,
	}.Build()
	File_proto_core_v1_auth_proto = out.File
	file_proto_core_v1_auth_proto_goTypes = nil
	file_proto_core_v1_auth_proto_depIdxs = nil
}
