// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.5
// source: proto/core/v1/auth.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AuthService_StartCliLogin_FullMethodName          = "/gitslice.core.v1.AuthService/StartCliLogin"
	AuthService_PollCliLogin_FullMethodName           = "/gitslice.core.v1.AuthService/PollCliLogin"
	AuthService_CompleteCliLogin_FullMethodName       = "/gitslice.core.v1.AuthService/CompleteCliLogin"
	AuthService_GetAuthStatus_FullMethodName          = "/gitslice.core.v1.AuthService/GetAuthStatus"
	AuthService_CheckUsernameAvailable_FullMethodName = "/gitslice.core.v1.AuthService/CheckUsernameAvailable"
	AuthService_ChooseUsername_FullMethodName         = "/gitslice.core.v1.AuthService/ChooseUsername"
	AuthService_RegisterAgent_FullMethodName          = "/gitslice.core.v1.AuthService/RegisterAgent"
	AuthService_ListPendingClaims_FullMethodName      = "/gitslice.core.v1.AuthService/ListPendingClaims"
	AuthService_AcceptClaim_FullMethodName            = "/gitslice.core.v1.AuthService/AcceptClaim"
	AuthService_ListOwnedAgents_FullMethodName        = "/gitslice.core.v1.AuthService/ListOwnedAgents"
	AuthService_CreateOrganization_FullMethodName     = "/gitslice.core.v1.AuthService/CreateOrganization"
	AuthService_ListAccountMembers_FullMethodName     = "/gitslice.core.v1.AuthService/ListAccountMembers"
	AuthService_SetAccountMember_FullMethodName       = "/gitslice.core.v1.AuthService/SetAccountMember"
	AuthService_RemoveAccountMember_FullMethodName    = "/gitslice.core.v1.AuthService/RemoveAccountMember"
)

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceClient interface {
	StartCliLogin(ctx context.Context, in *StartCliLoginRequest, opts ...grpc.CallOption) (*StartCliLoginResponse, error)
	PollCliLogin(ctx context.Context, in *PollCliLoginRequest, opts ...grpc.CallOption) (*PollCliLoginResponse, error)
	CompleteCliLogin(ctx context.Context, in *CompleteCliLoginRequest, opts ...grpc.CallOption) (*CompleteCliLoginResponse, error)
	GetAuthStatus(ctx context.Context, in *GetAuthStatusRequest, opts ...grpc.CallOption) (*GetAuthStatusResponse, error)
	CheckUsernameAvailable(ctx context.Context, in *CheckUsernameAvailableRequest, opts ...grpc.CallOption) (*CheckUsernameAvailableResponse, error)
	ChooseUsername(ctx context.Context, in *ChooseUsernameRequest, opts ...grpc.CallOption) (*ChooseUsernameResponse, error)
	// RegisterAgent self-registers an agent with its own personal account and
	// returns a long-lived API key. Unauthenticated; disabled unless the server
	// sets GITSLICE_AGENT_SIGNUP_ENABLED. See design/20_agent_signup_and_claim.md.
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// ListPendingClaims lists agent registrations the caller may claim: unclaimed
	// agents whose owner email is one of the caller's verified emails.
	ListPendingClaims(ctx context.Context, in *ListPendingClaimsRequest, opts ...grpc.CallOption) (*ListPendingClaimsResponse, error)
	// AcceptClaim makes the caller an owner of the agent's account. The agent
	// keeps its own access, so the account becomes co-owned.
	AcceptClaim(ctx context.Context, in *AcceptClaimRequest, opts ...grpc.CallOption) (*AcceptClaimResponse, error)
	// ListOwnedAgents lists the self-registered agents whose accounts the caller
	// owns (typically after AcceptClaim), with basic activity.
	ListOwnedAgents(ctx context.Context, in *ListOwnedAgentsRequest, opts ...grpc.CallOption) (*ListOwnedAgentsResponse, error)
	// CreateOrganization creates an organization account (with a private home
	// slice) owned by the given users. Operator-only: the caller's subject must
	// be listed in the server's GITSLICE_OPERATOR_SUBJECTS. Operators may use
	// names reserved for self-service sign-up.
	CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error)
	// ListAccountMembers lists an account's members. Any member may call it.
	ListAccountMembers(ctx context.Context, in *ListAccountMembersRequest, opts ...grpc.CallOption) (*ListAccountMembersResponse, error)
	// SetAccountMember adds a user to an organization or changes their role.
	// Owners and admins may call it; only owners grant or revoke owner.
	SetAccountMember(ctx context.Context, in *SetAccountMemberRequest, opts ...grpc.CallOption) (*SetAccountMemberResponse, error)
	// RemoveAccountMember removes a user from an organization. The last owner
	// cannot be removed.
	RemoveAccountMember(ctx context.Context, in *RemoveAccountMemberRequest, opts ...grpc.CallOption) (*RemoveAccountMemberResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) StartCliLogin(ctx context.Context, in *StartCliLoginRequest, opts ...grpc.CallOption) (*StartCliLoginResponse, error) {
	out := new(StartCliLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_StartCliLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) PollCliLogin(ctx context.Context, in *PollCliLoginRequest, opts ...grpc.CallOption) (*PollCliLoginResponse, error) {
	out := new(PollCliLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_PollCliLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CompleteCliLogin(ctx context.Context, in *CompleteCliLoginRequest, opts ...grpc.CallOption) (*CompleteCliLoginResponse, error) {
	out := new(CompleteCliLoginResponse)
	err := c.cc.Invoke(ctx, AuthService_CompleteCliLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetAuthStatus(ctx context.Context, in *GetAuthStatusRequest, opts ...grpc.CallOption) (*GetAuthStatusResponse, error) {
	out := new(GetAuthStatusResponse)
	err := c.cc.Invoke(ctx, AuthService_GetAuthStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CheckUsernameAvailable(ctx context.Context, in *CheckUsernameAvailableRequest, opts ...grpc.CallOption) (*CheckUsernameAvailableResponse, error) {
	out := new(CheckUsernameAvailableResponse)
	err := c.cc.Invoke(ctx, AuthService_CheckUsernameAvailable_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ChooseUsername(ctx context.Context, in *ChooseUsernameRequest, opts ...grpc.CallOption) (*ChooseUsernameResponse, error) {
	out := new(ChooseUsernameResponse)
	err := c.cc.Invoke(ctx, AuthService_ChooseUsername_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, AuthService_RegisterAgent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListPendingClaims(ctx context.Context, in *ListPendingClaimsRequest, opts ...grpc.CallOption) (*ListPendingClaimsResponse, error) {
	out := new(ListPendingClaimsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListPendingClaims_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) AcceptClaim(ctx context.Context, in *AcceptClaimRequest, opts ...grpc.CallOption) (*AcceptClaimResponse, error) {
	out := new(AcceptClaimResponse)
	err := c.cc.Invoke(ctx, AuthService_AcceptClaim_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListOwnedAgents(ctx context.Context, in *ListOwnedAgentsRequest, opts ...grpc.CallOption) (*ListOwnedAgentsResponse, error) {
	out := new(ListOwnedAgentsResponse)
	err := c.cc.Invoke(ctx, AuthService_ListOwnedAgents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) CreateOrganization(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*CreateOrganizationResponse, error) {
	out := new(CreateOrganizationResponse)
	err := c.cc.Invoke(ctx, AuthService_CreateOrganization_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ListAccountMembers(ctx context.Context, in *ListAccountMembersRequest, opts ...grpc.CallOption) (*ListAccountMembersResponse, error) {
	out := new(ListAccountMembersResponse)
	err := c.cc.Invoke(ctx, AuthService_ListAccountMembers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SetAccountMember(ctx context.Context, in *SetAccountMemberRequest, opts ...grpc.CallOption) (*SetAccountMemberResponse, error) {
	out := new(SetAccountMemberResponse)
	err := c.cc.Invoke(ctx, AuthService_SetAccountMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) RemoveAccountMember(ctx context.Context, in *RemoveAccountMemberRequest, opts ...grpc.CallOption) (*RemoveAccountMemberResponse, error) {
	out := new(RemoveAccountMemberResponse)
	err := c.cc.Invoke(ctx, AuthService_RemoveAccountMember_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
// All implementations should embed UnimplementedAuthServiceServer
// for forward compatibility
type AuthServiceServer interface {
	StartCliLogin(context.Context, *StartCliLoginRequest) (*StartCliLoginResponse, error)
	PollCliLogin(context.Context, *PollCliLoginRequest) (*PollCliLoginResponse, error)
	CompleteCliLogin(context.Context, *CompleteCliLoginRequest) (*CompleteCliLoginResponse, error)
	GetAuthStatus(context.Context, *GetAuthStatusRequest) (*GetAuthStatusResponse, error)
	CheckUsernameAvailable(context.Context, *CheckUsernameAvailableRequest) (*CheckUsernameAvailableResponse, error)
	ChooseUsername(context.Context, *ChooseUsernameRequest) (*ChooseUsernameResponse, error)
	// RegisterAgent self-registers an agent with its own personal account and
	// returns a long-lived API key. Unauthenticated; disabled unless the server
	// sets GITSLICE_AGENT_SIGNUP_ENABLED. See design/20_agent_signup_and_claim.md.
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// ListPendingClaims lists agent registrations the caller may claim: unclaimed
	// agents whose owner email is one of the caller's verified emails.
	ListPendingClaims(context.Context, *ListPendingClaimsRequest) (*ListPendingClaimsResponse, error)
	// AcceptClaim makes the caller an owner of the agent's account. The agent
	// keeps its own access, so the account becomes co-owned.
	AcceptClaim(context.Context, *AcceptClaimRequest) (*AcceptClaimResponse, error)
	// ListOwnedAgents lists the self-registered agents whose accounts the caller
	// owns (typically after AcceptClaim), with basic activity.
	ListOwnedAgents(context.Context, *ListOwnedAgentsRequest) (*ListOwnedAgentsResponse, error)
	// CreateOrganization creates an organization account (with a private home
	// slice) owned by the given users. Operator-only: the caller's subject must
	// be listed in the server's GITSLICE_OPERATOR_SUBJECTS. Operators may use
	// names reserved for self-service sign-up.
	CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error)
	// ListAccountMembers lists an account's members. Any member may call it.
	ListAccountMembers(context.Context, *ListAccountMembersRequest) (*ListAccountMembersResponse, error)
	// SetAccountMember adds a user to an organization or changes their role.
	// Owners and admins may call it; only owners grant or revoke owner.
	SetAccountMember(context.Context, *SetAccountMemberRequest) (*SetAccountMemberResponse, error)
	// RemoveAccountMember removes a user from an organization. The last owner
	// cannot be removed.
	RemoveAccountMember(context.Context, *RemoveAccountMemberRequest) (*RemoveAccountMemberResponse, error)
}

// UnimplementedAuthServiceServer should be embedded to have forward compatible implementations.
type UnimplementedAuthServiceServer struct {
}

func (UnimplementedAuthServiceServer) StartCliLogin(context.Context, *StartCliLoginRequest) (*StartCliLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartCliLogin not implemented")
}
func (UnimplementedAuthServiceServer) PollCliLogin(context.Context, *PollCliLoginRequest) (*PollCliLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollCliLogin not implemented")
}
func (UnimplementedAuthServiceServer) CompleteCliLogin(context.Context, *CompleteCliLoginRequest) (*CompleteCliLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteCliLogin not implemented")
}
func (UnimplementedAuthServiceServer) GetAuthStatus(context.Context, *GetAuthStatusRequest) (*GetAuthStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthStatus not implemented")
}
func (UnimplementedAuthServiceServer) CheckUsernameAvailable(context.Context, *CheckUsernameAvailableRequest) (*CheckUsernameAvailableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckUsernameAvailable not implemented")
}
func (UnimplementedAuthServiceServer) ChooseUsername(context.Context, *ChooseUsernameRequest) (*ChooseUsernameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChooseUsername not implemented")
}
func (UnimplementedAuthServiceServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAuthServiceServer) ListPendingClaims(context.Context, *ListPendingClaimsRequest) (*ListPendingClaimsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPendingClaims not implemented")
}
func (UnimplementedAuthServiceServer) AcceptClaim(context.Context, *AcceptClaimRequest) (*AcceptClaimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptClaim not implemented")
}
func (UnimplementedAuthServiceServer) ListOwnedAgents(context.Context, *ListOwnedAgentsRequest) (*ListOwnedAgentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOwnedAgents not implemented")
}
func (UnimplementedAuthServiceServer) CreateOrganization(context.Context, *CreateOrganizationRequest) (*CreateOrganizationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrganization not implemented")
}
func (UnimplementedAuthServiceServer) ListAccountMembers(context.Context, *ListAccountMembersRequest) (*ListAccountMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountMembers not implemented")
}
func (UnimplementedAuthServiceServer) SetAccountMember(context.Context, *SetAccountMemberRequest) (*SetAccountMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetAccountMember not implemented")
}
func (UnimplementedAuthServiceServer) RemoveAccountMember(context.Context, *RemoveAccountMemberRequest) (*RemoveAccountMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAccountMember not implemented")
}

// UnsafeAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceServer will
// result in compilation errors.
type UnsafeAuthServiceServer interface {
	mustEmbedUnimplementedAuthServiceServer()
}

func RegisterAuthServiceServer(s grpc.ServiceRegistrar, srv AuthServiceServer) {
	s.RegisterService(&AuthService_ServiceDesc, srv)
}

func _AuthService_StartCliLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartCliLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).StartCliLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_StartCliLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).StartCliLogin(ctx, req.(*StartCliLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_PollCliLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCliLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).PollCliLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_PollCliLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).PollCliLogin(ctx, req.(*PollCliLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CompleteCliLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteCliLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CompleteCliLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CompleteCliLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CompleteCliLogin(ctx, req.(*CompleteCliLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetAuthStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetAuthStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_GetAuthStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetAuthStatus(ctx, req.(*GetAuthStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CheckUsernameAvailable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckUsernameAvailableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CheckUsernameAvailable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CheckUsernameAvailable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CheckUsernameAvailable(ctx, req.(*CheckUsernameAvailableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ChooseUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChooseUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ChooseUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ChooseUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ChooseUsername(ctx, req.(*ChooseUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListPendingClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPendingClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListPendingClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListPendingClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListPendingClaims(ctx, req.(*ListPendingClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_AcceptClaim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptClaimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).AcceptClaim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_AcceptClaim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).AcceptClaim(ctx, req.(*AcceptClaimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListOwnedAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOwnedAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListOwnedAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListOwnedAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListOwnedAgents(ctx, req.(*ListOwnedAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_CreateOrganization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).CreateOrganization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_CreateOrganization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).CreateOrganization(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_ListAccountMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).ListAccountMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_ListAccountMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).ListAccountMembers(ctx, req.(*ListAccountMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SetAccountMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SetAccountMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_SetAccountMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SetAccountMember(ctx, req.(*SetAccountMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_RemoveAccountMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAccountMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).RemoveAccountMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthService_RemoveAccountMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).RemoveAccountMember(ctx, req.(*RemoveAccountMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartCliLogin",
			Handler:    _AuthService_StartCliLogin_Handler,
		},
		{
			MethodName: "PollCliLogin",
			Handler:    _AuthService_PollCliLogin_Handler,
		},
		{
			MethodName: "CompleteCliLogin",
			Handler:    _AuthService_CompleteCliLogin_Handler,
		},
		{
			MethodName: "GetAuthStatus",
			Handler:    _AuthService_GetAuthStatus_Handler,
		},
		{
			MethodName: "CheckUsernameAvailable",
			Handler:    _AuthService_CheckUsernameAvailable_Handler,
		},
		{
			MethodName: "ChooseUsername",
			Handler:    _AuthService_ChooseUsername_Handler,
		},
		{
			MethodName: "RegisterAgent",
			Handler:    _AuthService_RegisterAgent_Handler,
		},
		{
			MethodName: "ListPendingClaims",
			Handler:    _AuthService_ListPendingClaims_Handler,
		},
		{
			MethodName: "AcceptClaim",
			Handler:    _AuthService_AcceptClaim_Handler,
		},
		{
			MethodName: "ListOwnedAgents",
			Handler:    _AuthService_ListOwnedAgents_Handler,
		},
		{
			MethodName: "CreateOrganization",
			Handler:    _AuthService_CreateOrganization_Handler,
		},
		{
			MethodName: "ListAccountMembers",
			Handler:    _AuthService_ListAccountMembers_Handler,
		},
		{
			MethodName: "SetAccountMember",
			Handler:    _AuthService_SetAccountMember_Handler,
		},
		{
			MethodName: "RemoveAccountMember",
			Handler:    _AuthService_RemoveAccountMember_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/auth.proto",
}
