// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.27.5
// source: proto/core/v1/blob.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	BlobService_GetBlobStatus_FullMethodName    = "/gitslice.core.v1.BlobService/GetBlobStatus"
	BlobService_UploadBlob_FullMethodName       = "/gitslice.core.v1.BlobService/UploadBlob"
	BlobService_UploadBlobStream_FullMethodName = "/gitslice.core.v1.BlobService/UploadBlobStream"
	BlobService_ReadBlobStream_FullMethodName   = "/gitslice.core.v1.BlobService/ReadBlobStream"
)

// BlobServiceClient is the client API for BlobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobServiceClient interface {
	GetBlobStatus(ctx context.Context, in *GetBlobStatusRequest, opts ...grpc.CallOption) (*GetBlobStatusResponse, error)
	UploadBlob(ctx context.Context, in *UploadBlobRequest, opts ...grpc.CallOption) (*UploadBlobResponse, error)
	UploadBlobStream(ctx context.Context, opts ...grpc.CallOption) (BlobService_UploadBlobStreamClient, error)
	ReadBlobStream(ctx context.Context, in *ReadBlobStreamRequest, opts ...grpc.CallOption) (BlobService_ReadBlobStreamClient, error)
}

type blobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobServiceClient(cc grpc.ClientConnInterface) BlobServiceClient {
	return &blobServiceClient{cc}
}

func (c *blobServiceClient) GetBlobStatus(ctx context.Context, in *GetBlobStatusRequest, opts ...grpc.CallOption) (*GetBlobStatusResponse, error) {
	out := new(GetBlobStatusResponse)
	err := c.cc.Invoke(ctx, BlobService_GetBlobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) UploadBlob(ctx context.Context, in *UploadBlobRequest, opts ...grpc.CallOption) (*UploadBlobResponse, error) {
	out := new(UploadBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_UploadBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) UploadBlobStream(ctx context.Context, opts ...grpc.CallOption) (BlobService_UploadBlobStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[0], BlobService_UploadBlobStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &blobServiceUploadBlobStreamClient{stream}
	return x, nil
}

type BlobService_UploadBlobStreamClient interface {
	Send(*UploadBlobChunk) error
	CloseAndRecv() (*UploadBlobResponse, error)
	grpc.ClientStream
}

type blobServiceUploadBlobStreamClient struct {
	grpc.ClientStream
}

func (x *blobServiceUploadBlobStreamClient) Send(m *UploadBlobChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *blobServiceUploadBlobStreamClient) CloseAndRecv() (*UploadBlobResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UploadBlobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blobServiceClient) ReadBlobStream(ctx context.Context, in *ReadBlobStreamRequest, opts ...grpc.CallOption) (BlobService_ReadBlobStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlobService_ServiceDesc.Streams[1], BlobService_ReadBlobStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &blobServiceReadBlobStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlobService_ReadBlobStreamClient interface {
	Recv() (*ReadBlobChunk, error)
	grpc.ClientStream
}

type blobServiceReadBlobStreamClient struct {
	grpc.ClientStream
}

func (x *blobServiceReadBlobStreamClient) Recv() (*ReadBlobChunk, error) {
	m := new(ReadBlobChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlobServiceServer is the server API for BlobService service.
// All implementations should embed UnimplementedBlobServiceServer
// for forward compatibility
type BlobServiceServer interface {
	GetBlobStatus(context.Context, *GetBlobStatusRequest) (*GetBlobStatusResponse, error)
	UploadBlob(context.Context, *UploadBlobRequest) (*UploadBlobResponse, error)
	UploadBlobStream(BlobService_UploadBlobStreamServer) error
	ReadBlobStream(*ReadBlobStreamRequest, BlobService_ReadBlobStreamServer) error
}

// UnimplementedBlobServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBlobServiceServer struct {
}

func (UnimplementedBlobServiceServer) GetBlobStatus(context.Context, *GetBlobStatusRequest) (*GetBlobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlobStatus not implemented")
}
func (UnimplementedBlobServiceServer) UploadBlob(context.Context, *UploadBlobRequest) (*UploadBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBlob not implemented")
}
func (UnimplementedBlobServiceServer) UploadBlobStream(BlobService_UploadBlobStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadBlobStream not implemented")
}
func (UnimplementedBlobServiceServer) ReadBlobStream(*ReadBlobStreamRequest, BlobService_ReadBlobStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ReadBlobStream not implemented")
}

// UnsafeBlobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServiceServer will
// result in compilation errors.
type UnsafeBlobServiceServer interface {
	mustEmbedUnimplementedBlobServiceServer()
}

func RegisterBlobServiceServer(s grpc.ServiceRegistrar, srv BlobServiceServer) {
	s.RegisterService(&BlobService_ServiceDesc, srv)
}

func _BlobService_GetBlobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).GetBlobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_GetBlobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).GetBlobStatus(ctx, req.(*GetBlobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_UploadBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).UploadBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_UploadBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).UploadBlob(ctx, req.(*UploadBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_UploadBlobStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BlobServiceServer).UploadBlobStream(&blobServiceUploadBlobStreamServer{stream})
}

type BlobService_UploadBlobStreamServer interface {
	SendAndClose(*UploadBlobResponse) error
	Recv() (*UploadBlobChunk, error)
	grpc.ServerStream
}

type blobServiceUploadBlobStreamServer struct {
	grpc.ServerStream
}

func (x *blobServiceUploadBlobStreamServer) SendAndClose(m *UploadBlobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *blobServiceUploadBlobStreamServer) Recv() (*UploadBlobChunk, error) {
	m := new(UploadBlobChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BlobService_ReadBlobStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadBlobStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).ReadBlobStream(m, &blobServiceReadBlobStreamServer{stream})
}

type BlobService_ReadBlobStreamServer interface {
	Send(*ReadBlobChunk) error
	grpc.ServerStream
}

type blobServiceReadBlobStreamServer struct {
	grpc.ServerStream
}

func (x *blobServiceReadBlobStreamServer) Send(m *ReadBlobChunk) error {
	return x.ServerStream.SendMsg(m)
}

// BlobService_ServiceDesc is the grpc.ServiceDesc for BlobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.BlobService",
	HandlerType: (*BlobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlobStatus",
			Handler:    _BlobService_GetBlobStatus_Handler,
		},
		{
			MethodName: "UploadBlob",
			Handler:    _BlobService_UploadBlob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadBlobStream",
			Handler:       _BlobService_UploadBlobStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReadBlobStream",
			Handler:       _BlobService_ReadBlobStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/core/v1/blob.proto",
}
