// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/core/v1/changeset.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Changeset struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthoringSlice        *SliceRef              `protobuf:"bytes,2,opt,name=authoring_slice,json=authoringSlice,proto3" json:"authoring_slice,omitempty"`
	Author                string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	TargetRef             string                 `protobuf:"bytes,4,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	BaseCommitId          string                 `protobuf:"bytes,5,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	Title                 string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Patchsets             []*Patchset            `protobuf:"bytes,8,rep,name=patchsets,proto3" json:"patchsets,omitempty"`
	CurrentPatchsetId     string                 `protobuf:"bytes,9,opt,name=current_patchset_id,json=currentPatchsetId,proto3" json:"current_patchset_id,omitempty"`
	CurrentPatchsetNumber int64                  `protobuf:"varint,10,opt,name=current_patchset_number,json=currentPatchsetNumber,proto3" json:"current_patchset_number,omitempty"`
	Status                string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	AffectedPaths         []string               `protobuf:"bytes,12,rep,name=affected_paths,json=affectedPaths,proto3" json:"affected_paths,omitempty"`
	SubmitRequirements    *SubmitRequirements    `protobuf:"bytes,13,opt,name=submit_requirements,json=submitRequirements,proto3" json:"submit_requirements,omitempty"`
	CommitId              string                 `protobuf:"bytes,14,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	PendingPublishId      string                 `protobuf:"bytes,15,opt,name=pending_publish_id,json=pendingPublishId,proto3" json:"pending_publish_id,omitempty"`
	Number                int64                  `protobuf:"varint,16,opt,name=number,proto3" json:"number,omitempty"`
	Handle                string                 `protobuf:"bytes,17,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Changeset) Reset() {
	*x = Changeset{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Changeset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changeset) ProtoMessage() {}

func (x *Changeset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changeset.ProtoReflect.Descriptor instead.
func (*Changeset) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{0}
}

func (x *Changeset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Changeset) GetAuthoringSlice() *SliceRef {
	if x != nil {
		return x.AuthoringSlice
	}
	return nil
}

func (x *Changeset) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Changeset) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *Changeset) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *Changeset) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Changeset) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Changeset) GetPatchsets() []*Patchset {
	if x != nil {
		return x.Patchsets
	}
	return nil
}

func (x *Changeset) GetCurrentPatchsetId() string {
	if x != nil {
		return x.CurrentPatchsetId
	}
	return ""
}

func (x *Changeset) GetCurrentPatchsetNumber() int64 {
	if x != nil {
		return x.CurrentPatchsetNumber
	}
	return 0
}

func (x *Changeset) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Changeset) GetAffectedPaths() []string {
	if x != nil {
		return x.AffectedPaths
	}
	return nil
}

func (x *Changeset) GetSubmitRequirements() *SubmitRequirements {
	if x != nil {
		return x.SubmitRequirements
	}
	return nil
}

func (x *Changeset) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *Changeset) GetPendingPublishId() string {
	if x != nil {
		return x.PendingPublishId
	}
	return ""
}

func (x *Changeset) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Changeset) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type Patchset struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ChangesetId        string                 `protobuf:"bytes,2,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	Number             int64                  `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	BaseCommitId       string                 `protobuf:"bytes,4,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	Author             string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ChangedPaths       []string               `protobuf:"bytes,7,rep,name=changed_paths,json=changedPaths,proto3" json:"changed_paths,omitempty"`
	FileEdits          []*FileEdit            `protobuf:"bytes,8,rep,name=file_edits,json=fileEdits,proto3" json:"file_edits,omitempty"`
	Coverage           []*PathCoverage        `protobuf:"bytes,9,rep,name=coverage,proto3" json:"coverage,omitempty"`
	SubmitRequirements *SubmitRequirements    `protobuf:"bytes,10,opt,name=submit_requirements,json=submitRequirements,proto3" json:"submit_requirements,omitempty"`
	PathBases          []*PathBase            `protobuf:"bytes,11,rep,name=path_bases,json=pathBases,proto3" json:"path_bases,omitempty"`
	ReadSet            []*PathSetEntry        `protobuf:"bytes,12,rep,name=read_set,json=readSet,proto3" json:"read_set,omitempty"`
	WriteSet           []*PathSetEntry        `protobuf:"bytes,13,rep,name=write_set,json=writeSet,proto3" json:"write_set,omitempty"`
	Handle             string                 `protobuf:"bytes,14,opt,name=handle,proto3" json:"handle,omitempty"`
	Conflicts          []*PatchsetConflict    `protobuf:"bytes,15,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Kind               string                 `protobuf:"bytes,16,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Patchset) Reset() {
	*x = Patchset{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patchset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patchset) ProtoMessage() {}

func (x *Patchset) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patchset.ProtoReflect.Descriptor instead.
func (*Patchset) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{1}
}

func (x *Patchset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patchset) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *Patchset) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Patchset) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *Patchset) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Patchset) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Patchset) GetChangedPaths() []string {
	if x != nil {
		return x.ChangedPaths
	}
	return nil
}

func (x *Patchset) GetFileEdits() []*FileEdit {
	if x != nil {
		return x.FileEdits
	}
	return nil
}

func (x *Patchset) GetCoverage() []*PathCoverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

func (x *Patchset) GetSubmitRequirements() *SubmitRequirements {
	if x != nil {
		return x.SubmitRequirements
	}
	return nil
}

func (x *Patchset) GetPathBases() []*PathBase {
	if x != nil {
		return x.PathBases
	}
	return nil
}

func (x *Patchset) GetReadSet() []*PathSetEntry {
	if x != nil {
		return x.ReadSet
	}
	return nil
}

func (x *Patchset) GetWriteSet() []*PathSetEntry {
	if x != nil {
		return x.WriteSet
	}
	return nil
}

func (x *Patchset) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *Patchset) GetConflicts() []*PatchsetConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *Patchset) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type FileEdit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	OldPath       string                 `protobuf:"bytes,3,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	BlobId        string                 `protobuf:"bytes,4,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	ContentHash   string                 `protobuf:"bytes,5,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	Mode          uint32                 `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEdit) Reset() {
	*x = FileEdit{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEdit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEdit) ProtoMessage() {}

func (x *FileEdit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEdit.ProtoReflect.Descriptor instead.
func (*FileEdit) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{2}
}

func (x *FileEdit) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *FileEdit) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEdit) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *FileEdit) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *FileEdit) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *FileEdit) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type PathCoverage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	CoveringSliceIds []string               `protobuf:"bytes,2,rep,name=covering_slice_ids,json=coveringSliceIds,proto3" json:"covering_slice_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PathCoverage) Reset() {
	*x = PathCoverage{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathCoverage) ProtoMessage() {}

func (x *PathCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathCoverage.ProtoReflect.Descriptor instead.
func (*PathCoverage) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{3}
}

func (x *PathCoverage) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathCoverage) GetCoveringSliceIds() []string {
	if x != nil {
		return x.CoveringSliceIds
	}
	return nil
}

type PathBase struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BaseCommitId     string                 `protobuf:"bytes,2,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	Exists           bool                   `protobuf:"varint,3,opt,name=exists,proto3" json:"exists,omitempty"`
	EntryKind        string                 `protobuf:"bytes,4,opt,name=entry_kind,json=entryKind,proto3" json:"entry_kind,omitempty"`
	Mode             uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	BlobId           string                 `protobuf:"bytes,6,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	ContentHash      string                 `protobuf:"bytes,7,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	TreeId           string                 `protobuf:"bytes,8,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	SymlinkTarget    string                 `protobuf:"bytes,9,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	EntryFingerprint string                 `protobuf:"bytes,10,opt,name=entry_fingerprint,json=entryFingerprint,proto3" json:"entry_fingerprint,omitempty"`
	Check            string                 `protobuf:"bytes,11,opt,name=check,proto3" json:"check,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PathBase) Reset() {
	*x = PathBase{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathBase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathBase) ProtoMessage() {}

func (x *PathBase) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathBase.ProtoReflect.Descriptor instead.
func (*PathBase) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{4}
}

func (x *PathBase) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathBase) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *PathBase) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *PathBase) GetEntryKind() string {
	if x != nil {
		return x.EntryKind
	}
	return ""
}

func (x *PathBase) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *PathBase) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *PathBase) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

func (x *PathBase) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *PathBase) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

func (x *PathBase) GetEntryFingerprint() string {
	if x != nil {
		return x.EntryFingerprint
	}
	return ""
}

func (x *PathBase) GetCheck() string {
	if x != nil {
		return x.Check
	}
	return ""
}

type PatchsetConflict struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Path              string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ConflictClass     string                 `protobuf:"bytes,2,opt,name=conflict_class,json=conflictClass,proto3" json:"conflict_class,omitempty"`
	OldBaseCommitId   string                 `protobuf:"bytes,3,opt,name=old_base_commit_id,json=oldBaseCommitId,proto3" json:"old_base_commit_id,omitempty"`
	NewBaseCommitId   string                 `protobuf:"bytes,4,opt,name=new_base_commit_id,json=newBaseCommitId,proto3" json:"new_base_commit_id,omitempty"`
	BaseFingerprint   string                 `protobuf:"bytes,5,opt,name=base_fingerprint,json=baseFingerprint,proto3" json:"base_fingerprint,omitempty"`
	LocalFingerprint  string                 `protobuf:"bytes,6,opt,name=local_fingerprint,json=localFingerprint,proto3" json:"local_fingerprint,omitempty"`
	RemoteFingerprint string                 `protobuf:"bytes,7,opt,name=remote_fingerprint,json=remoteFingerprint,proto3" json:"remote_fingerprint,omitempty"`
	BaseContentHash   string                 `protobuf:"bytes,8,opt,name=base_content_hash,json=baseContentHash,proto3" json:"base_content_hash,omitempty"`
	LocalContentHash  string                 `protobuf:"bytes,9,opt,name=local_content_hash,json=localContentHash,proto3" json:"local_content_hash,omitempty"`
	RemoteContentHash string                 `protobuf:"bytes,10,opt,name=remote_content_hash,json=remoteContentHash,proto3" json:"remote_content_hash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PatchsetConflict) Reset() {
	*x = PatchsetConflict{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchsetConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchsetConflict) ProtoMessage() {}

func (x *PatchsetConflict) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchsetConflict.ProtoReflect.Descriptor instead.
func (*PatchsetConflict) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{5}
}

func (x *PatchsetConflict) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PatchsetConflict) GetConflictClass() string {
	if x != nil {
		return x.ConflictClass
	}
	return ""
}

func (x *PatchsetConflict) GetOldBaseCommitId() string {
	if x != nil {
		return x.OldBaseCommitId
	}
	return ""
}

func (x *PatchsetConflict) GetNewBaseCommitId() string {
	if x != nil {
		return x.NewBaseCommitId
	}
	return ""
}

func (x *PatchsetConflict) GetBaseFingerprint() string {
	if x != nil {
		return x.BaseFingerprint
	}
	return ""
}

func (x *PatchsetConflict) GetLocalFingerprint() string {
	if x != nil {
		return x.LocalFingerprint
	}
	return ""
}

func (x *PatchsetConflict) GetRemoteFingerprint() string {
	if x != nil {
		return x.RemoteFingerprint
	}
	return ""
}

func (x *PatchsetConflict) GetBaseContentHash() string {
	if x != nil {
		return x.BaseContentHash
	}
	return ""
}

func (x *PatchsetConflict) GetLocalContentHash() string {
	if x != nil {
		return x.LocalContentHash
	}
	return ""
}

func (x *PatchsetConflict) GetRemoteContentHash() string {
	if x != nil {
		return x.RemoteContentHash
	}
	return ""
}

type PathSetEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathSetEntry) Reset() {
	*x = PathSetEntry{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathSetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathSetEntry) ProtoMessage() {}

func (x *PathSetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathSetEntry.ProtoReflect.Descriptor instead.
func (*PathSetEntry) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{6}
}

func (x *PathSetEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathSetEntry) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

type SubmitRequirements struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	RequiredApprovals         []string               `protobuf:"bytes,1,rep,name=required_approvals,json=requiredApprovals,proto3" json:"required_approvals,omitempty"`
	RequiredChecks            []string               `protobuf:"bytes,2,rep,name=required_checks,json=requiredChecks,proto3" json:"required_checks,omitempty"`
	PathLockIds               []string               `protobuf:"bytes,3,rep,name=path_lock_ids,json=pathLockIds,proto3" json:"path_lock_ids,omitempty"`
	SourceSliceDefinitionHash string                 `protobuf:"bytes,4,opt,name=source_slice_definition_hash,json=sourceSliceDefinitionHash,proto3" json:"source_slice_definition_hash,omitempty"`
	SourcePathLockSetHash     string                 `protobuf:"bytes,5,opt,name=source_path_lock_set_hash,json=sourcePathLockSetHash,proto3" json:"source_path_lock_set_hash,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SubmitRequirements) Reset() {
	*x = SubmitRequirements{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequirements) ProtoMessage() {}

func (x *SubmitRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequirements.ProtoReflect.Descriptor instead.
func (*SubmitRequirements) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{7}
}

func (x *SubmitRequirements) GetRequiredApprovals() []string {
	if x != nil {
		return x.RequiredApprovals
	}
	return nil
}

func (x *SubmitRequirements) GetRequiredChecks() []string {
	if x != nil {
		return x.RequiredChecks
	}
	return nil
}

func (x *SubmitRequirements) GetPathLockIds() []string {
	if x != nil {
		return x.PathLockIds
	}
	return nil
}

func (x *SubmitRequirements) GetSourceSliceDefinitionHash() string {
	if x != nil {
		return x.SourceSliceDefinitionHash
	}
	return ""
}

func (x *SubmitRequirements) GetSourcePathLockSetHash() string {
	if x != nil {
		return x.SourcePathLockSetHash
	}
	return ""
}

type CreateChangesetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthoringSlice *SliceRef              `protobuf:"bytes,1,opt,name=authoring_slice,json=authoringSlice,proto3" json:"authoring_slice,omitempty"`
	TargetRef      string                 `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	BaseCommitId   string                 `protobuf:"bytes,3,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateChangesetRequest) Reset() {
	*x = CreateChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChangesetRequest) ProtoMessage() {}

func (x *CreateChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChangesetRequest.ProtoReflect.Descriptor instead.
func (*CreateChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{8}
}

func (x *CreateChangesetRequest) GetAuthoringSlice() *SliceRef {
	if x != nil {
		return x.AuthoringSlice
	}
	return nil
}

func (x *CreateChangesetRequest) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *CreateChangesetRequest) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *CreateChangesetRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateChangesetRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangesetRequest) Reset() {
	*x = GetChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangesetRequest) ProtoMessage() {}

func (x *GetChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangesetRequest.ProtoReflect.Descriptor instead.
func (*GetChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{9}
}

func (x *GetChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

type ListChangesetsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuthoringSlice *SliceRef              `protobuf:"bytes,1,opt,name=authoring_slice,json=authoringSlice,proto3" json:"authoring_slice,omitempty"`
	Status         string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListChangesetsRequest) Reset() {
	*x = ListChangesetsRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesetsRequest) ProtoMessage() {}

func (x *ListChangesetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesetsRequest.ProtoReflect.Descriptor instead.
func (*ListChangesetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{10}
}

func (x *ListChangesetsRequest) GetAuthoringSlice() *SliceRef {
	if x != nil {
		return x.AuthoringSlice
	}
	return nil
}

func (x *ListChangesetsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListChangesetsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListChangesetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Changesets    []*Changeset           `protobuf:"bytes,1,rep,name=changesets,proto3" json:"changesets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChangesetsResponse) Reset() {
	*x = ListChangesetsResponse{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChangesetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChangesetsResponse) ProtoMessage() {}

func (x *ListChangesetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChangesetsResponse.ProtoReflect.Descriptor instead.
func (*ListChangesetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{11}
}

func (x *ListChangesetsResponse) GetChangesets() []*Changeset {
	if x != nil {
		return x.Changesets
	}
	return nil
}

type DiffChangesetRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	// patchset, from_patchset, and to_patchset accept a patchset number encoded as
	// a string, an exact patchset handle, or a canonical patchset id.
	Patchset      string `protobuf:"bytes,2,opt,name=patchset,proto3" json:"patchset,omitempty"`
	FromPatchset  string `protobuf:"bytes,3,opt,name=from_patchset,json=fromPatchset,proto3" json:"from_patchset,omitempty"`
	ToPatchset    string `protobuf:"bytes,4,opt,name=to_patchset,json=toPatchset,proto3" json:"to_patchset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiffChangesetRequest) Reset() {
	*x = DiffChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffChangesetRequest) ProtoMessage() {}

func (x *DiffChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffChangesetRequest.ProtoReflect.Descriptor instead.
func (*DiffChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{12}
}

func (x *DiffChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *DiffChangesetRequest) GetPatchset() string {
	if x != nil {
		return x.Patchset
	}
	return ""
}

func (x *DiffChangesetRequest) GetFromPatchset() string {
	if x != nil {
		return x.FromPatchset
	}
	return ""
}

func (x *DiffChangesetRequest) GetToPatchset() string {
	if x != nil {
		return x.ToPatchset
	}
	return ""
}

type DiffChangesetResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId        string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	FromPatchsetId     string                 `protobuf:"bytes,2,opt,name=from_patchset_id,json=fromPatchsetId,proto3" json:"from_patchset_id,omitempty"`
	ToPatchsetId       string                 `protobuf:"bytes,3,opt,name=to_patchset_id,json=toPatchsetId,proto3" json:"to_patchset_id,omitempty"`
	ChangedPaths       []string               `protobuf:"bytes,4,rep,name=changed_paths,json=changedPaths,proto3" json:"changed_paths,omitempty"`
	Diff               string                 `protobuf:"bytes,5,opt,name=diff,proto3" json:"diff,omitempty"`
	ChangesetHandle    string                 `protobuf:"bytes,6,opt,name=changeset_handle,json=changesetHandle,proto3" json:"changeset_handle,omitempty"`
	FromPatchsetHandle string                 `protobuf:"bytes,7,opt,name=from_patchset_handle,json=fromPatchsetHandle,proto3" json:"from_patchset_handle,omitempty"`
	ToPatchsetHandle   string                 `protobuf:"bytes,8,opt,name=to_patchset_handle,json=toPatchsetHandle,proto3" json:"to_patchset_handle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DiffChangesetResponse) Reset() {
	*x = DiffChangesetResponse{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffChangesetResponse) ProtoMessage() {}

func (x *DiffChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffChangesetResponse.ProtoReflect.Descriptor instead.
func (*DiffChangesetResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{13}
}

func (x *DiffChangesetResponse) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *DiffChangesetResponse) GetFromPatchsetId() string {
	if x != nil {
		return x.FromPatchsetId
	}
	return ""
}

func (x *DiffChangesetResponse) GetToPatchsetId() string {
	if x != nil {
		return x.ToPatchsetId
	}
	return ""
}

func (x *DiffChangesetResponse) GetChangedPaths() []string {
	if x != nil {
		return x.ChangedPaths
	}
	return nil
}

func (x *DiffChangesetResponse) GetDiff() string {
	if x != nil {
		return x.Diff
	}
	return ""
}

func (x *DiffChangesetResponse) GetChangesetHandle() string {
	if x != nil {
		return x.ChangesetHandle
	}
	return ""
}

func (x *DiffChangesetResponse) GetFromPatchsetHandle() string {
	if x != nil {
		return x.FromPatchsetHandle
	}
	return ""
}

func (x *DiffChangesetResponse) GetToPatchsetHandle() string {
	if x != nil {
		return x.ToPatchsetHandle
	}
	return ""
}

type UpdateChangesetRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId               string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	ExpectedCurrentPatchsetId string                 `protobuf:"bytes,2,opt,name=expected_current_patchset_id,json=expectedCurrentPatchsetId,proto3" json:"expected_current_patchset_id,omitempty"`
	BaseCommitId              string                 `protobuf:"bytes,3,opt,name=base_commit_id,json=baseCommitId,proto3" json:"base_commit_id,omitempty"`
	FileEdits                 []*FileEdit            `protobuf:"bytes,4,rep,name=file_edits,json=fileEdits,proto3" json:"file_edits,omitempty"`
	Conflicts                 []*PatchsetConflict    `protobuf:"bytes,5,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	PatchsetKind              string                 `protobuf:"bytes,6,opt,name=patchset_kind,json=patchsetKind,proto3" json:"patchset_kind,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *UpdateChangesetRequest) Reset() {
	*x = UpdateChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChangesetRequest) ProtoMessage() {}

func (x *UpdateChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChangesetRequest.ProtoReflect.Descriptor instead.
func (*UpdateChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *UpdateChangesetRequest) GetExpectedCurrentPatchsetId() string {
	if x != nil {
		return x.ExpectedCurrentPatchsetId
	}
	return ""
}

func (x *UpdateChangesetRequest) GetBaseCommitId() string {
	if x != nil {
		return x.BaseCommitId
	}
	return ""
}

func (x *UpdateChangesetRequest) GetFileEdits() []*FileEdit {
	if x != nil {
		return x.FileEdits
	}
	return nil
}

func (x *UpdateChangesetRequest) GetConflicts() []*PatchsetConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *UpdateChangesetRequest) GetPatchsetKind() string {
	if x != nil {
		return x.PatchsetKind
	}
	return ""
}

type SubmitChangesetRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId               string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	ExpectedCurrentPatchsetId string                 `protobuf:"bytes,2,opt,name=expected_current_patchset_id,json=expectedCurrentPatchsetId,proto3" json:"expected_current_patchset_id,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SubmitChangesetRequest) Reset() {
	*x = SubmitChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitChangesetRequest) ProtoMessage() {}

func (x *SubmitChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitChangesetRequest.ProtoReflect.Descriptor instead.
func (*SubmitChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{15}
}

func (x *SubmitChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *SubmitChangesetRequest) GetExpectedCurrentPatchsetId() string {
	if x != nil {
		return x.ExpectedCurrentPatchsetId
	}
	return ""
}

type SubmitChangesetResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CommitId         string                 `protobuf:"bytes,1,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	TargetRef        string                 `protobuf:"bytes,2,opt,name=target_ref,json=targetRef,proto3" json:"target_ref,omitempty"`
	NewRefCommitId   string                 `protobuf:"bytes,3,opt,name=new_ref_commit_id,json=newRefCommitId,proto3" json:"new_ref_commit_id,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	PendingPublishId string                 `protobuf:"bytes,5,opt,name=pending_publish_id,json=pendingPublishId,proto3" json:"pending_publish_id,omitempty"`
	ChangesetHandle  string                 `protobuf:"bytes,6,opt,name=changeset_handle,json=changesetHandle,proto3" json:"changeset_handle,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitChangesetResponse) Reset() {
	*x = SubmitChangesetResponse{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitChangesetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitChangesetResponse) ProtoMessage() {}

func (x *SubmitChangesetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitChangesetResponse.ProtoReflect.Descriptor instead.
func (*SubmitChangesetResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{16}
}

func (x *SubmitChangesetResponse) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *SubmitChangesetResponse) GetTargetRef() string {
	if x != nil {
		return x.TargetRef
	}
	return ""
}

func (x *SubmitChangesetResponse) GetNewRefCommitId() string {
	if x != nil {
		return x.NewRefCommitId
	}
	return ""
}

func (x *SubmitChangesetResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubmitChangesetResponse) GetPendingPublishId() string {
	if x != nil {
		return x.PendingPublishId
	}
	return ""
}

func (x *SubmitChangesetResponse) GetChangesetHandle() string {
	if x != nil {
		return x.ChangesetHandle
	}
	return ""
}

type AbandonChangesetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangesetId   string                 `protobuf:"bytes,1,opt,name=changeset_id,json=changesetId,proto3" json:"changeset_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbandonChangesetRequest) Reset() {
	*x = AbandonChangesetRequest{}
	mi := &file_proto_core_v1_changeset_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbandonChangesetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonChangesetRequest) ProtoMessage() {}

func (x *AbandonChangesetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_changeset_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonChangesetRequest.ProtoReflect.Descriptor instead.
func (*AbandonChangesetRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_changeset_proto_rawDescGZIP(), []int{17}
}

func (x *AbandonChangesetRequest) GetChangesetId() string {
	if x != nil {
		return x.ChangesetId
	}
	return ""
}

func (x *AbandonChangesetRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_proto_core_v1_changeset_proto protoreflect.FileDescriptor

const file_proto_core_v1_changeset_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/core/v1/changeset.proto\x12\x10gitslice.core.v1\x1a\x1aproto/core/v1/common.proto\"\xa8\x05\n" +
	"\tChangeset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12C\n" +
	"\x0fauthoring_slice\x18\x02 \x01(\v2\x1a.gitslice.core.v1.SliceRefR\x0eauthoringSlice\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x04 \x01(\tR\ttargetRef\x12$\n" +
	"\x0ebase_commit_id\x18\x05 \x01(\tR\fbaseCommitId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x128\n" +
	"\tpatchsets\x18\b \x03(\v2\x1a.gitslice.core.v1.PatchsetR\tpatchsets\x12.\n" +
	"\x13current_patchset_id\x18\t \x01(\tR\x11currentPatchsetId\x126\n" +
	"\x17current_patchset_number\x18\n" +
	" \x01(\x03R\x15currentPatchsetNumber\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12%\n" +
	"\x0eaffected_paths\x18\f \x03(\tR\raffectedPaths\x12U\n" +
	"\x13submit_requirements\x18\r \x01(\v2$.gitslice.core.v1.SubmitRequirementsR\x12submitRequirements\x12\x1b\n" +
	"\tcommit_id\x18\x0e \x01(\tR\bcommitId\x12,\n" +
	"\x12pending_publish_id\x18\x0f \x01(\tR\x10pendingPublishId\x12\x16\n" +
	"\x06number\x18\x10 \x01(\x03R\x06number\x12\x16\n" +
	"\x06handle\x18\x11 \x01(\tR\x06handle\"\xc6\x05\n" +
	"\bPatchset\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fchangeset_id\x18\x02 \x01(\tR\vchangesetId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\x03R\x06number\x12$\n" +
	"\x0ebase_commit_id\x18\x04 \x01(\tR\fbaseCommitId\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12#\n" +
	"\rchanged_paths\x18\a \x03(\tR\fchangedPaths\x129\n" +
	"\n" +
	"file_edits\x18\b \x03(\v2\x1a.gitslice.core.v1.FileEditR\tfileEdits\x12:\n" +
	"\bcoverage\x18\t \x03(\v2\x1e.gitslice.core.v1.PathCoverageR\bcoverage\x12U\n" +
	"\x13submit_requirements\x18\n" +
	" \x01(\v2$.gitslice.core.v1.SubmitRequirementsR\x12submitRequirements\x129\n" +
	"\n" +
	"path_bases\x18\v \x03(\v2\x1a.gitslice.core.v1.PathBaseR\tpathBases\x129\n" +
	"\bread_set\x18\f \x03(\v2\x1e.gitslice.core.v1.PathSetEntryR\areadSet\x12;\n" +
	"\twrite_set\x18\r \x03(\v2\x1e.gitslice.core.v1.PathSetEntryR\bwriteSet\x12\x16\n" +
	"\x06handle\x18\x0e \x01(\tR\x06handle\x12@\n" +
	"\tconflicts\x18\x0f \x03(\v2\".gitslice.core.v1.PatchsetConflictR\tconflicts\x12\x12\n" +
	"\x04kind\x18\x10 \x01(\tR\x04kind\"\x99\x01\n" +
	"\bFileEdit\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x19\n" +
	"\bold_path\x18\x03 \x01(\tR\aoldPath\x12\x17\n" +
	"\ablob_id\x18\x04 \x01(\tR\x06blobId\x12!\n" +
	"\fcontent_hash\x18\x05 \x01(\tR\vcontentHash\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\rR\x04mode\"P\n" +
	"\fPathCoverage\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12,\n" +
	"\x12covering_slice_ids\x18\x02 \x03(\tR\x10coveringSliceIds\"\xce\x02\n" +
	"\bPathBase\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12$\n" +
	"\x0ebase_commit_id\x18\x02 \x01(\tR\fbaseCommitId\x12\x16\n" +
	"\x06exists\x18\x03 \x01(\bR\x06exists\x12\x1d\n" +
	"\n" +
	"entry_kind\x18\x04 \x01(\tR\tentryKind\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\x12\x17\n" +
	"\ablob_id\x18\x06 \x01(\tR\x06blobId\x12!\n" +
	"\fcontent_hash\x18\a \x01(\tR\vcontentHash\x12\x17\n" +
	"\atree_id\x18\b \x01(\tR\x06treeId\x12%\n" +
	"\x0esymlink_target\x18\t \x01(\tR\rsymlinkTarget\x12+\n" +
	"\x11entry_fingerprint\x18\n" +
	" \x01(\tR\x10entryFingerprint\x12\x14\n" +
	"\x05check\x18\v \x01(\tR\x05check\"\xb8\x03\n" +
	"\x10PatchsetConflict\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12%\n" +
	"\x0econflict_class\x18\x02 \x01(\tR\rconflictClass\x12+\n" +
	"\x12old_base_commit_id\x18\x03 \x01(\tR\x0foldBaseCommitId\x12+\n" +
	"\x12new_base_commit_id\x18\x04 \x01(\tR\x0fnewBaseCommitId\x12)\n" +
	"\x10base_fingerprint\x18\x05 \x01(\tR\x0fbaseFingerprint\x12+\n" +
	"\x11local_fingerprint\x18\x06 \x01(\tR\x10localFingerprint\x12-\n" +
	"\x12remote_fingerprint\x18\a \x01(\tR\x11remoteFingerprint\x12*\n" +
	"\x11base_content_hash\x18\b \x01(\tR\x0fbaseContentHash\x12,\n" +
	"\x12local_content_hash\x18\t \x01(\tR\x10localContentHash\x12.\n" +
	"\x13remote_content_hash\x18\n" +
	" \x01(\tR\x11remoteContentHash\"@\n" +
	"\fPathSetEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\x8b\x02\n" +
	"\x12SubmitRequirements\x12-\n" +
	"\x12required_approvals\x18\x01 \x03(\tR\x11requiredApprovals\x12'\n" +
	"\x0frequired_checks\x18\x02 \x03(\tR\x0erequiredChecks\x12\"\n" +
	"\rpath_lock_ids\x18\x03 \x03(\tR\vpathLockIds\x12?\n" +
	"\x1csource_slice_definition_hash\x18\x04 \x01(\tR\x19sourceSliceDefinitionHash\x128\n" +
	"\x19source_path_lock_set_hash\x18\x05 \x01(\tR\x15sourcePathLockSetHash\"\xda\x01\n" +
	"\x16CreateChangesetRequest\x12C\n" +
	"\x0fauthoring_slice\x18\x01 \x01(\v2\x1a.gitslice.core.v1.SliceRefR\x0eauthoringSlice\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12$\n" +
	"\x0ebase_commit_id\x18\x03 \x01(\tR\fbaseCommitId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"8\n" +
	"\x13GetChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\"\x8a\x01\n" +
	"\x15ListChangesetsRequest\x12C\n" +
	"\x0fauthoring_slice\x18\x01 \x01(\v2\x1a.gitslice.core.v1.SliceRefR\x0eauthoringSlice\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"U\n" +
	"\x16ListChangesetsResponse\x12;\n" +
	"\n" +
	"changesets\x18\x01 \x03(\v2\x1b.gitslice.core.v1.ChangesetR\n" +
	"changesets\"\x9b\x01\n" +
	"\x14DiffChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12\x1a\n" +
	"\bpatchset\x18\x02 \x01(\tR\bpatchset\x12#\n" +
	"\rfrom_patchset\x18\x03 \x01(\tR\ffromPatchset\x12\x1f\n" +
	"\vto_patchset\x18\x04 \x01(\tR\n" +
	"toPatchset\"\xce\x02\n" +
	"\x15DiffChangesetResponse\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12(\n" +
	"\x10from_patchset_id\x18\x02 \x01(\tR\x0efromPatchsetId\x12$\n" +
	"\x0eto_patchset_id\x18\x03 \x01(\tR\ftoPatchsetId\x12#\n" +
	"\rchanged_paths\x18\x04 \x03(\tR\fchangedPaths\x12\x12\n" +
	"\x04diff\x18\x05 \x01(\tR\x04diff\x12)\n" +
	"\x10changeset_handle\x18\x06 \x01(\tR\x0fchangesetHandle\x120\n" +
	"\x14from_patchset_handle\x18\a \x01(\tR\x12fromPatchsetHandle\x12,\n" +
	"\x12to_patchset_handle\x18\b \x01(\tR\x10toPatchsetHandle\"\xc4\x02\n" +
	"\x16UpdateChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12?\n" +
	"\x1cexpected_current_patchset_id\x18\x02 \x01(\tR\x19expectedCurrentPatchsetId\x12$\n" +
	"\x0ebase_commit_id\x18\x03 \x01(\tR\fbaseCommitId\x129\n" +
	"\n" +
	"file_edits\x18\x04 \x03(\v2\x1a.gitslice.core.v1.FileEditR\tfileEdits\x12@\n" +
	"\tconflicts\x18\x05 \x03(\v2\".gitslice.core.v1.PatchsetConflictR\tconflicts\x12#\n" +
	"\rpatchset_kind\x18\x06 \x01(\tR\fpatchsetKind\"|\n" +
	"\x16SubmitChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12?\n" +
	"\x1cexpected_current_patchset_id\x18\x02 \x01(\tR\x19expectedCurrentPatchsetId\"\xf1\x01\n" +
	"\x17SubmitChangesetResponse\x12\x1b\n" +
	"\tcommit_id\x18\x01 \x01(\tR\bcommitId\x12\x1d\n" +
	"\n" +
	"target_ref\x18\x02 \x01(\tR\ttargetRef\x12)\n" +
	"\x11new_ref_commit_id\x18\x03 \x01(\tR\x0enewRefCommitId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12,\n" +
	"\x12pending_publish_id\x18\x05 \x01(\tR\x10pendingPublishId\x12)\n" +
	"\x10changeset_handle\x18\x06 \x01(\tR\x0fchangesetHandle\"T\n" +
	"\x17AbandonChangesetRequest\x12!\n" +
	"\fchangeset_id\x18\x01 \x01(\tR\vchangesetId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xa0\x05\n" +
	"\x10ChangesetService\x12X\n" +
	"\x0fCreateChangeset\x12(.gitslice.core.v1.CreateChangesetRequest\x1a\x1b.gitslice.core.v1.Changeset\x12R\n" +
	"\fGetChangeset\x12%.gitslice.core.v1.GetChangesetRequest\x1a\x1b.gitslice.core.v1.Changeset\x12c\n" +
	"\x0eListChangesets\x12'.gitslice.core.v1.ListChangesetsRequest\x1a(.gitslice.core.v1.ListChangesetsResponse\x12`\n" +
	"\rDiffChangeset\x12&.gitslice.core.v1.DiffChangesetRequest\x1a'.gitslice.core.v1.DiffChangesetResponse\x12W\n" +
	"\x0fUpdateChangeset\x12(.gitslice.core.v1.UpdateChangesetRequest\x1a\x1a.gitslice.core.v1.Patchset\x12f\n" +
	"\x0fSubmitChangeset\x12(.gitslice.core.v1.SubmitChangesetRequest\x1a).gitslice.core.v1.SubmitChangesetResponse\x12V\n" +
	"\x10AbandonChangeset\x12).gitslice.core.v1.AbandonChangesetRequest\x1a\x17.gitslice.core.v1.EmptyB6Z4github.com/gitslice-io/gitslice/proto/core/v1;corev1b\x06proto3"

var (
	file_proto_core_v1_changeset_proto_rawDescOnce sync.Once
	file_proto_core_v1_changeset_proto_rawDescData []byte
)

func file_proto_core_v1_changeset_proto_rawDescGZIP() []byte {
	file_proto_core_v1_changeset_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_changeset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_changeset_proto_rawDesc), len(file_proto_core_v1_changeset_proto_rawDesc)))
	})
	return file_proto_core_v1_changeset_proto_rawDescData
}

var file_proto_core_v1_changeset_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_core_v1_changeset_proto_goTypes = []any{
	(*Changeset)(nil),               // 0: gitslice.core.v1.Changeset
	(*Patchset)(nil),                // 1: gitslice.core.v1.Patchset
	(*FileEdit)(nil),                // 2: gitslice.core.v1.FileEdit
	(*PathCoverage)(nil),            // 3: gitslice.core.v1.PathCoverage
	(*PathBase)(nil),                // 4: gitslice.core.v1.PathBase
	(*PatchsetConflict)(nil),        // 5: gitslice.core.v1.PatchsetConflict
	(*PathSetEntry)(nil),            // 6: gitslice.core.v1.PathSetEntry
	(*SubmitRequirements)(nil),      // 7: gitslice.core.v1.SubmitRequirements
	(*CreateChangesetRequest)(nil),  // 8: gitslice.core.v1.CreateChangesetRequest
	(*GetChangesetRequest)(nil),     // 9: gitslice.core.v1.GetChangesetRequest
	(*ListChangesetsRequest)(nil),   // 10: gitslice.core.v1.ListChangesetsRequest
	(*ListChangesetsResponse)(nil),  // 11: gitslice.core.v1.ListChangesetsResponse
	(*DiffChangesetRequest)(nil),    // 12: gitslice.core.v1.DiffChangesetRequest
	(*DiffChangesetResponse)(nil),   // 13: gitslice.core.v1.DiffChangesetResponse
	(*UpdateChangesetRequest)(nil),  // 14: gitslice.core.v1.UpdateChangesetRequest
	(*SubmitChangesetRequest)(nil),  // 15: gitslice.core.v1.SubmitChangesetRequest
	(*SubmitChangesetResponse)(nil), // 16: gitslice.core.v1.SubmitChangesetResponse
	(*AbandonChangesetRequest)(nil), // 17: gitslice.core.v1.AbandonChangesetRequest
	(*SliceRef)(nil),                // 18: gitslice.core.v1.SliceRef
	(*Empty)(nil),                   // 19: gitslice.core.v1.Empty
}
var file_proto_core_v1_changeset_proto_depIdxs = []int32{
	18, // 0: gitslice.core.v1.Changeset.authoring_slice:type_name -> gitslice.core.v1.SliceRef
	1,  // 1: gitslice.core.v1.Changeset.patchsets:type_name -> gitslice.core.v1.Patchset
	7,  // 2: gitslice.core.v1.Changeset.submit_requirements:type_name -> gitslice.core.v1.SubmitRequirements
	2,  // 3: gitslice.core.v1.Patchset.file_edits:type_name -> gitslice.core.v1.FileEdit
	3,  // 4: gitslice.core.v1.Patchset.coverage:type_name -> gitslice.core.v1.PathCoverage
	7,  // 5: gitslice.core.v1.Patchset.submit_requirements:type_name -> gitslice.core.v1.SubmitRequirements
	4,  // 6: gitslice.core.v1.Patchset.path_bases:type_name -> gitslice.core.v1.PathBase
	6,  // 7: gitslice.core.v1.Patchset.read_set:type_name -> gitslice.core.v1.PathSetEntry
	6,  // 8: gitslice.core.v1.Patchset.write_set:type_name -> gitslice.core.v1.PathSetEntry
	5,  // 9: gitslice.core.v1.Patchset.conflicts:type_name -> gitslice.core.v1.PatchsetConflict
	18, // 10: gitslice.core.v1.CreateChangesetRequest.authoring_slice:type_name -> gitslice.core.v1.SliceRef
	18, // 11: gitslice.core.v1.ListChangesetsRequest.authoring_slice:type_name -> gitslice.core.v1.SliceRef
	0,  // 12: gitslice.core.v1.ListChangesetsResponse.changesets:type_name -> gitslice.core.v1.Changeset
	2,  // 13: gitslice.core.v1.UpdateChangesetRequest.file_edits:type_name -> gitslice.core.v1.FileEdit
	5,  // 14: gitslice.core.v1.UpdateChangesetRequest.conflicts:type_name -> gitslice.core.v1.PatchsetConflict
	8,  // 15: gitslice.core.v1.ChangesetService.CreateChangeset:input_type -> gitslice.core.v1.CreateChangesetRequest
	9,  // 16: gitslice.core.v1.ChangesetService.GetChangeset:input_type -> gitslice.core.v1.GetChangesetRequest
	10, // 17: gitslice.core.v1.ChangesetService.ListChangesets:input_type -> gitslice.core.v1.ListChangesetsRequest
	12, // 18: gitslice.core.v1.ChangesetService.DiffChangeset:input_type -> gitslice.core.v1.DiffChangesetRequest
	14, // 19: gitslice.core.v1.ChangesetService.UpdateChangeset:input_type -> gitslice.core.v1.UpdateChangesetRequest
	15, // 20: gitslice.core.v1.ChangesetService.SubmitChangeset:input_type -> gitslice.core.v1.SubmitChangesetRequest
	17, // 21: gitslice.core.v1.ChangesetService.AbandonChangeset:input_type -> gitslice.core.v1.AbandonChangesetRequest
	0,  // 22: gitslice.core.v1.ChangesetService.CreateChangeset:output_type -> gitslice.core.v1.Changeset
	0,  // 23: gitslice.core.v1.ChangesetService.GetChangeset:output_type -> gitslice.core.v1.Changeset
	11, // 24: gitslice.core.v1.ChangesetService.ListChangesets:output_type -> gitslice.core.v1.ListChangesetsResponse
	13, // 25: gitslice.core.v1.ChangesetService.DiffChangeset:output_type -> gitslice.core.v1.DiffChangesetResponse
	1,  // 26: gitslice.core.v1.ChangesetService.UpdateChangeset:output_type -> gitslice.core.v1.Patchset
	16, // 27: gitslice.core.v1.ChangesetService.SubmitChangeset:output_type -> gitslice.core.v1.SubmitChangesetResponse
	19, // 28: gitslice.core.v1.ChangesetService.AbandonChangeset:output_type -> gitslice.core.v1.Empty
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_core_v1_changeset_proto_init() }
func file_proto_core_v1_changeset_proto_init() {
	if File_proto_core_v1_changeset_proto != nil {
		return
	}
	file_proto_core_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_changeset_proto_rawDesc), len(file_proto_core_v1_changeset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_changeset_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_changeset_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_changeset_proto_msgTypes,
	}.Build()
	File_proto_core_v1_changeset_proto = out.File
	file_proto_core_v1_changeset_proto_goTypes = nil
	file_proto_core_v1_changeset_proto_depIdxs = nil
}
