// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/core/v1/common.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryKind int32

const (
	EntryKind_ENTRY_KIND_UNSPECIFIED EntryKind = 0
	EntryKind_ENTRY_KIND_FILE        EntryKind = 1
	EntryKind_ENTRY_KIND_DIRECTORY   EntryKind = 2
	EntryKind_ENTRY_KIND_SYMLINK     EntryKind = 3
)

// Enum value maps for EntryKind.
var (
	EntryKind_name = map[int32]string{
		0: "ENTRY_KIND_UNSPECIFIED",
		1: "ENTRY_KIND_FILE",
		2: "ENTRY_KIND_DIRECTORY",
		3: "ENTRY_KIND_SYMLINK",
	}
	EntryKind_value = map[string]int32{
		"ENTRY_KIND_UNSPECIFIED": 0,
		"ENTRY_KIND_FILE":        1,
		"ENTRY_KIND_DIRECTORY":   2,
		"ENTRY_KIND_SYMLINK":     3,
	}
)

func (x EntryKind) Enum() *EntryKind {
	p := new(EntryKind)
	*p = x
	return p
}

func (x EntryKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntryKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_core_v1_common_proto_enumTypes[0].Descriptor()
}

func (EntryKind) Type() protoreflect.EnumType {
	return &file_proto_core_v1_common_proto_enumTypes[0]
}

func (x EntryKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntryKind.Descriptor instead.
func (EntryKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_core_v1_common_proto_rawDescGZIP(), []int{0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_core_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_common_proto_rawDescGZIP(), []int{0}
}

type SliceRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Slice         string                 `protobuf:"bytes,2,opt,name=slice,proto3" json:"slice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceRef) Reset() {
	*x = SliceRef{}
	mi := &file_proto_core_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceRef) ProtoMessage() {}

func (x *SliceRef) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceRef.ProtoReflect.Descriptor instead.
func (*SliceRef) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *SliceRef) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *SliceRef) GetSlice() string {
	if x != nil {
		return x.Slice
	}
	return ""
}

type TreeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          EntryKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=gitslice.core.v1.EntryKind" json:"kind,omitempty"`
	Mode          uint32                 `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	TreeId        string                 `protobuf:"bytes,5,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BlobId        string                 `protobuf:"bytes,6,opt,name=blob_id,json=blobId,proto3" json:"blob_id,omitempty"`
	SymlinkTarget string                 `protobuf:"bytes,7,opt,name=symlink_target,json=symlinkTarget,proto3" json:"symlink_target,omitempty"`
	Size          int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	ContentHash   string                 `protobuf:"bytes,9,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeEntry) Reset() {
	*x = TreeEntry{}
	mi := &file_proto_core_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeEntry) ProtoMessage() {}

func (x *TreeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeEntry.ProtoReflect.Descriptor instead.
func (*TreeEntry) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *TreeEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeEntry) GetKind() EntryKind {
	if x != nil {
		return x.Kind
	}
	return EntryKind_ENTRY_KIND_UNSPECIFIED
}

func (x *TreeEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *TreeEntry) GetTreeId() string {
	if x != nil {
		return x.TreeId
	}
	return ""
}

func (x *TreeEntry) GetBlobId() string {
	if x != nil {
		return x.BlobId
	}
	return ""
}

func (x *TreeEntry) GetSymlinkTarget() string {
	if x != nil {
		return x.SymlinkTarget
	}
	return ""
}

func (x *TreeEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TreeEntry) GetContentHash() string {
	if x != nil {
		return x.ContentHash
	}
	return ""
}

var File_proto_core_v1_common_proto protoreflect.FileDescriptor

const file_proto_core_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/core/v1/common.proto\x12\x10gitslice.core.v1\"\a\n" +
	"\x05Empty\":\n" +
	"\bSliceRef\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05slice\x18\x02 \x01(\tR\x05slice\"\x88\x02\n" +
	"\tTreeEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.gitslice.core.v1.EntryKindR\x04kind\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\rR\x04mode\x12\x17\n" +
	"\atree_id\x18\x05 \x01(\tR\x06treeId\x12\x17\n" +
	"\ablob_id\x18\x06 \x01(\tR\x06blobId\x12%\n" +
	"\x0esymlink_target\x18\a \x01(\tR\rsymlinkTarget\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\x12!\n" +
	"\fcontent_hash\x18\t \x01(\tR\vcontentHash*n\n" +
	"\tEntryKind\x12\x1a\n" +
	"\x16ENTRY_KIND_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fENTRY_KIND_FILE\x10\x01\x12\x18\n" +
	"\x14ENTRY_KIND_DIRECTORY\x10\x02\x12\x16\n" +
	"\x12ENTRY_KIND_SYMLINK\x10\x03B6Z4github.com/gitslice-io/gitslice/proto/core/v1;corev1b\x06proto3"

var (
	file_proto_core_v1_common_proto_rawDescOnce sync.Once
	file_proto_core_v1_common_proto_rawDescData []byte
)

func file_proto_core_v1_common_proto_rawDescGZIP() []byte {
	file_proto_core_v1_common_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_common_proto_rawDesc), len(file_proto_core_v1_common_proto_rawDesc)))
	})
	return file_proto_core_v1_common_proto_rawDescData
}

var file_proto_core_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_core_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_core_v1_common_proto_goTypes = []any{
	(EntryKind)(0),    // 0: gitslice.core.v1.EntryKind
	(*Empty)(nil),     // 1: gitslice.core.v1.Empty
	(*SliceRef)(nil),  // 2: gitslice.core.v1.SliceRef
	(*TreeEntry)(nil), // 3: gitslice.core.v1.TreeEntry
}
var file_proto_core_v1_common_proto_depIdxs = []int32{
	0, // 0: gitslice.core.v1.TreeEntry.kind:type_name -> gitslice.core.v1.EntryKind
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_core_v1_common_proto_init() }
func file_proto_core_v1_common_proto_init() {
	if File_proto_core_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_common_proto_rawDesc), len(file_proto_core_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_core_v1_common_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_common_proto_depIdxs,
		EnumInfos:         file_proto_core_v1_common_proto_enumTypes,
		MessageInfos:      file_proto_core_v1_common_proto_msgTypes,
	}.Build()
	File_proto_core_v1_common_proto = out.File
	file_proto_core_v1_common_proto_goTypes = nil
	file_proto_core_v1_common_proto_depIdxs = nil
}
