// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: proto/core/v1/core.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FakeAccountService_Login_FullMethodName = "/gitslice.core.v1.FakeAccountService/Login"
)

// FakeAccountServiceClient is the client API for FakeAccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FakeAccountServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type fakeAccountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFakeAccountServiceClient(cc grpc.ClientConnInterface) FakeAccountServiceClient {
	return &fakeAccountServiceClient{cc}
}

func (c *fakeAccountServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, FakeAccountService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FakeAccountServiceServer is the server API for FakeAccountService service.
// All implementations should embed UnimplementedFakeAccountServiceServer
// for forward compatibility
type FakeAccountServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedFakeAccountServiceServer should be embedded to have forward compatible implementations.
type UnimplementedFakeAccountServiceServer struct {
}

func (UnimplementedFakeAccountServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

// UnsafeFakeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FakeAccountServiceServer will
// result in compilation errors.
type UnsafeFakeAccountServiceServer interface {
	mustEmbedUnimplementedFakeAccountServiceServer()
}

func RegisterFakeAccountServiceServer(s grpc.ServiceRegistrar, srv FakeAccountServiceServer) {
	s.RegisterService(&FakeAccountService_ServiceDesc, srv)
}

func _FakeAccountService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FakeAccountServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FakeAccountService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FakeAccountServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FakeAccountService_ServiceDesc is the grpc.ServiceDesc for FakeAccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FakeAccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.FakeAccountService",
	HandlerType: (*FakeAccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _FakeAccountService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}

const (
	RepositoryService_ResolvePath_FullMethodName   = "/gitslice.core.v1.RepositoryService/ResolvePath"
	RepositoryService_ListDirectory_FullMethodName = "/gitslice.core.v1.RepositoryService/ListDirectory"
	RepositoryService_ReadFile_FullMethodName      = "/gitslice.core.v1.RepositoryService/ReadFile"
	RepositoryService_GetCommit_FullMethodName     = "/gitslice.core.v1.RepositoryService/GetCommit"
	RepositoryService_GetRef_FullMethodName        = "/gitslice.core.v1.RepositoryService/GetRef"
)

// RepositoryServiceClient is the client API for RepositoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RepositoryServiceClient interface {
	ResolvePath(ctx context.Context, in *ResolvePathRequest, opts ...grpc.CallOption) (*ResolvePathResponse, error)
	ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error)
	ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error)
	GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error)
	GetRef(ctx context.Context, in *GetRefRequest, opts ...grpc.CallOption) (*Ref, error)
}

type repositoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRepositoryServiceClient(cc grpc.ClientConnInterface) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) ResolvePath(ctx context.Context, in *ResolvePathRequest, opts ...grpc.CallOption) (*ResolvePathResponse, error) {
	out := new(ResolvePathResponse)
	err := c.cc.Invoke(ctx, RepositoryService_ResolvePath_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) ListDirectory(ctx context.Context, in *ListDirectoryRequest, opts ...grpc.CallOption) (*ListDirectoryResponse, error) {
	out := new(ListDirectoryResponse)
	err := c.cc.Invoke(ctx, RepositoryService_ListDirectory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) ReadFile(ctx context.Context, in *ReadFileRequest, opts ...grpc.CallOption) (*ReadFileResponse, error) {
	out := new(ReadFileResponse)
	err := c.cc.Invoke(ctx, RepositoryService_ReadFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetCommit(ctx context.Context, in *GetCommitRequest, opts ...grpc.CallOption) (*Commit, error) {
	out := new(Commit)
	err := c.cc.Invoke(ctx, RepositoryService_GetCommit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *repositoryServiceClient) GetRef(ctx context.Context, in *GetRefRequest, opts ...grpc.CallOption) (*Ref, error) {
	out := new(Ref)
	err := c.cc.Invoke(ctx, RepositoryService_GetRef_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RepositoryServiceServer is the server API for RepositoryService service.
// All implementations should embed UnimplementedRepositoryServiceServer
// for forward compatibility
type RepositoryServiceServer interface {
	ResolvePath(context.Context, *ResolvePathRequest) (*ResolvePathResponse, error)
	ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error)
	ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error)
	GetCommit(context.Context, *GetCommitRequest) (*Commit, error)
	GetRef(context.Context, *GetRefRequest) (*Ref, error)
}

// UnimplementedRepositoryServiceServer should be embedded to have forward compatible implementations.
type UnimplementedRepositoryServiceServer struct {
}

func (UnimplementedRepositoryServiceServer) ResolvePath(context.Context, *ResolvePathRequest) (*ResolvePathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePath not implemented")
}
func (UnimplementedRepositoryServiceServer) ListDirectory(context.Context, *ListDirectoryRequest) (*ListDirectoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDirectory not implemented")
}
func (UnimplementedRepositoryServiceServer) ReadFile(context.Context, *ReadFileRequest) (*ReadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadFile not implemented")
}
func (UnimplementedRepositoryServiceServer) GetCommit(context.Context, *GetCommitRequest) (*Commit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommit not implemented")
}
func (UnimplementedRepositoryServiceServer) GetRef(context.Context, *GetRefRequest) (*Ref, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRef not implemented")
}

// UnsafeRepositoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RepositoryServiceServer will
// result in compilation errors.
type UnsafeRepositoryServiceServer interface {
	mustEmbedUnimplementedRepositoryServiceServer()
}

func RegisterRepositoryServiceServer(s grpc.ServiceRegistrar, srv RepositoryServiceServer) {
	s.RegisterService(&RepositoryService_ServiceDesc, srv)
}

func _RepositoryService_ResolvePath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).ResolvePath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_ResolvePath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).ResolvePath(ctx, req.(*ResolvePathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_ListDirectory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDirectoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).ListDirectory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_ListDirectory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).ListDirectory(ctx, req.(*ListDirectoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_ReadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).ReadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_ReadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).ReadFile(ctx, req.(*ReadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_GetCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetCommit(ctx, req.(*GetCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RepositoryService_GetRef_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRefRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).GetRef(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RepositoryService_GetRef_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).GetRef(ctx, req.(*GetRefRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RepositoryService_ServiceDesc is the grpc.ServiceDesc for RepositoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RepositoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolvePath",
			Handler:    _RepositoryService_ResolvePath_Handler,
		},
		{
			MethodName: "ListDirectory",
			Handler:    _RepositoryService_ListDirectory_Handler,
		},
		{
			MethodName: "ReadFile",
			Handler:    _RepositoryService_ReadFile_Handler,
		},
		{
			MethodName: "GetCommit",
			Handler:    _RepositoryService_GetCommit_Handler,
		},
		{
			MethodName: "GetRef",
			Handler:    _RepositoryService_GetRef_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}

const (
	BlobService_GetBlobStatus_FullMethodName = "/gitslice.core.v1.BlobService/GetBlobStatus"
	BlobService_UploadBlob_FullMethodName    = "/gitslice.core.v1.BlobService/UploadBlob"
)

// BlobServiceClient is the client API for BlobService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlobServiceClient interface {
	GetBlobStatus(ctx context.Context, in *GetBlobStatusRequest, opts ...grpc.CallOption) (*GetBlobStatusResponse, error)
	UploadBlob(ctx context.Context, in *UploadBlobRequest, opts ...grpc.CallOption) (*UploadBlobResponse, error)
}

type blobServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobServiceClient(cc grpc.ClientConnInterface) BlobServiceClient {
	return &blobServiceClient{cc}
}

func (c *blobServiceClient) GetBlobStatus(ctx context.Context, in *GetBlobStatusRequest, opts ...grpc.CallOption) (*GetBlobStatusResponse, error) {
	out := new(GetBlobStatusResponse)
	err := c.cc.Invoke(ctx, BlobService_GetBlobStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobServiceClient) UploadBlob(ctx context.Context, in *UploadBlobRequest, opts ...grpc.CallOption) (*UploadBlobResponse, error) {
	out := new(UploadBlobResponse)
	err := c.cc.Invoke(ctx, BlobService_UploadBlob_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobServiceServer is the server API for BlobService service.
// All implementations should embed UnimplementedBlobServiceServer
// for forward compatibility
type BlobServiceServer interface {
	GetBlobStatus(context.Context, *GetBlobStatusRequest) (*GetBlobStatusResponse, error)
	UploadBlob(context.Context, *UploadBlobRequest) (*UploadBlobResponse, error)
}

// UnimplementedBlobServiceServer should be embedded to have forward compatible implementations.
type UnimplementedBlobServiceServer struct {
}

func (UnimplementedBlobServiceServer) GetBlobStatus(context.Context, *GetBlobStatusRequest) (*GetBlobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlobStatus not implemented")
}
func (UnimplementedBlobServiceServer) UploadBlob(context.Context, *UploadBlobRequest) (*UploadBlobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadBlob not implemented")
}

// UnsafeBlobServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobServiceServer will
// result in compilation errors.
type UnsafeBlobServiceServer interface {
	mustEmbedUnimplementedBlobServiceServer()
}

func RegisterBlobServiceServer(s grpc.ServiceRegistrar, srv BlobServiceServer) {
	s.RegisterService(&BlobService_ServiceDesc, srv)
}

func _BlobService_GetBlobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).GetBlobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_GetBlobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).GetBlobStatus(ctx, req.(*GetBlobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobService_UploadBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobServiceServer).UploadBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobService_UploadBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobServiceServer).UploadBlob(ctx, req.(*UploadBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobService_ServiceDesc is the grpc.ServiceDesc for BlobService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.BlobService",
	HandlerType: (*BlobServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlobStatus",
			Handler:    _BlobService_GetBlobStatus_Handler,
		},
		{
			MethodName: "UploadBlob",
			Handler:    _BlobService_UploadBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}

const (
	SliceService_ResolveSlice_FullMethodName          = "/gitslice.core.v1.SliceService/ResolveSlice"
	SliceService_GetSlice_FullMethodName              = "/gitslice.core.v1.SliceService/GetSlice"
	SliceService_ListSlices_FullMethodName            = "/gitslice.core.v1.SliceService/ListSlices"
	SliceService_UpdateSliceDefinition_FullMethodName = "/gitslice.core.v1.SliceService/UpdateSliceDefinition"
)

// SliceServiceClient is the client API for SliceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SliceServiceClient interface {
	ResolveSlice(ctx context.Context, in *ResolveSliceRequest, opts ...grpc.CallOption) (*Slice, error)
	GetSlice(ctx context.Context, in *GetSliceRequest, opts ...grpc.CallOption) (*Slice, error)
	ListSlices(ctx context.Context, in *ListSlicesRequest, opts ...grpc.CallOption) (*ListSlicesResponse, error)
	UpdateSliceDefinition(ctx context.Context, in *UpdateSliceDefinitionRequest, opts ...grpc.CallOption) (*SliceDefinition, error)
}

type sliceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSliceServiceClient(cc grpc.ClientConnInterface) SliceServiceClient {
	return &sliceServiceClient{cc}
}

func (c *sliceServiceClient) ResolveSlice(ctx context.Context, in *ResolveSliceRequest, opts ...grpc.CallOption) (*Slice, error) {
	out := new(Slice)
	err := c.cc.Invoke(ctx, SliceService_ResolveSlice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) GetSlice(ctx context.Context, in *GetSliceRequest, opts ...grpc.CallOption) (*Slice, error) {
	out := new(Slice)
	err := c.cc.Invoke(ctx, SliceService_GetSlice_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) ListSlices(ctx context.Context, in *ListSlicesRequest, opts ...grpc.CallOption) (*ListSlicesResponse, error) {
	out := new(ListSlicesResponse)
	err := c.cc.Invoke(ctx, SliceService_ListSlices_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sliceServiceClient) UpdateSliceDefinition(ctx context.Context, in *UpdateSliceDefinitionRequest, opts ...grpc.CallOption) (*SliceDefinition, error) {
	out := new(SliceDefinition)
	err := c.cc.Invoke(ctx, SliceService_UpdateSliceDefinition_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SliceServiceServer is the server API for SliceService service.
// All implementations should embed UnimplementedSliceServiceServer
// for forward compatibility
type SliceServiceServer interface {
	ResolveSlice(context.Context, *ResolveSliceRequest) (*Slice, error)
	GetSlice(context.Context, *GetSliceRequest) (*Slice, error)
	ListSlices(context.Context, *ListSlicesRequest) (*ListSlicesResponse, error)
	UpdateSliceDefinition(context.Context, *UpdateSliceDefinitionRequest) (*SliceDefinition, error)
}

// UnimplementedSliceServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSliceServiceServer struct {
}

func (UnimplementedSliceServiceServer) ResolveSlice(context.Context, *ResolveSliceRequest) (*Slice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveSlice not implemented")
}
func (UnimplementedSliceServiceServer) GetSlice(context.Context, *GetSliceRequest) (*Slice, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlice not implemented")
}
func (UnimplementedSliceServiceServer) ListSlices(context.Context, *ListSlicesRequest) (*ListSlicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSlices not implemented")
}
func (UnimplementedSliceServiceServer) UpdateSliceDefinition(context.Context, *UpdateSliceDefinitionRequest) (*SliceDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSliceDefinition not implemented")
}

// UnsafeSliceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SliceServiceServer will
// result in compilation errors.
type UnsafeSliceServiceServer interface {
	mustEmbedUnimplementedSliceServiceServer()
}

func RegisterSliceServiceServer(s grpc.ServiceRegistrar, srv SliceServiceServer) {
	s.RegisterService(&SliceService_ServiceDesc, srv)
}

func _SliceService_ResolveSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ResolveSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_ResolveSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ResolveSlice(ctx, req.(*ResolveSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_GetSlice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSliceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).GetSlice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_GetSlice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).GetSlice(ctx, req.(*GetSliceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_ListSlices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSlicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).ListSlices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_ListSlices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).ListSlices(ctx, req.(*ListSlicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SliceService_UpdateSliceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSliceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SliceServiceServer).UpdateSliceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SliceService_UpdateSliceDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SliceServiceServer).UpdateSliceDefinition(ctx, req.(*UpdateSliceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SliceService_ServiceDesc is the grpc.ServiceDesc for SliceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SliceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.SliceService",
	HandlerType: (*SliceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveSlice",
			Handler:    _SliceService_ResolveSlice_Handler,
		},
		{
			MethodName: "GetSlice",
			Handler:    _SliceService_GetSlice_Handler,
		},
		{
			MethodName: "ListSlices",
			Handler:    _SliceService_ListSlices_Handler,
		},
		{
			MethodName: "UpdateSliceDefinition",
			Handler:    _SliceService_UpdateSliceDefinition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}

const (
	WorkspaceService_GetWorkspaceState_FullMethodName        = "/gitslice.core.v1.WorkspaceService/GetWorkspaceState"
	WorkspaceService_HydratePaths_FullMethodName             = "/gitslice.core.v1.WorkspaceService/HydratePaths"
	WorkspaceService_ValidateWorkspaceDiff_FullMethodName    = "/gitslice.core.v1.WorkspaceService/ValidateWorkspaceDiff"
	WorkspaceService_RecordWorkspaceOperation_FullMethodName = "/gitslice.core.v1.WorkspaceService/RecordWorkspaceOperation"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceServiceClient interface {
	GetWorkspaceState(ctx context.Context, in *GetWorkspaceStateRequest, opts ...grpc.CallOption) (*WorkspaceState, error)
	HydratePaths(ctx context.Context, in *HydratePathsRequest, opts ...grpc.CallOption) (*HydratePathsResponse, error)
	ValidateWorkspaceDiff(ctx context.Context, in *ValidateWorkspaceDiffRequest, opts ...grpc.CallOption) (*ValidateWorkspaceDiffResponse, error)
	RecordWorkspaceOperation(ctx context.Context, in *RecordWorkspaceOperationRequest, opts ...grpc.CallOption) (*RecordWorkspaceOperationResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) GetWorkspaceState(ctx context.Context, in *GetWorkspaceStateRequest, opts ...grpc.CallOption) (*WorkspaceState, error) {
	out := new(WorkspaceState)
	err := c.cc.Invoke(ctx, WorkspaceService_GetWorkspaceState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) HydratePaths(ctx context.Context, in *HydratePathsRequest, opts ...grpc.CallOption) (*HydratePathsResponse, error) {
	out := new(HydratePathsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_HydratePaths_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ValidateWorkspaceDiff(ctx context.Context, in *ValidateWorkspaceDiffRequest, opts ...grpc.CallOption) (*ValidateWorkspaceDiffResponse, error) {
	out := new(ValidateWorkspaceDiffResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ValidateWorkspaceDiff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) RecordWorkspaceOperation(ctx context.Context, in *RecordWorkspaceOperationRequest, opts ...grpc.CallOption) (*RecordWorkspaceOperationResponse, error) {
	out := new(RecordWorkspaceOperationResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_RecordWorkspaceOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations should embed UnimplementedWorkspaceServiceServer
// for forward compatibility
type WorkspaceServiceServer interface {
	GetWorkspaceState(context.Context, *GetWorkspaceStateRequest) (*WorkspaceState, error)
	HydratePaths(context.Context, *HydratePathsRequest) (*HydratePathsResponse, error)
	ValidateWorkspaceDiff(context.Context, *ValidateWorkspaceDiffRequest) (*ValidateWorkspaceDiffResponse, error)
	RecordWorkspaceOperation(context.Context, *RecordWorkspaceOperationRequest) (*RecordWorkspaceOperationResponse, error)
}

// UnimplementedWorkspaceServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWorkspaceServiceServer struct {
}

func (UnimplementedWorkspaceServiceServer) GetWorkspaceState(context.Context, *GetWorkspaceStateRequest) (*WorkspaceState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceState not implemented")
}
func (UnimplementedWorkspaceServiceServer) HydratePaths(context.Context, *HydratePathsRequest) (*HydratePathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HydratePaths not implemented")
}
func (UnimplementedWorkspaceServiceServer) ValidateWorkspaceDiff(context.Context, *ValidateWorkspaceDiffRequest) (*ValidateWorkspaceDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateWorkspaceDiff not implemented")
}
func (UnimplementedWorkspaceServiceServer) RecordWorkspaceOperation(context.Context, *RecordWorkspaceOperationRequest) (*RecordWorkspaceOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordWorkspaceOperation not implemented")
}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_GetWorkspaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetWorkspaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetWorkspaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetWorkspaceState(ctx, req.(*GetWorkspaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_HydratePaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HydratePathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).HydratePaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_HydratePaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).HydratePaths(ctx, req.(*HydratePathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ValidateWorkspaceDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateWorkspaceDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ValidateWorkspaceDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ValidateWorkspaceDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ValidateWorkspaceDiff(ctx, req.(*ValidateWorkspaceDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_RecordWorkspaceOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWorkspaceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).RecordWorkspaceOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_RecordWorkspaceOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).RecordWorkspaceOperation(ctx, req.(*RecordWorkspaceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceState",
			Handler:    _WorkspaceService_GetWorkspaceState_Handler,
		},
		{
			MethodName: "HydratePaths",
			Handler:    _WorkspaceService_HydratePaths_Handler,
		},
		{
			MethodName: "ValidateWorkspaceDiff",
			Handler:    _WorkspaceService_ValidateWorkspaceDiff_Handler,
		},
		{
			MethodName: "RecordWorkspaceOperation",
			Handler:    _WorkspaceService_RecordWorkspaceOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}

const (
	ChangesetService_CreateChangeset_FullMethodName  = "/gitslice.core.v1.ChangesetService/CreateChangeset"
	ChangesetService_GetChangeset_FullMethodName     = "/gitslice.core.v1.ChangesetService/GetChangeset"
	ChangesetService_UpdateChangeset_FullMethodName  = "/gitslice.core.v1.ChangesetService/UpdateChangeset"
	ChangesetService_SubmitChangeset_FullMethodName  = "/gitslice.core.v1.ChangesetService/SubmitChangeset"
	ChangesetService_AbandonChangeset_FullMethodName = "/gitslice.core.v1.ChangesetService/AbandonChangeset"
)

// ChangesetServiceClient is the client API for ChangesetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChangesetServiceClient interface {
	CreateChangeset(ctx context.Context, in *CreateChangesetRequest, opts ...grpc.CallOption) (*Changeset, error)
	GetChangeset(ctx context.Context, in *GetChangesetRequest, opts ...grpc.CallOption) (*Changeset, error)
	UpdateChangeset(ctx context.Context, in *UpdateChangesetRequest, opts ...grpc.CallOption) (*Patchset, error)
	SubmitChangeset(ctx context.Context, in *SubmitChangesetRequest, opts ...grpc.CallOption) (*SubmitChangesetResponse, error)
	AbandonChangeset(ctx context.Context, in *AbandonChangesetRequest, opts ...grpc.CallOption) (*Empty, error)
}

type changesetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChangesetServiceClient(cc grpc.ClientConnInterface) ChangesetServiceClient {
	return &changesetServiceClient{cc}
}

func (c *changesetServiceClient) CreateChangeset(ctx context.Context, in *CreateChangesetRequest, opts ...grpc.CallOption) (*Changeset, error) {
	out := new(Changeset)
	err := c.cc.Invoke(ctx, ChangesetService_CreateChangeset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changesetServiceClient) GetChangeset(ctx context.Context, in *GetChangesetRequest, opts ...grpc.CallOption) (*Changeset, error) {
	out := new(Changeset)
	err := c.cc.Invoke(ctx, ChangesetService_GetChangeset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changesetServiceClient) UpdateChangeset(ctx context.Context, in *UpdateChangesetRequest, opts ...grpc.CallOption) (*Patchset, error) {
	out := new(Patchset)
	err := c.cc.Invoke(ctx, ChangesetService_UpdateChangeset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changesetServiceClient) SubmitChangeset(ctx context.Context, in *SubmitChangesetRequest, opts ...grpc.CallOption) (*SubmitChangesetResponse, error) {
	out := new(SubmitChangesetResponse)
	err := c.cc.Invoke(ctx, ChangesetService_SubmitChangeset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *changesetServiceClient) AbandonChangeset(ctx context.Context, in *AbandonChangesetRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, ChangesetService_AbandonChangeset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChangesetServiceServer is the server API for ChangesetService service.
// All implementations should embed UnimplementedChangesetServiceServer
// for forward compatibility
type ChangesetServiceServer interface {
	CreateChangeset(context.Context, *CreateChangesetRequest) (*Changeset, error)
	GetChangeset(context.Context, *GetChangesetRequest) (*Changeset, error)
	UpdateChangeset(context.Context, *UpdateChangesetRequest) (*Patchset, error)
	SubmitChangeset(context.Context, *SubmitChangesetRequest) (*SubmitChangesetResponse, error)
	AbandonChangeset(context.Context, *AbandonChangesetRequest) (*Empty, error)
}

// UnimplementedChangesetServiceServer should be embedded to have forward compatible implementations.
type UnimplementedChangesetServiceServer struct {
}

func (UnimplementedChangesetServiceServer) CreateChangeset(context.Context, *CreateChangesetRequest) (*Changeset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateChangeset not implemented")
}
func (UnimplementedChangesetServiceServer) GetChangeset(context.Context, *GetChangesetRequest) (*Changeset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChangeset not implemented")
}
func (UnimplementedChangesetServiceServer) UpdateChangeset(context.Context, *UpdateChangesetRequest) (*Patchset, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateChangeset not implemented")
}
func (UnimplementedChangesetServiceServer) SubmitChangeset(context.Context, *SubmitChangesetRequest) (*SubmitChangesetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitChangeset not implemented")
}
func (UnimplementedChangesetServiceServer) AbandonChangeset(context.Context, *AbandonChangesetRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbandonChangeset not implemented")
}

// UnsafeChangesetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChangesetServiceServer will
// result in compilation errors.
type UnsafeChangesetServiceServer interface {
	mustEmbedUnimplementedChangesetServiceServer()
}

func RegisterChangesetServiceServer(s grpc.ServiceRegistrar, srv ChangesetServiceServer) {
	s.RegisterService(&ChangesetService_ServiceDesc, srv)
}

func _ChangesetService_CreateChangeset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChangesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangesetServiceServer).CreateChangeset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangesetService_CreateChangeset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangesetServiceServer).CreateChangeset(ctx, req.(*CreateChangesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangesetService_GetChangeset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetChangesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangesetServiceServer).GetChangeset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangesetService_GetChangeset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangesetServiceServer).GetChangeset(ctx, req.(*GetChangesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangesetService_UpdateChangeset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChangesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangesetServiceServer).UpdateChangeset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangesetService_UpdateChangeset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangesetServiceServer).UpdateChangeset(ctx, req.(*UpdateChangesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangesetService_SubmitChangeset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitChangesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangesetServiceServer).SubmitChangeset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangesetService_SubmitChangeset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangesetServiceServer).SubmitChangeset(ctx, req.(*SubmitChangesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChangesetService_AbandonChangeset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbandonChangesetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChangesetServiceServer).AbandonChangeset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChangesetService_AbandonChangeset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChangesetServiceServer).AbandonChangeset(ctx, req.(*AbandonChangesetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChangesetService_ServiceDesc is the grpc.ServiceDesc for ChangesetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChangesetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.ChangesetService",
	HandlerType: (*ChangesetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateChangeset",
			Handler:    _ChangesetService_CreateChangeset_Handler,
		},
		{
			MethodName: "GetChangeset",
			Handler:    _ChangesetService_GetChangeset_Handler,
		},
		{
			MethodName: "UpdateChangeset",
			Handler:    _ChangesetService_UpdateChangeset_Handler,
		},
		{
			MethodName: "SubmitChangeset",
			Handler:    _ChangesetService_SubmitChangeset_Handler,
		},
		{
			MethodName: "AbandonChangeset",
			Handler:    _ChangesetService_AbandonChangeset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/core.proto",
}
