// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/core/v1/slice.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Slice struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ref            *SliceRef              `protobuf:"bytes,2,opt,name=ref,proto3" json:"ref,omitempty"`
	Definition     *SliceDefinition       `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	DefinitionHash string                 `protobuf:"bytes,4,opt,name=definition_hash,json=definitionHash,proto3" json:"definition_hash,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Slice) Reset() {
	*x = Slice{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slice) ProtoMessage() {}

func (x *Slice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slice.ProtoReflect.Descriptor instead.
func (*Slice) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{0}
}

func (x *Slice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slice) GetRef() *SliceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

func (x *Slice) GetDefinition() *SliceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

func (x *Slice) GetDefinitionHash() string {
	if x != nil {
		return x.DefinitionHash
	}
	return ""
}

type SliceDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	IncludedPaths []string               `protobuf:"bytes,3,rep,name=included_paths,json=includedPaths,proto3" json:"included_paths,omitempty"`
	Visibility    string                 `protobuf:"bytes,4,opt,name=visibility,proto3" json:"visibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SliceDefinition) Reset() {
	*x = SliceDefinition{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceDefinition) ProtoMessage() {}

func (x *SliceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceDefinition.ProtoReflect.Descriptor instead.
func (*SliceDefinition) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{1}
}

func (x *SliceDefinition) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *SliceDefinition) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SliceDefinition) GetIncludedPaths() []string {
	if x != nil {
		return x.IncludedPaths
	}
	return nil
}

func (x *SliceDefinition) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

type ResolveSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           *SliceRef              `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSliceRequest) Reset() {
	*x = ResolveSliceRequest{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSliceRequest) ProtoMessage() {}

func (x *ResolveSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSliceRequest.ProtoReflect.Descriptor instead.
func (*ResolveSliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{2}
}

func (x *ResolveSliceRequest) GetRef() *SliceRef {
	if x != nil {
		return x.Ref
	}
	return nil
}

type GetSliceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SliceId       string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSliceRequest) Reset() {
	*x = GetSliceRequest{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSliceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSliceRequest) ProtoMessage() {}

func (x *GetSliceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSliceRequest.ProtoReflect.Descriptor instead.
func (*GetSliceRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{3}
}

func (x *GetSliceRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

type ListSlicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesRequest) Reset() {
	*x = ListSlicesRequest{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesRequest) ProtoMessage() {}

func (x *ListSlicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesRequest.ProtoReflect.Descriptor instead.
func (*ListSlicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{4}
}

func (x *ListSlicesRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ListSlicesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListSlicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSlicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slices        []*Slice               `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSlicesResponse) Reset() {
	*x = ListSlicesResponse{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSlicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSlicesResponse) ProtoMessage() {}

func (x *ListSlicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSlicesResponse.ProtoReflect.Descriptor instead.
func (*ListSlicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{5}
}

func (x *ListSlicesResponse) GetSlices() []*Slice {
	if x != nil {
		return x.Slices
	}
	return nil
}

func (x *ListSlicesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type UpdateSliceDefinitionRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SliceId                string                 `protobuf:"bytes,1,opt,name=slice_id,json=sliceId,proto3" json:"slice_id,omitempty"`
	ExpectedDefinitionHash string                 `protobuf:"bytes,2,opt,name=expected_definition_hash,json=expectedDefinitionHash,proto3" json:"expected_definition_hash,omitempty"`
	Definition             *SliceDefinition       `protobuf:"bytes,3,opt,name=definition,proto3" json:"definition,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UpdateSliceDefinitionRequest) Reset() {
	*x = UpdateSliceDefinitionRequest{}
	mi := &file_proto_core_v1_slice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSliceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSliceDefinitionRequest) ProtoMessage() {}

func (x *UpdateSliceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_v1_slice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSliceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSliceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_proto_core_v1_slice_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateSliceDefinitionRequest) GetSliceId() string {
	if x != nil {
		return x.SliceId
	}
	return ""
}

func (x *UpdateSliceDefinitionRequest) GetExpectedDefinitionHash() string {
	if x != nil {
		return x.ExpectedDefinitionHash
	}
	return ""
}

func (x *UpdateSliceDefinitionRequest) GetDefinition() *SliceDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

var File_proto_core_v1_slice_proto protoreflect.FileDescriptor

const file_proto_core_v1_slice_proto_rawDesc = "" +
	"\n" +
	"\x19proto/core/v1/slice.proto\x12\x10gitslice.core.v1\x1a\x1aproto/core/v1/common.proto\"\xb1\x01\n" +
	"\x05Slice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x03ref\x18\x02 \x01(\v2\x1a.gitslice.core.v1.SliceRefR\x03ref\x12A\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2!.gitslice.core.v1.SliceDefinitionR\n" +
	"definition\x12'\n" +
	"\x0fdefinition_hash\x18\x04 \x01(\tR\x0edefinitionHash\"\x8d\x01\n" +
	"\x0fSliceDefinition\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12%\n" +
	"\x0eincluded_paths\x18\x03 \x03(\tR\rincludedPaths\x12\x1e\n" +
	"\n" +
	"visibility\x18\x04 \x01(\tR\n" +
	"visibility\"C\n" +
	"\x13ResolveSliceRequest\x12,\n" +
	"\x03ref\x18\x01 \x01(\v2\x1a.gitslice.core.v1.SliceRefR\x03ref\",\n" +
	"\x0fGetSliceRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\"b\n" +
	"\x11ListSlicesRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"f\n" +
	"\x12ListSlicesResponse\x12/\n" +
	"\x06slices\x18\x01 \x03(\v2\x17.gitslice.core.v1.SliceR\x06slices\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"\xb6\x01\n" +
	"\x1cUpdateSliceDefinitionRequest\x12\x19\n" +
	"\bslice_id\x18\x01 \x01(\tR\asliceId\x128\n" +
	"\x18expected_definition_hash\x18\x02 \x01(\tR\x16expectedDefinitionHash\x12A\n" +
	"\n" +
	"definition\x18\x03 \x01(\v2!.gitslice.core.v1.SliceDefinitionR\n" +
	"definition2\xeb\x02\n" +
	"\fSliceService\x12N\n" +
	"\fResolveSlice\x12%.gitslice.core.v1.ResolveSliceRequest\x1a\x17.gitslice.core.v1.Slice\x12F\n" +
	"\bGetSlice\x12!.gitslice.core.v1.GetSliceRequest\x1a\x17.gitslice.core.v1.Slice\x12W\n" +
	"\n" +
	"ListSlices\x12#.gitslice.core.v1.ListSlicesRequest\x1a$.gitslice.core.v1.ListSlicesResponse\x12j\n" +
	"\x15UpdateSliceDefinition\x12..gitslice.core.v1.UpdateSliceDefinitionRequest\x1a!.gitslice.core.v1.SliceDefinitionB6Z4github.com/gitslice-io/gitslice/proto/core/v1;corev1b\x06proto3"

var (
	file_proto_core_v1_slice_proto_rawDescOnce sync.Once
	file_proto_core_v1_slice_proto_rawDescData []byte
)

func file_proto_core_v1_slice_proto_rawDescGZIP() []byte {
	file_proto_core_v1_slice_proto_rawDescOnce.Do(func() {
		file_proto_core_v1_slice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_v1_slice_proto_rawDesc), len(file_proto_core_v1_slice_proto_rawDesc)))
	})
	return file_proto_core_v1_slice_proto_rawDescData
}

var file_proto_core_v1_slice_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_core_v1_slice_proto_goTypes = []any{
	(*Slice)(nil),                        // 0: gitslice.core.v1.Slice
	(*SliceDefinition)(nil),              // 1: gitslice.core.v1.SliceDefinition
	(*ResolveSliceRequest)(nil),          // 2: gitslice.core.v1.ResolveSliceRequest
	(*GetSliceRequest)(nil),              // 3: gitslice.core.v1.GetSliceRequest
	(*ListSlicesRequest)(nil),            // 4: gitslice.core.v1.ListSlicesRequest
	(*ListSlicesResponse)(nil),           // 5: gitslice.core.v1.ListSlicesResponse
	(*UpdateSliceDefinitionRequest)(nil), // 6: gitslice.core.v1.UpdateSliceDefinitionRequest
	(*SliceRef)(nil),                     // 7: gitslice.core.v1.SliceRef
}
var file_proto_core_v1_slice_proto_depIdxs = []int32{
	7, // 0: gitslice.core.v1.Slice.ref:type_name -> gitslice.core.v1.SliceRef
	1, // 1: gitslice.core.v1.Slice.definition:type_name -> gitslice.core.v1.SliceDefinition
	7, // 2: gitslice.core.v1.ResolveSliceRequest.ref:type_name -> gitslice.core.v1.SliceRef
	0, // 3: gitslice.core.v1.ListSlicesResponse.slices:type_name -> gitslice.core.v1.Slice
	1, // 4: gitslice.core.v1.UpdateSliceDefinitionRequest.definition:type_name -> gitslice.core.v1.SliceDefinition
	2, // 5: gitslice.core.v1.SliceService.ResolveSlice:input_type -> gitslice.core.v1.ResolveSliceRequest
	3, // 6: gitslice.core.v1.SliceService.GetSlice:input_type -> gitslice.core.v1.GetSliceRequest
	4, // 7: gitslice.core.v1.SliceService.ListSlices:input_type -> gitslice.core.v1.ListSlicesRequest
	6, // 8: gitslice.core.v1.SliceService.UpdateSliceDefinition:input_type -> gitslice.core.v1.UpdateSliceDefinitionRequest
	0, // 9: gitslice.core.v1.SliceService.ResolveSlice:output_type -> gitslice.core.v1.Slice
	0, // 10: gitslice.core.v1.SliceService.GetSlice:output_type -> gitslice.core.v1.Slice
	5, // 11: gitslice.core.v1.SliceService.ListSlices:output_type -> gitslice.core.v1.ListSlicesResponse
	1, // 12: gitslice.core.v1.SliceService.UpdateSliceDefinition:output_type -> gitslice.core.v1.SliceDefinition
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_core_v1_slice_proto_init() }
func file_proto_core_v1_slice_proto_init() {
	if File_proto_core_v1_slice_proto != nil {
		return
	}
	file_proto_core_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_v1_slice_proto_rawDesc), len(file_proto_core_v1_slice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_core_v1_slice_proto_goTypes,
		DependencyIndexes: file_proto_core_v1_slice_proto_depIdxs,
		MessageInfos:      file_proto_core_v1_slice_proto_msgTypes,
	}.Build()
	File_proto_core_v1_slice_proto = out.File
	file_proto_core_v1_slice_proto_goTypes = nil
	file_proto_core_v1_slice_proto_depIdxs = nil
}
