// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.4
// source: proto/core/v1/workspace.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	WorkspaceService_GetWorkspaceState_FullMethodName        = "/gitslice.core.v1.WorkspaceService/GetWorkspaceState"
	WorkspaceService_HydratePaths_FullMethodName             = "/gitslice.core.v1.WorkspaceService/HydratePaths"
	WorkspaceService_ValidateWorkspaceDiff_FullMethodName    = "/gitslice.core.v1.WorkspaceService/ValidateWorkspaceDiff"
	WorkspaceService_RecordWorkspaceOperation_FullMethodName = "/gitslice.core.v1.WorkspaceService/RecordWorkspaceOperation"
)

// WorkspaceServiceClient is the client API for WorkspaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkspaceServiceClient interface {
	GetWorkspaceState(ctx context.Context, in *GetWorkspaceStateRequest, opts ...grpc.CallOption) (*WorkspaceState, error)
	HydratePaths(ctx context.Context, in *HydratePathsRequest, opts ...grpc.CallOption) (*HydratePathsResponse, error)
	ValidateWorkspaceDiff(ctx context.Context, in *ValidateWorkspaceDiffRequest, opts ...grpc.CallOption) (*ValidateWorkspaceDiffResponse, error)
	RecordWorkspaceOperation(ctx context.Context, in *RecordWorkspaceOperationRequest, opts ...grpc.CallOption) (*RecordWorkspaceOperationResponse, error)
}

type workspaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkspaceServiceClient(cc grpc.ClientConnInterface) WorkspaceServiceClient {
	return &workspaceServiceClient{cc}
}

func (c *workspaceServiceClient) GetWorkspaceState(ctx context.Context, in *GetWorkspaceStateRequest, opts ...grpc.CallOption) (*WorkspaceState, error) {
	out := new(WorkspaceState)
	err := c.cc.Invoke(ctx, WorkspaceService_GetWorkspaceState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) HydratePaths(ctx context.Context, in *HydratePathsRequest, opts ...grpc.CallOption) (*HydratePathsResponse, error) {
	out := new(HydratePathsResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_HydratePaths_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) ValidateWorkspaceDiff(ctx context.Context, in *ValidateWorkspaceDiffRequest, opts ...grpc.CallOption) (*ValidateWorkspaceDiffResponse, error) {
	out := new(ValidateWorkspaceDiffResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_ValidateWorkspaceDiff_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workspaceServiceClient) RecordWorkspaceOperation(ctx context.Context, in *RecordWorkspaceOperationRequest, opts ...grpc.CallOption) (*RecordWorkspaceOperationResponse, error) {
	out := new(RecordWorkspaceOperationResponse)
	err := c.cc.Invoke(ctx, WorkspaceService_RecordWorkspaceOperation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkspaceServiceServer is the server API for WorkspaceService service.
// All implementations should embed UnimplementedWorkspaceServiceServer
// for forward compatibility
type WorkspaceServiceServer interface {
	GetWorkspaceState(context.Context, *GetWorkspaceStateRequest) (*WorkspaceState, error)
	HydratePaths(context.Context, *HydratePathsRequest) (*HydratePathsResponse, error)
	ValidateWorkspaceDiff(context.Context, *ValidateWorkspaceDiffRequest) (*ValidateWorkspaceDiffResponse, error)
	RecordWorkspaceOperation(context.Context, *RecordWorkspaceOperationRequest) (*RecordWorkspaceOperationResponse, error)
}

// UnimplementedWorkspaceServiceServer should be embedded to have forward compatible implementations.
type UnimplementedWorkspaceServiceServer struct {
}

func (UnimplementedWorkspaceServiceServer) GetWorkspaceState(context.Context, *GetWorkspaceStateRequest) (*WorkspaceState, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorkspaceState not implemented")
}
func (UnimplementedWorkspaceServiceServer) HydratePaths(context.Context, *HydratePathsRequest) (*HydratePathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HydratePaths not implemented")
}
func (UnimplementedWorkspaceServiceServer) ValidateWorkspaceDiff(context.Context, *ValidateWorkspaceDiffRequest) (*ValidateWorkspaceDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateWorkspaceDiff not implemented")
}
func (UnimplementedWorkspaceServiceServer) RecordWorkspaceOperation(context.Context, *RecordWorkspaceOperationRequest) (*RecordWorkspaceOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordWorkspaceOperation not implemented")
}

// UnsafeWorkspaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkspaceServiceServer will
// result in compilation errors.
type UnsafeWorkspaceServiceServer interface {
	mustEmbedUnimplementedWorkspaceServiceServer()
}

func RegisterWorkspaceServiceServer(s grpc.ServiceRegistrar, srv WorkspaceServiceServer) {
	s.RegisterService(&WorkspaceService_ServiceDesc, srv)
}

func _WorkspaceService_GetWorkspaceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkspaceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).GetWorkspaceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_GetWorkspaceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).GetWorkspaceState(ctx, req.(*GetWorkspaceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_HydratePaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HydratePathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).HydratePaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_HydratePaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).HydratePaths(ctx, req.(*HydratePathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_ValidateWorkspaceDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateWorkspaceDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).ValidateWorkspaceDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_ValidateWorkspaceDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).ValidateWorkspaceDiff(ctx, req.(*ValidateWorkspaceDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkspaceService_RecordWorkspaceOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordWorkspaceOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkspaceServiceServer).RecordWorkspaceOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkspaceService_RecordWorkspaceOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkspaceServiceServer).RecordWorkspaceOperation(ctx, req.(*RecordWorkspaceOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkspaceService_ServiceDesc is the grpc.ServiceDesc for WorkspaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkspaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gitslice.core.v1.WorkspaceService",
	HandlerType: (*WorkspaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWorkspaceState",
			Handler:    _WorkspaceService_GetWorkspaceState_Handler,
		},
		{
			MethodName: "HydratePaths",
			Handler:    _WorkspaceService_HydratePaths_Handler,
		},
		{
			MethodName: "ValidateWorkspaceDiff",
			Handler:    _WorkspaceService_ValidateWorkspaceDiff_Handler,
		},
		{
			MethodName: "RecordWorkspaceOperation",
			Handler:    _WorkspaceService_RecordWorkspaceOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/core/v1/workspace.proto",
}
